// -------------------------------------------------------------
// 
// File Name: /home/draco/git/adi_dma_testing/iq_dma_example/hdl_ip/hdlsrc/rx_dma_test/rx_dma_test_src_FilterTapSystolicWvldin.v
// Created: 2025-08-22 09:27:16
// 
// Generated by MATLAB 24.1, HDL Coder 24.1, and Simulink 24.1
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: rx_dma_test_src_FilterTapSystolicWvldin
// Source Path: rx_dma_test/LDCR_D/Channelizer_CH1/FilterBank/subFilter/FilterTapSystolicWvldin
// Hierarchy Level: 4
// Model version: 9.625
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module rx_dma_test_src_FilterTapSystolicWvldin
          (clk,
           enb,
           dinReg2_0_re,
           coefIn_0,
           addin,
           dinRegVld,
           dinDly2,
           tapout);


  input   clk;
  input   enb;
  input   signed [13:0] dinReg2_0_re;  // sfix14
  input   signed [13:0] coefIn_0;  // sfix14_En18
  input   signed [47:0] addin;  // sfix48_En18
  input   dinRegVld;
  output  signed [13:0] dinDly2;  // sfix14
  output  signed [47:0] tapout;  // sfix48_En18


  reg signed [13:0] fTap_din_reg1;  // sfix14
  reg signed [13:0] fTap_coef_reg1;  // sfix14
  reg signed [13:0] fTap_din_reg2;  // sfix14
  reg signed [13:0] fTap_coef_reg2;  // sfix14
  reg signed [27:0] fTap_mult_reg;  // sfix28
  reg signed [47:0] fTap_addout_reg;  // sfix48
  reg signed [13:0] fTap_din_reg1_next;  // sfix14
  reg signed [13:0] fTap_coef_reg1_next;  // sfix14_En18
  reg signed [13:0] fTap_din_reg2_next;  // sfix14
  reg signed [13:0] fTap_coef_reg2_next;  // sfix14_En18
  reg signed [27:0] fTap_mult_reg_next;  // sfix28_En18
  reg signed [47:0] fTap_addout_reg_next;  // sfix48_En18
  reg signed [13:0] dinDly2_1;  // sfix14
  reg signed [47:0] tapout_1;  // sfix48_En18
  reg signed [47:0] fTap_add_cast;  // sfix48_En18

  initial begin
    fTap_din_reg1 = 14'sb00000000000000;
    fTap_coef_reg1 = 14'sb00000000000000;
    fTap_din_reg2 = 14'sb00000000000000;
    fTap_coef_reg2 = 14'sb00000000000000;
    fTap_mult_reg = 28'sb0000000000000000000000000000;
    fTap_addout_reg = 48'sh000000000000;
  end

  // FilterTapSystlicWvldIn
  always @(posedge clk)
    begin : fTap_process
      if (enb) begin
        fTap_din_reg1 <= fTap_din_reg1_next;
        fTap_coef_reg1 <= fTap_coef_reg1_next;
        fTap_din_reg2 <= fTap_din_reg2_next;
        fTap_coef_reg2 <= fTap_coef_reg2_next;
        fTap_mult_reg <= fTap_mult_reg_next;
        fTap_addout_reg <= fTap_addout_reg_next;
      end
    end

  always @(addin, coefIn_0, dinReg2_0_re, dinRegVld, fTap_addout_reg, fTap_coef_reg1,
       fTap_coef_reg2, fTap_din_reg1, fTap_din_reg2, fTap_mult_reg) begin
    fTap_add_cast = 48'sh000000000000;
    fTap_din_reg1_next = fTap_din_reg1;
    fTap_coef_reg1_next = fTap_coef_reg1;
    fTap_din_reg2_next = fTap_din_reg2;
    fTap_coef_reg2_next = fTap_coef_reg2;
    fTap_mult_reg_next = fTap_mult_reg;
    fTap_addout_reg_next = fTap_addout_reg;
    if (dinRegVld) begin
      fTap_add_cast = {{20{fTap_mult_reg[27]}}, fTap_mult_reg};
      fTap_addout_reg_next = fTap_add_cast + addin;
      fTap_mult_reg_next = fTap_din_reg2 * fTap_coef_reg2;
      fTap_din_reg2_next = fTap_din_reg1;
      fTap_coef_reg2_next = fTap_coef_reg1;
      fTap_din_reg1_next = dinReg2_0_re;
      fTap_coef_reg1_next = coefIn_0;
    end
    dinDly2_1 = fTap_din_reg2;
    tapout_1 = fTap_addout_reg;
  end



  assign dinDly2 = dinDly2_1;

  assign tapout = tapout_1;

endmodule  // rx_dma_test_src_FilterTapSystolicWvldin

