// -------------------------------------------------------------
// 
// File Name: /home/draco/git/adi_dma_testing/iq_dma_example/hdl_ip/hdlsrc/rx_dma_test/rx_dma_test_src_RADIX2FFT_bitNatural.v
// Created: 2025-08-21 13:52:00
// 
// Generated by MATLAB 24.1, HDL Coder 24.1, and Simulink 24.1
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: rx_dma_test_src_RADIX2FFT_bitNatural
// Source Path: rx_dma_test/LDCR_D/Channelizer_CH1/FFT/RADIX2FFT_bitNatural
// Hierarchy Level: 3
// Model version: 9.535
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module rx_dma_test_src_RADIX2FFT_bitNatural
          (clk,
           reset,
           enb,
           dout_6_1_re,
           dout_6_1_im,
           dout_6_1_vld,
           startOutS,
           endOutS);


  input   clk;
  input   reset;
  input   enb;
  input   signed [19:0] dout_6_1_re;  // sfix20_En5
  input   signed [19:0] dout_6_1_im;  // sfix20_En5
  input   dout_6_1_vld;
  output  startOutS;
  output  endOutS;


  reg [1:0] wrStateMachineBitNatural_wrState;  // ufix2
  reg [5:0] wrStateMachineBitNatural_wrAddrCnt;  // ufix6
  reg [1:0] wrStateMachineBitNatural_wrState_next;  // ufix2
  reg [5:0] wrStateMachineBitNatural_wrAddrCnt_next;  // ufix6
  reg  WrEnb;
  reg [5:0] wrAddr;  // ufix6
  reg [5:0] sampleIdx;  // ufix6
  reg [5:0] rdAddr;  // ufix6
  wire signed [19:0] memOut_im;  // sfix20_En5
  wire signed [19:0] memOut_re;  // sfix20_En5
  reg [1:0] rdStateMachineBitNatural_rdState;  // ufix2
  reg [5:0] rdStateMachineBitNatural_rdAddrCnt;  // ufix6
  reg  rdStateMachineBitNatural_doutVldReg1;
  reg  rdStateMachineBitNatural_doutVldReg2;
  reg signed [19:0] rdStateMachineBitNatural_doutReReg;  // sfix20
  reg signed [19:0] rdStateMachineBitNatural_doutImReg;  // sfix20
  reg  rdStateMachineBitNatural_startOutReg;
  reg  rdStateMachineBitNatural_endOutReg1;
  reg  rdStateMachineBitNatural_endOutReg2;
  reg [1:0] rdStateMachineBitNatural_rdState_next;  // ufix2
  reg [5:0] rdStateMachineBitNatural_rdAddrCnt_next;  // ufix6
  reg  rdStateMachineBitNatural_doutVldReg1_next;
  reg  rdStateMachineBitNatural_doutVldReg2_next;
  reg signed [19:0] rdStateMachineBitNatural_doutReReg_next;  // sfix20_En5
  reg signed [19:0] rdStateMachineBitNatural_doutImReg_next;  // sfix20_En5
  reg  rdStateMachineBitNatural_startOutReg_next;
  reg  rdStateMachineBitNatural_endOutReg1_next;
  reg  rdStateMachineBitNatural_endOutReg2_next;
  reg signed [19:0] dout_re1;  // sfix20_En5
  reg signed [19:0] dout_im1;  // sfix20_En5
  reg  dout_vld1;
  reg  startOutW;
  reg  endOutW;


  // wrStateMachineBitNatural
  always @(posedge clk)
    begin : wrStateMachineBitNatural_process
      if (reset == 1'b1) begin
        wrStateMachineBitNatural_wrState <= 2'b00;
        wrStateMachineBitNatural_wrAddrCnt <= 6'b000000;
      end
      else begin
        if (enb) begin
          wrStateMachineBitNatural_wrState <= wrStateMachineBitNatural_wrState_next;
          wrStateMachineBitNatural_wrAddrCnt <= wrStateMachineBitNatural_wrAddrCnt_next;
        end
      end
    end

  always @(dout_6_1_vld, wrStateMachineBitNatural_wrAddrCnt,
       wrStateMachineBitNatural_wrState) begin
    wrStateMachineBitNatural_wrState_next = wrStateMachineBitNatural_wrState;
    wrStateMachineBitNatural_wrAddrCnt_next = wrStateMachineBitNatural_wrAddrCnt;
    if (wrStateMachineBitNatural_wrState == 2'b10) begin
      wrAddr = {wrStateMachineBitNatural_wrAddrCnt[0], wrStateMachineBitNatural_wrAddrCnt[1], wrStateMachineBitNatural_wrAddrCnt[2], wrStateMachineBitNatural_wrAddrCnt[3], wrStateMachineBitNatural_wrAddrCnt[4], wrStateMachineBitNatural_wrAddrCnt[5]};
    end
    else begin
      wrAddr = wrStateMachineBitNatural_wrAddrCnt;
    end
    case ( wrStateMachineBitNatural_wrState)
      2'b00 :
        begin
          if (dout_6_1_vld) begin
            wrStateMachineBitNatural_wrState_next = 2'b01;
            wrStateMachineBitNatural_wrAddrCnt_next = 6'b000001;
          end
          else begin
            wrStateMachineBitNatural_wrState_next = 2'b00;
            wrStateMachineBitNatural_wrAddrCnt_next = 6'b000000;
          end
        end
      2'b01 :
        begin
          if (dout_6_1_vld) begin
            if (wrStateMachineBitNatural_wrAddrCnt == 6'b111111) begin
              wrStateMachineBitNatural_wrAddrCnt_next = 6'b000000;
              wrStateMachineBitNatural_wrState_next = 2'b10;
            end
            else begin
              wrStateMachineBitNatural_wrAddrCnt_next = wrStateMachineBitNatural_wrAddrCnt + 6'b000001;
              wrStateMachineBitNatural_wrState_next = 2'b01;
            end
          end
        end
      2'b10 :
        begin
          if (dout_6_1_vld) begin
            if (wrStateMachineBitNatural_wrAddrCnt == 6'b111111) begin
              wrStateMachineBitNatural_wrAddrCnt_next = 6'b000000;
              wrStateMachineBitNatural_wrState_next = 2'b01;
            end
            else begin
              wrStateMachineBitNatural_wrAddrCnt_next = wrStateMachineBitNatural_wrAddrCnt + 6'b000001;
              wrStateMachineBitNatural_wrState_next = 2'b10;
            end
          end
        end
      default :
        begin
          wrStateMachineBitNatural_wrState_next = 2'b00;
          wrStateMachineBitNatural_wrAddrCnt_next = 6'b000000;
        end
    endcase
    WrEnb = dout_6_1_vld;
    sampleIdx = wrStateMachineBitNatural_wrAddrCnt;
  end



  rx_dma_test_src_SimpleDualPortRAM_generic #(.AddrWidth(6),
                                              .DataWidth(20)
                                              )
                                            u_dataMEM_im_1 (.clk(clk),
                                                            .enb(enb),
                                                            .wr_din(dout_6_1_im),
                                                            .wr_addr(wrAddr),
                                                            .wr_en(WrEnb),
                                                            .rd_addr(rdAddr),
                                                            .dout(memOut_im)
                                                            );

  rx_dma_test_src_SimpleDualPortRAM_generic #(.AddrWidth(6),
                                              .DataWidth(20)
                                              )
                                            u_dataMEM_re_1 (.clk(clk),
                                                            .enb(enb),
                                                            .wr_din(dout_6_1_re),
                                                            .wr_addr(wrAddr),
                                                            .wr_en(WrEnb),
                                                            .rd_addr(rdAddr),
                                                            .dout(memOut_re)
                                                            );

  // rdStateMachineBitNatural
  always @(posedge clk)
    begin : rdStateMachineBitNatural_process
      if (reset == 1'b1) begin
        rdStateMachineBitNatural_rdState <= 2'b00;
        rdStateMachineBitNatural_rdAddrCnt <= 6'b000000;
        rdStateMachineBitNatural_doutVldReg1 <= 1'b0;
        rdStateMachineBitNatural_doutVldReg2 <= 1'b0;
        rdStateMachineBitNatural_doutReReg <= 20'sb00000000000000000000;
        rdStateMachineBitNatural_doutImReg <= 20'sb00000000000000000000;
        rdStateMachineBitNatural_startOutReg <= 1'b0;
        rdStateMachineBitNatural_endOutReg1 <= 1'b0;
        rdStateMachineBitNatural_endOutReg2 <= 1'b0;
      end
      else begin
        if (enb) begin
          rdStateMachineBitNatural_rdState <= rdStateMachineBitNatural_rdState_next;
          rdStateMachineBitNatural_rdAddrCnt <= rdStateMachineBitNatural_rdAddrCnt_next;
          rdStateMachineBitNatural_doutVldReg1 <= rdStateMachineBitNatural_doutVldReg1_next;
          rdStateMachineBitNatural_doutVldReg2 <= rdStateMachineBitNatural_doutVldReg2_next;
          rdStateMachineBitNatural_doutReReg <= rdStateMachineBitNatural_doutReReg_next;
          rdStateMachineBitNatural_doutImReg <= rdStateMachineBitNatural_doutImReg_next;
          rdStateMachineBitNatural_startOutReg <= rdStateMachineBitNatural_startOutReg_next;
          rdStateMachineBitNatural_endOutReg1 <= rdStateMachineBitNatural_endOutReg1_next;
          rdStateMachineBitNatural_endOutReg2 <= rdStateMachineBitNatural_endOutReg2_next;
        end
      end
    end

  always @(memOut_im, memOut_re, rdStateMachineBitNatural_doutImReg,
       rdStateMachineBitNatural_doutReReg, rdStateMachineBitNatural_doutVldReg1,
       rdStateMachineBitNatural_doutVldReg2,
       rdStateMachineBitNatural_endOutReg1, rdStateMachineBitNatural_endOutReg2,
       rdStateMachineBitNatural_rdAddrCnt, rdStateMachineBitNatural_rdState,
       rdStateMachineBitNatural_startOutReg, sampleIdx) begin
    rdStateMachineBitNatural_doutReReg_next = rdStateMachineBitNatural_doutReReg;
    rdStateMachineBitNatural_doutImReg_next = rdStateMachineBitNatural_doutImReg;
    if (rdStateMachineBitNatural_rdState == 2'b01) begin
      rdAddr = {rdStateMachineBitNatural_rdAddrCnt[0], rdStateMachineBitNatural_rdAddrCnt[1], rdStateMachineBitNatural_rdAddrCnt[2], rdStateMachineBitNatural_rdAddrCnt[3], rdStateMachineBitNatural_rdAddrCnt[4], rdStateMachineBitNatural_rdAddrCnt[5]};
    end
    else begin
      rdAddr = rdStateMachineBitNatural_rdAddrCnt;
    end
    rdStateMachineBitNatural_endOutReg2_next = rdStateMachineBitNatural_endOutReg1;
    rdStateMachineBitNatural_startOutReg_next = rdStateMachineBitNatural_rdAddrCnt == 6'b000001;
    case ( rdStateMachineBitNatural_rdState)
      2'b00 :
        begin
          rdStateMachineBitNatural_doutVldReg1_next = 1'b0;
          if (sampleIdx >= 6'b110101) begin
            rdStateMachineBitNatural_rdAddrCnt_next = 6'b000001;
            rdStateMachineBitNatural_doutVldReg1_next = 1'b1;
            rdStateMachineBitNatural_rdState_next = 2'b01;
            rdStateMachineBitNatural_endOutReg1_next = 1'b0;
          end
          else begin
            rdStateMachineBitNatural_rdAddrCnt_next = 6'b000000;
            rdStateMachineBitNatural_rdState_next = 2'b00;
            rdStateMachineBitNatural_endOutReg1_next = 1'b0;
          end
        end
      2'b01 :
        begin
          rdStateMachineBitNatural_doutVldReg1_next = 1'b1;
          if (rdStateMachineBitNatural_rdAddrCnt == 6'b111111) begin
            rdStateMachineBitNatural_rdAddrCnt_next = 6'b000000;
            rdStateMachineBitNatural_rdState_next = 2'b10;
            rdStateMachineBitNatural_endOutReg1_next = 1'b1;
          end
          else begin
            rdStateMachineBitNatural_rdAddrCnt_next = rdStateMachineBitNatural_rdAddrCnt + 6'b000001;
            rdStateMachineBitNatural_rdState_next = 2'b01;
            rdStateMachineBitNatural_endOutReg1_next = 1'b0;
          end
        end
      2'b10 :
        begin
          rdStateMachineBitNatural_doutVldReg1_next = 1'b0;
          if (sampleIdx >= 6'b110101) begin
            rdStateMachineBitNatural_rdAddrCnt_next = 6'b000001;
            rdStateMachineBitNatural_doutVldReg1_next = 1'b1;
            rdStateMachineBitNatural_rdState_next = 2'b11;
            rdStateMachineBitNatural_endOutReg1_next = 1'b0;
          end
          else begin
            rdStateMachineBitNatural_rdAddrCnt_next = 6'b000000;
            rdStateMachineBitNatural_rdState_next = 2'b10;
            rdStateMachineBitNatural_endOutReg1_next = 1'b0;
          end
        end
      2'b11 :
        begin
          rdStateMachineBitNatural_doutVldReg1_next = 1'b1;
          if (rdStateMachineBitNatural_rdAddrCnt == 6'b111111) begin
            rdStateMachineBitNatural_rdAddrCnt_next = 6'b000000;
            rdStateMachineBitNatural_rdState_next = 2'b00;
            rdStateMachineBitNatural_endOutReg1_next = 1'b1;
          end
          else begin
            rdStateMachineBitNatural_rdAddrCnt_next = rdStateMachineBitNatural_rdAddrCnt + 6'b000001;
            rdStateMachineBitNatural_rdState_next = 2'b11;
            rdStateMachineBitNatural_endOutReg1_next = 1'b0;
          end
        end
      default :
        begin
          rdStateMachineBitNatural_rdState_next = 2'b00;
          rdStateMachineBitNatural_rdAddrCnt_next = 6'b000000;
          rdStateMachineBitNatural_doutVldReg1_next = 1'b0;
          rdStateMachineBitNatural_endOutReg1_next = 1'b0;
        end
    endcase
    if (rdStateMachineBitNatural_doutVldReg1) begin
      rdStateMachineBitNatural_doutReReg_next = memOut_re;
      rdStateMachineBitNatural_doutImReg_next = memOut_im;
    end
    rdStateMachineBitNatural_doutVldReg2_next = rdStateMachineBitNatural_doutVldReg1;
    dout_re1 = rdStateMachineBitNatural_doutReReg;
    dout_im1 = rdStateMachineBitNatural_doutImReg;
    dout_vld1 = rdStateMachineBitNatural_doutVldReg2;
    startOutW = rdStateMachineBitNatural_startOutReg;
    endOutW = rdStateMachineBitNatural_endOutReg2;
  end



  assign startOutS = startOutW;

  assign endOutS = endOutW;

endmodule  // rx_dma_test_src_RADIX2FFT_bitNatural

