// -------------------------------------------------------------
// 
// File Name: /home/draco/git/adi_dma_testing/iq_dma_example/hdl_ip/hdlsrc/rx_dma_test/rx_dma_test_src_FilterCoef.v
// Created: 2025-08-21 13:52:00
// 
// Generated by MATLAB 24.1, HDL Coder 24.1, and Simulink 24.1
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: rx_dma_test_src_FilterCoef
// Source Path: rx_dma_test/LDCR_D/Channelizer_CH1/FilterBank/FilterCoef
// Hierarchy Level: 3
// Model version: 9.535
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module rx_dma_test_src_FilterCoef
          (clk,
           reset,
           enb,
           validIn,
           syncReset,
           CoefOut_0,
           CoefOut_1,
           CoefOut_2,
           CoefOut_3,
           CoefOut_4,
           CoefOut_5,
           CoefOut_6,
           CoefOut_7,
           CoefOut_8,
           CoefOut_9,
           CoefOut_10,
           CoefOut_11);


  input   clk;
  input   reset;
  input   enb;
  input   validIn;
  input   syncReset;
  output  signed [13:0] CoefOut_0;  // sfix14_En18
  output  signed [13:0] CoefOut_1;  // sfix14_En18
  output  signed [13:0] CoefOut_2;  // sfix14_En18
  output  signed [13:0] CoefOut_3;  // sfix14_En18
  output  signed [13:0] CoefOut_4;  // sfix14_En18
  output  signed [13:0] CoefOut_5;  // sfix14_En18
  output  signed [13:0] CoefOut_6;  // sfix14_En18
  output  signed [13:0] CoefOut_7;  // sfix14_En18
  output  signed [13:0] CoefOut_8;  // sfix14_En18
  output  signed [13:0] CoefOut_9;  // sfix14_En18
  output  signed [13:0] CoefOut_10;  // sfix14_En18
  output  signed [13:0] CoefOut_11;  // sfix14_En18


  reg [5:0] CoefAddr_cnt;  // ufix6
  reg  CoefAddr_state;  // ufix1
  reg [5:0] CoefAddr_cnt_next;  // ufix6
  reg  CoefAddr_state_next;  // ufix1
  reg [5:0] CoefAddr_1;  // ufix6
  wire signed [13:0] Coef_table_table_data [0:63];  // sfix14_En18 [64]
  wire signed [13:0] CoefData;  // sfix14_En18
  reg signed [13:0] CoefReg;  // sfix14_En18
  wire signed [13:0] Coef_table_table_data_1 [0:63];  // sfix14_En18 [64]
  wire signed [13:0] CoefData_1;  // sfix14_En18
  reg signed [13:0] CoefReg_1;  // sfix14_En18
  wire signed [13:0] Coef_table_table_data_2 [0:63];  // sfix14_En18 [64]
  wire signed [13:0] CoefData_2;  // sfix14_En18
  reg signed [13:0] CoefReg_2;  // sfix14_En18
  wire signed [13:0] Coef_table_table_data_3 [0:63];  // sfix14_En18 [64]
  wire signed [13:0] CoefData_3;  // sfix14_En18
  reg signed [13:0] CoefReg_3;  // sfix14_En18
  wire signed [13:0] Coef_table_table_data_4 [0:63];  // sfix14_En18 [64]
  wire signed [13:0] CoefData_4;  // sfix14_En18
  reg signed [13:0] CoefReg_4;  // sfix14_En18
  wire signed [13:0] Coef_table_table_data_5 [0:63];  // sfix14_En18 [64]
  wire signed [13:0] CoefData_5;  // sfix14_En18
  reg signed [13:0] CoefReg_5;  // sfix14_En18
  wire signed [13:0] Coef_table_table_data_6 [0:63];  // sfix14_En18 [64]
  wire signed [13:0] CoefData_6;  // sfix14_En18
  reg signed [13:0] CoefReg_6;  // sfix14_En18
  wire signed [13:0] Coef_table_table_data_7 [0:63];  // sfix14_En18 [64]
  wire signed [13:0] CoefData_7;  // sfix14_En18
  reg signed [13:0] CoefReg_7;  // sfix14_En18
  wire signed [13:0] Coef_table_table_data_8 [0:63];  // sfix14_En18 [64]
  wire signed [13:0] CoefData_8;  // sfix14_En18
  reg signed [13:0] CoefReg_8;  // sfix14_En18
  wire signed [13:0] Coef_table_table_data_9 [0:63];  // sfix14_En18 [64]
  wire signed [13:0] CoefData_9;  // sfix14_En18
  reg signed [13:0] CoefReg_9;  // sfix14_En18
  wire signed [13:0] Coef_table_table_data_10 [0:63];  // sfix14_En18 [64]
  wire signed [13:0] CoefData_10;  // sfix14_En18
  reg signed [13:0] CoefReg_10;  // sfix14_En18
  wire signed [13:0] Coef_table_table_data_11 [0:63];  // sfix14_En18 [64]
  wire signed [13:0] CoefData_11;  // sfix14_En18
  reg signed [13:0] CoefReg_11;  // sfix14_En18


  // CoefAddr
  always @(posedge clk)
    begin : CoefAddr_process
      if (reset == 1'b1) begin
        CoefAddr_cnt <= 6'b000000;
        CoefAddr_state <= 1'b0;
      end
      else begin
        if (enb) begin
          if (syncReset == 1'b1) begin
            CoefAddr_cnt <= 6'b000000;
            CoefAddr_state <= 1'b0;
          end
          else begin
            CoefAddr_cnt <= CoefAddr_cnt_next;
            CoefAddr_state <= CoefAddr_state_next;
          end
        end
      end
    end

  always @(CoefAddr_cnt, CoefAddr_state, validIn) begin
    CoefAddr_cnt_next = CoefAddr_cnt;
    CoefAddr_1 = CoefAddr_cnt;
    case ( CoefAddr_state)
      1'b0 :
        begin
          CoefAddr_state_next = 1'b0;
          CoefAddr_cnt_next = 6'b000000;
          if (validIn) begin
            CoefAddr_state_next = 1'b1;
          end
        end
      1'b1 :
        begin
          CoefAddr_state_next = 1'b1;
          if (validIn) begin
            if (CoefAddr_cnt == 6'b111111) begin
              CoefAddr_cnt_next = 6'b000000;
            end
            else begin
              CoefAddr_cnt_next = CoefAddr_cnt + 6'b000001;
            end
          end
        end
      default :
        begin
          CoefAddr_cnt_next = 6'b000000;
          CoefAddr_state_next = 1'b0;
        end
    endcase
  end



  // CoefTable_1
  assign Coef_table_table_data[0] = 14'sb11111111111111;
  assign Coef_table_table_data[1] = 14'sb11111111111111;
  assign Coef_table_table_data[2] = 14'sb11111111111111;
  assign Coef_table_table_data[3] = 14'sb11111111111110;
  assign Coef_table_table_data[4] = 14'sb11111111111110;
  assign Coef_table_table_data[5] = 14'sb11111111111101;
  assign Coef_table_table_data[6] = 14'sb11111111111101;
  assign Coef_table_table_data[7] = 14'sb11111111111101;
  assign Coef_table_table_data[8] = 14'sb11111111111101;
  assign Coef_table_table_data[9] = 14'sb11111111111100;
  assign Coef_table_table_data[10] = 14'sb11111111111100;
  assign Coef_table_table_data[11] = 14'sb11111111111100;
  assign Coef_table_table_data[12] = 14'sb11111111111100;
  assign Coef_table_table_data[13] = 14'sb11111111111100;
  assign Coef_table_table_data[14] = 14'sb11111111111100;
  assign Coef_table_table_data[15] = 14'sb11111111111100;
  assign Coef_table_table_data[16] = 14'sb11111111111011;
  assign Coef_table_table_data[17] = 14'sb11111111111011;
  assign Coef_table_table_data[18] = 14'sb11111111111011;
  assign Coef_table_table_data[19] = 14'sb11111111111011;
  assign Coef_table_table_data[20] = 14'sb11111111111011;
  assign Coef_table_table_data[21] = 14'sb11111111111011;
  assign Coef_table_table_data[22] = 14'sb11111111111100;
  assign Coef_table_table_data[23] = 14'sb11111111111100;
  assign Coef_table_table_data[24] = 14'sb11111111111100;
  assign Coef_table_table_data[25] = 14'sb11111111111100;
  assign Coef_table_table_data[26] = 14'sb11111111111100;
  assign Coef_table_table_data[27] = 14'sb11111111111100;
  assign Coef_table_table_data[28] = 14'sb11111111111100;
  assign Coef_table_table_data[29] = 14'sb11111111111100;
  assign Coef_table_table_data[30] = 14'sb11111111111100;
  assign Coef_table_table_data[31] = 14'sb11111111111101;
  assign Coef_table_table_data[32] = 14'sb11111111111101;
  assign Coef_table_table_data[33] = 14'sb11111111111101;
  assign Coef_table_table_data[34] = 14'sb11111111111101;
  assign Coef_table_table_data[35] = 14'sb11111111111101;
  assign Coef_table_table_data[36] = 14'sb11111111111101;
  assign Coef_table_table_data[37] = 14'sb11111111111101;
  assign Coef_table_table_data[38] = 14'sb11111111111110;
  assign Coef_table_table_data[39] = 14'sb11111111111110;
  assign Coef_table_table_data[40] = 14'sb11111111111110;
  assign Coef_table_table_data[41] = 14'sb11111111111110;
  assign Coef_table_table_data[42] = 14'sb11111111111110;
  assign Coef_table_table_data[43] = 14'sb11111111111110;
  assign Coef_table_table_data[44] = 14'sb11111111111110;
  assign Coef_table_table_data[45] = 14'sb11111111111111;
  assign Coef_table_table_data[46] = 14'sb11111111111111;
  assign Coef_table_table_data[47] = 14'sb11111111111111;
  assign Coef_table_table_data[48] = 14'sb11111111111111;
  assign Coef_table_table_data[49] = 14'sb11111111111111;
  assign Coef_table_table_data[50] = 14'sb11111111111111;
  assign Coef_table_table_data[51] = 14'sb11111111111111;
  assign Coef_table_table_data[52] = 14'sb11111111111111;
  assign Coef_table_table_data[53] = 14'sb11111111111111;
  assign Coef_table_table_data[54] = 14'sb00000000000000;
  assign Coef_table_table_data[55] = 14'sb00000000000000;
  assign Coef_table_table_data[56] = 14'sb00000000000000;
  assign Coef_table_table_data[57] = 14'sb00000000000000;
  assign Coef_table_table_data[58] = 14'sb00000000000000;
  assign Coef_table_table_data[59] = 14'sb00000000000000;
  assign Coef_table_table_data[60] = 14'sb00000000000000;
  assign Coef_table_table_data[61] = 14'sb00000000000000;
  assign Coef_table_table_data[62] = 14'sb00000000000000;
  assign Coef_table_table_data[63] = 14'sb00000000000000;
  assign CoefData = Coef_table_table_data[CoefAddr_1];



  always @(posedge clk)
    begin : FilterCoef_process
      if (reset == 1'b1) begin
        CoefReg <= 14'sb00000000000000;
      end
      else begin
        if (enb) begin
          CoefReg <= CoefData;
        end
      end
    end



  assign CoefOut_0 = CoefReg;

  // CoefTable_2
  assign Coef_table_table_data_1[0] = 14'sb00000000000010;
  assign Coef_table_table_data_1[1] = 14'sb00000000000101;
  assign Coef_table_table_data_1[2] = 14'sb00000000000111;
  assign Coef_table_table_data_1[3] = 14'sb00000000001001;
  assign Coef_table_table_data_1[4] = 14'sb00000000001011;
  assign Coef_table_table_data_1[5] = 14'sb00000000001101;
  assign Coef_table_table_data_1[6] = 14'sb00000000001111;
  assign Coef_table_table_data_1[7] = 14'sb00000000010001;
  assign Coef_table_table_data_1[8] = 14'sb00000000010010;
  assign Coef_table_table_data_1[9] = 14'sb00000000010100;
  assign Coef_table_table_data_1[10] = 14'sb00000000010101;
  assign Coef_table_table_data_1[11] = 14'sb00000000010110;
  assign Coef_table_table_data_1[12] = 14'sb00000000010111;
  assign Coef_table_table_data_1[13] = 14'sb00000000011000;
  assign Coef_table_table_data_1[14] = 14'sb00000000011001;
  assign Coef_table_table_data_1[15] = 14'sb00000000011010;
  assign Coef_table_table_data_1[16] = 14'sb00000000011010;
  assign Coef_table_table_data_1[17] = 14'sb00000000011011;
  assign Coef_table_table_data_1[18] = 14'sb00000000011011;
  assign Coef_table_table_data_1[19] = 14'sb00000000011100;
  assign Coef_table_table_data_1[20] = 14'sb00000000011100;
  assign Coef_table_table_data_1[21] = 14'sb00000000011100;
  assign Coef_table_table_data_1[22] = 14'sb00000000011100;
  assign Coef_table_table_data_1[23] = 14'sb00000000011100;
  assign Coef_table_table_data_1[24] = 14'sb00000000011100;
  assign Coef_table_table_data_1[25] = 14'sb00000000011100;
  assign Coef_table_table_data_1[26] = 14'sb00000000011100;
  assign Coef_table_table_data_1[27] = 14'sb00000000011011;
  assign Coef_table_table_data_1[28] = 14'sb00000000011011;
  assign Coef_table_table_data_1[29] = 14'sb00000000011010;
  assign Coef_table_table_data_1[30] = 14'sb00000000011010;
  assign Coef_table_table_data_1[31] = 14'sb00000000011001;
  assign Coef_table_table_data_1[32] = 14'sb00000000011001;
  assign Coef_table_table_data_1[33] = 14'sb00000000011000;
  assign Coef_table_table_data_1[34] = 14'sb00000000010111;
  assign Coef_table_table_data_1[35] = 14'sb00000000010110;
  assign Coef_table_table_data_1[36] = 14'sb00000000010110;
  assign Coef_table_table_data_1[37] = 14'sb00000000010101;
  assign Coef_table_table_data_1[38] = 14'sb00000000010100;
  assign Coef_table_table_data_1[39] = 14'sb00000000010011;
  assign Coef_table_table_data_1[40] = 14'sb00000000010010;
  assign Coef_table_table_data_1[41] = 14'sb00000000010001;
  assign Coef_table_table_data_1[42] = 14'sb00000000010000;
  assign Coef_table_table_data_1[43] = 14'sb00000000001111;
  assign Coef_table_table_data_1[44] = 14'sb00000000001111;
  assign Coef_table_table_data_1[45] = 14'sb00000000001110;
  assign Coef_table_table_data_1[46] = 14'sb00000000001101;
  assign Coef_table_table_data_1[47] = 14'sb00000000001100;
  assign Coef_table_table_data_1[48] = 14'sb00000000001011;
  assign Coef_table_table_data_1[49] = 14'sb00000000001010;
  assign Coef_table_table_data_1[50] = 14'sb00000000001001;
  assign Coef_table_table_data_1[51] = 14'sb00000000001000;
  assign Coef_table_table_data_1[52] = 14'sb00000000001000;
  assign Coef_table_table_data_1[53] = 14'sb00000000000111;
  assign Coef_table_table_data_1[54] = 14'sb00000000000110;
  assign Coef_table_table_data_1[55] = 14'sb00000000000101;
  assign Coef_table_table_data_1[56] = 14'sb00000000000100;
  assign Coef_table_table_data_1[57] = 14'sb00000000000100;
  assign Coef_table_table_data_1[58] = 14'sb00000000000011;
  assign Coef_table_table_data_1[59] = 14'sb00000000000010;
  assign Coef_table_table_data_1[60] = 14'sb00000000000010;
  assign Coef_table_table_data_1[61] = 14'sb00000000000001;
  assign Coef_table_table_data_1[62] = 14'sb00000000000001;
  assign Coef_table_table_data_1[63] = 14'sb00000000000000;
  assign CoefData_1 = Coef_table_table_data_1[CoefAddr_1];



  always @(posedge clk)
    begin : FilterCoef_1_process
      if (reset == 1'b1) begin
        CoefReg_1 <= 14'sb00000000000000;
      end
      else begin
        if (enb) begin
          CoefReg_1 <= CoefData_1;
        end
      end
    end



  assign CoefOut_1 = CoefReg_1;

  // CoefTable_3
  assign Coef_table_table_data_2[0] = 14'sb11111111111000;
  assign Coef_table_table_data_2[1] = 14'sb11111111110000;
  assign Coef_table_table_data_2[2] = 14'sb11111111101001;
  assign Coef_table_table_data_2[3] = 14'sb11111111100010;
  assign Coef_table_table_data_2[4] = 14'sb11111111011011;
  assign Coef_table_table_data_2[5] = 14'sb11111111010101;
  assign Coef_table_table_data_2[6] = 14'sb11111111001111;
  assign Coef_table_table_data_2[7] = 14'sb11111111001001;
  assign Coef_table_table_data_2[8] = 14'sb11111111000100;
  assign Coef_table_table_data_2[9] = 14'sb11111110111111;
  assign Coef_table_table_data_2[10] = 14'sb11111110111010;
  assign Coef_table_table_data_2[11] = 14'sb11111110110101;
  assign Coef_table_table_data_2[12] = 14'sb11111110110001;
  assign Coef_table_table_data_2[13] = 14'sb11111110101110;
  assign Coef_table_table_data_2[14] = 14'sb11111110101010;
  assign Coef_table_table_data_2[15] = 14'sb11111110100111;
  assign Coef_table_table_data_2[16] = 14'sb11111110100101;
  assign Coef_table_table_data_2[17] = 14'sb11111110100010;
  assign Coef_table_table_data_2[18] = 14'sb11111110100000;
  assign Coef_table_table_data_2[19] = 14'sb11111110011111;
  assign Coef_table_table_data_2[20] = 14'sb11111110011101;
  assign Coef_table_table_data_2[21] = 14'sb11111110011100;
  assign Coef_table_table_data_2[22] = 14'sb11111110011011;
  assign Coef_table_table_data_2[23] = 14'sb11111110011011;
  assign Coef_table_table_data_2[24] = 14'sb11111110011011;
  assign Coef_table_table_data_2[25] = 14'sb11111110011011;
  assign Coef_table_table_data_2[26] = 14'sb11111110011011;
  assign Coef_table_table_data_2[27] = 14'sb11111110011100;
  assign Coef_table_table_data_2[28] = 14'sb11111110011101;
  assign Coef_table_table_data_2[29] = 14'sb11111110011110;
  assign Coef_table_table_data_2[30] = 14'sb11111110011111;
  assign Coef_table_table_data_2[31] = 14'sb11111110100001;
  assign Coef_table_table_data_2[32] = 14'sb11111110100011;
  assign Coef_table_table_data_2[33] = 14'sb11111110100101;
  assign Coef_table_table_data_2[34] = 14'sb11111110100111;
  assign Coef_table_table_data_2[35] = 14'sb11111110101001;
  assign Coef_table_table_data_2[36] = 14'sb11111110101100;
  assign Coef_table_table_data_2[37] = 14'sb11111110101111;
  assign Coef_table_table_data_2[38] = 14'sb11111110110001;
  assign Coef_table_table_data_2[39] = 14'sb11111110110100;
  assign Coef_table_table_data_2[40] = 14'sb11111110110111;
  assign Coef_table_table_data_2[41] = 14'sb11111110111010;
  assign Coef_table_table_data_2[42] = 14'sb11111110111101;
  assign Coef_table_table_data_2[43] = 14'sb11111111000001;
  assign Coef_table_table_data_2[44] = 14'sb11111111000100;
  assign Coef_table_table_data_2[45] = 14'sb11111111000111;
  assign Coef_table_table_data_2[46] = 14'sb11111111001011;
  assign Coef_table_table_data_2[47] = 14'sb11111111001110;
  assign Coef_table_table_data_2[48] = 14'sb11111111010001;
  assign Coef_table_table_data_2[49] = 14'sb11111111010101;
  assign Coef_table_table_data_2[50] = 14'sb11111111011000;
  assign Coef_table_table_data_2[51] = 14'sb11111111011100;
  assign Coef_table_table_data_2[52] = 14'sb11111111011111;
  assign Coef_table_table_data_2[53] = 14'sb11111111100010;
  assign Coef_table_table_data_2[54] = 14'sb11111111100110;
  assign Coef_table_table_data_2[55] = 14'sb11111111101001;
  assign Coef_table_table_data_2[56] = 14'sb11111111101100;
  assign Coef_table_table_data_2[57] = 14'sb11111111101111;
  assign Coef_table_table_data_2[58] = 14'sb11111111110010;
  assign Coef_table_table_data_2[59] = 14'sb11111111110101;
  assign Coef_table_table_data_2[60] = 14'sb11111111111000;
  assign Coef_table_table_data_2[61] = 14'sb11111111111011;
  assign Coef_table_table_data_2[62] = 14'sb11111111111101;
  assign Coef_table_table_data_2[63] = 14'sb00000000000000;
  assign CoefData_2 = Coef_table_table_data_2[CoefAddr_1];



  always @(posedge clk)
    begin : FilterCoef_2_process
      if (reset == 1'b1) begin
        CoefReg_2 <= 14'sb00000000000000;
      end
      else begin
        if (enb) begin
          CoefReg_2 <= CoefData_2;
        end
      end
    end



  assign CoefOut_2 = CoefReg_2;

  // CoefTable_4
  assign Coef_table_table_data_3[0] = 14'sb00000000010101;
  assign Coef_table_table_data_3[1] = 14'sb00000000101001;
  assign Coef_table_table_data_3[2] = 14'sb00000000111100;
  assign Coef_table_table_data_3[3] = 14'sb00000001001111;
  assign Coef_table_table_data_3[4] = 14'sb00000001100001;
  assign Coef_table_table_data_3[5] = 14'sb00000001110010;
  assign Coef_table_table_data_3[6] = 14'sb00000010000011;
  assign Coef_table_table_data_3[7] = 14'sb00000010010010;
  assign Coef_table_table_data_3[8] = 14'sb00000010100001;
  assign Coef_table_table_data_3[9] = 14'sb00000010101111;
  assign Coef_table_table_data_3[10] = 14'sb00000010111100;
  assign Coef_table_table_data_3[11] = 14'sb00000011001000;
  assign Coef_table_table_data_3[12] = 14'sb00000011010011;
  assign Coef_table_table_data_3[13] = 14'sb00000011011110;
  assign Coef_table_table_data_3[14] = 14'sb00000011101000;
  assign Coef_table_table_data_3[15] = 14'sb00000011110000;
  assign Coef_table_table_data_3[16] = 14'sb00000011111000;
  assign Coef_table_table_data_3[17] = 14'sb00000011111111;
  assign Coef_table_table_data_3[18] = 14'sb00000100000101;
  assign Coef_table_table_data_3[19] = 14'sb00000100001010;
  assign Coef_table_table_data_3[20] = 14'sb00000100001111;
  assign Coef_table_table_data_3[21] = 14'sb00000100010010;
  assign Coef_table_table_data_3[22] = 14'sb00000100010101;
  assign Coef_table_table_data_3[23] = 14'sb00000100010111;
  assign Coef_table_table_data_3[24] = 14'sb00000100011000;
  assign Coef_table_table_data_3[25] = 14'sb00000100011001;
  assign Coef_table_table_data_3[26] = 14'sb00000100011000;
  assign Coef_table_table_data_3[27] = 14'sb00000100010111;
  assign Coef_table_table_data_3[28] = 14'sb00000100010101;
  assign Coef_table_table_data_3[29] = 14'sb00000100010011;
  assign Coef_table_table_data_3[30] = 14'sb00000100010000;
  assign Coef_table_table_data_3[31] = 14'sb00000100001100;
  assign Coef_table_table_data_3[32] = 14'sb00000100001000;
  assign Coef_table_table_data_3[33] = 14'sb00000100000011;
  assign Coef_table_table_data_3[34] = 14'sb00000011111110;
  assign Coef_table_table_data_3[35] = 14'sb00000011111000;
  assign Coef_table_table_data_3[36] = 14'sb00000011110001;
  assign Coef_table_table_data_3[37] = 14'sb00000011101011;
  assign Coef_table_table_data_3[38] = 14'sb00000011100011;
  assign Coef_table_table_data_3[39] = 14'sb00000011011100;
  assign Coef_table_table_data_3[40] = 14'sb00000011010100;
  assign Coef_table_table_data_3[41] = 14'sb00000011001011;
  assign Coef_table_table_data_3[42] = 14'sb00000011000011;
  assign Coef_table_table_data_3[43] = 14'sb00000010111010;
  assign Coef_table_table_data_3[44] = 14'sb00000010110001;
  assign Coef_table_table_data_3[45] = 14'sb00000010101000;
  assign Coef_table_table_data_3[46] = 14'sb00000010011110;
  assign Coef_table_table_data_3[47] = 14'sb00000010010101;
  assign Coef_table_table_data_3[48] = 14'sb00000010001011;
  assign Coef_table_table_data_3[49] = 14'sb00000010000001;
  assign Coef_table_table_data_3[50] = 14'sb00000001111000;
  assign Coef_table_table_data_3[51] = 14'sb00000001101110;
  assign Coef_table_table_data_3[52] = 14'sb00000001100100;
  assign Coef_table_table_data_3[53] = 14'sb00000001011010;
  assign Coef_table_table_data_3[54] = 14'sb00000001010001;
  assign Coef_table_table_data_3[55] = 14'sb00000001000111;
  assign Coef_table_table_data_3[56] = 14'sb00000000111110;
  assign Coef_table_table_data_3[57] = 14'sb00000000110100;
  assign Coef_table_table_data_3[58] = 14'sb00000000101011;
  assign Coef_table_table_data_3[59] = 14'sb00000000100010;
  assign Coef_table_table_data_3[60] = 14'sb00000000011001;
  assign Coef_table_table_data_3[61] = 14'sb00000000010001;
  assign Coef_table_table_data_3[62] = 14'sb00000000001000;
  assign Coef_table_table_data_3[63] = 14'sb00000000000000;
  assign CoefData_3 = Coef_table_table_data_3[CoefAddr_1];



  always @(posedge clk)
    begin : FilterCoef_3_process
      if (reset == 1'b1) begin
        CoefReg_3 <= 14'sb00000000000000;
      end
      else begin
        if (enb) begin
          CoefReg_3 <= CoefData_3;
        end
      end
    end



  assign CoefOut_3 = CoefReg_3;

  // CoefTable_5
  assign Coef_table_table_data_4[0] = 14'sb11111111000111;
  assign Coef_table_table_data_4[1] = 14'sb11111110010001;
  assign Coef_table_table_data_4[2] = 14'sb11111101011101;
  assign Coef_table_table_data_4[3] = 14'sb11111100101011;
  assign Coef_table_table_data_4[4] = 14'sb11111011111011;
  assign Coef_table_table_data_4[5] = 14'sb11111011001110;
  assign Coef_table_table_data_4[6] = 14'sb11111010100011;
  assign Coef_table_table_data_4[7] = 14'sb11111001111011;
  assign Coef_table_table_data_4[8] = 14'sb11111001010100;
  assign Coef_table_table_data_4[9] = 14'sb11111000110001;
  assign Coef_table_table_data_4[10] = 14'sb11111000001111;
  assign Coef_table_table_data_4[11] = 14'sb11110111110000;
  assign Coef_table_table_data_4[12] = 14'sb11110111010100;
  assign Coef_table_table_data_4[13] = 14'sb11110110111010;
  assign Coef_table_table_data_4[14] = 14'sb11110110100010;
  assign Coef_table_table_data_4[15] = 14'sb11110110001100;
  assign Coef_table_table_data_4[16] = 14'sb11110101111001;
  assign Coef_table_table_data_4[17] = 14'sb11110101101000;
  assign Coef_table_table_data_4[18] = 14'sb11110101011001;
  assign Coef_table_table_data_4[19] = 14'sb11110101001100;
  assign Coef_table_table_data_4[20] = 14'sb11110101000010;
  assign Coef_table_table_data_4[21] = 14'sb11110100111010;
  assign Coef_table_table_data_4[22] = 14'sb11110100110011;
  assign Coef_table_table_data_4[23] = 14'sb11110100101111;
  assign Coef_table_table_data_4[24] = 14'sb11110100101101;
  assign Coef_table_table_data_4[25] = 14'sb11110100101101;
  assign Coef_table_table_data_4[26] = 14'sb11110100101110;
  assign Coef_table_table_data_4[27] = 14'sb11110100110001;
  assign Coef_table_table_data_4[28] = 14'sb11110100110110;
  assign Coef_table_table_data_4[29] = 14'sb11110100111101;
  assign Coef_table_table_data_4[30] = 14'sb11110101000101;
  assign Coef_table_table_data_4[31] = 14'sb11110101001111;
  assign Coef_table_table_data_4[32] = 14'sb11110101011011;
  assign Coef_table_table_data_4[33] = 14'sb11110101100111;
  assign Coef_table_table_data_4[34] = 14'sb11110101110101;
  assign Coef_table_table_data_4[35] = 14'sb11110110000100;
  assign Coef_table_table_data_4[36] = 14'sb11110110010101;
  assign Coef_table_table_data_4[37] = 14'sb11110110100110;
  assign Coef_table_table_data_4[38] = 14'sb11110110111001;
  assign Coef_table_table_data_4[39] = 14'sb11110111001100;
  assign Coef_table_table_data_4[40] = 14'sb11110111100001;
  assign Coef_table_table_data_4[41] = 14'sb11110111110110;
  assign Coef_table_table_data_4[42] = 14'sb11111000001100;
  assign Coef_table_table_data_4[43] = 14'sb11111000100010;
  assign Coef_table_table_data_4[44] = 14'sb11111000111001;
  assign Coef_table_table_data_4[45] = 14'sb11111001010001;
  assign Coef_table_table_data_4[46] = 14'sb11111001101001;
  assign Coef_table_table_data_4[47] = 14'sb11111010000001;
  assign Coef_table_table_data_4[48] = 14'sb11111010011001;
  assign Coef_table_table_data_4[49] = 14'sb11111010110010;
  assign Coef_table_table_data_4[50] = 14'sb11111011001011;
  assign Coef_table_table_data_4[51] = 14'sb11111011100100;
  assign Coef_table_table_data_4[52] = 14'sb11111011111101;
  assign Coef_table_table_data_4[53] = 14'sb11111100010110;
  assign Coef_table_table_data_4[54] = 14'sb11111100101111;
  assign Coef_table_table_data_4[55] = 14'sb11111101001000;
  assign Coef_table_table_data_4[56] = 14'sb11111101100000;
  assign Coef_table_table_data_4[57] = 14'sb11111101111000;
  assign Coef_table_table_data_4[58] = 14'sb11111110010000;
  assign Coef_table_table_data_4[59] = 14'sb11111110100111;
  assign Coef_table_table_data_4[60] = 14'sb11111110111110;
  assign Coef_table_table_data_4[61] = 14'sb11111111010101;
  assign Coef_table_table_data_4[62] = 14'sb11111111101011;
  assign Coef_table_table_data_4[63] = 14'sb00000000000000;
  assign CoefData_4 = Coef_table_table_data_4[CoefAddr_1];



  always @(posedge clk)
    begin : FilterCoef_4_process
      if (reset == 1'b1) begin
        CoefReg_4 <= 14'sb00000000000000;
      end
      else begin
        if (enb) begin
          CoefReg_4 <= CoefData_4;
        end
      end
    end



  assign CoefOut_4 = CoefReg_4;

  // CoefTable_6
  assign Coef_table_table_data_5[0] = 14'sb00111111111110;
  assign Coef_table_table_data_5[1] = 14'sb00111111111001;
  assign Coef_table_table_data_5[2] = 14'sb00111111110000;
  assign Coef_table_table_data_5[3] = 14'sb00111111100100;
  assign Coef_table_table_data_5[4] = 14'sb00111111010100;
  assign Coef_table_table_data_5[5] = 14'sb00111111000001;
  assign Coef_table_table_data_5[6] = 14'sb00111110101011;
  assign Coef_table_table_data_5[7] = 14'sb00111110010001;
  assign Coef_table_table_data_5[8] = 14'sb00111101110100;
  assign Coef_table_table_data_5[9] = 14'sb00111101010100;
  assign Coef_table_table_data_5[10] = 14'sb00111100110000;
  assign Coef_table_table_data_5[11] = 14'sb00111100001001;
  assign Coef_table_table_data_5[12] = 14'sb00111011100000;
  assign Coef_table_table_data_5[13] = 14'sb00111010110011;
  assign Coef_table_table_data_5[14] = 14'sb00111010000011;
  assign Coef_table_table_data_5[15] = 14'sb00111001010000;
  assign Coef_table_table_data_5[16] = 14'sb00111000011011;
  assign Coef_table_table_data_5[17] = 14'sb00110111100011;
  assign Coef_table_table_data_5[18] = 14'sb00110110101000;
  assign Coef_table_table_data_5[19] = 14'sb00110101101011;
  assign Coef_table_table_data_5[20] = 14'sb00110100101011;
  assign Coef_table_table_data_5[21] = 14'sb00110011101001;
  assign Coef_table_table_data_5[22] = 14'sb00110010100101;
  assign Coef_table_table_data_5[23] = 14'sb00110001011110;
  assign Coef_table_table_data_5[24] = 14'sb00110000010110;
  assign Coef_table_table_data_5[25] = 14'sb00101111001100;
  assign Coef_table_table_data_5[26] = 14'sb00101110000000;
  assign Coef_table_table_data_5[27] = 14'sb00101100110010;
  assign Coef_table_table_data_5[28] = 14'sb00101011100011;
  assign Coef_table_table_data_5[29] = 14'sb00101010010011;
  assign Coef_table_table_data_5[30] = 14'sb00101001000001;
  assign Coef_table_table_data_5[31] = 14'sb00100111101110;
  assign Coef_table_table_data_5[32] = 14'sb00100110011010;
  assign Coef_table_table_data_5[33] = 14'sb00100101000101;
  assign Coef_table_table_data_5[34] = 14'sb00100011101111;
  assign Coef_table_table_data_5[35] = 14'sb00100010011001;
  assign Coef_table_table_data_5[36] = 14'sb00100001000010;
  assign Coef_table_table_data_5[37] = 14'sb00011111101011;
  assign Coef_table_table_data_5[38] = 14'sb00011110010100;
  assign Coef_table_table_data_5[39] = 14'sb00011100111100;
  assign Coef_table_table_data_5[40] = 14'sb00011011100100;
  assign Coef_table_table_data_5[41] = 14'sb00011010001101;
  assign Coef_table_table_data_5[42] = 14'sb00011000110101;
  assign Coef_table_table_data_5[43] = 14'sb00010111011110;
  assign Coef_table_table_data_5[44] = 14'sb00010110001000;
  assign Coef_table_table_data_5[45] = 14'sb00010100110010;
  assign Coef_table_table_data_5[46] = 14'sb00010011011101;
  assign Coef_table_table_data_5[47] = 14'sb00010010001001;
  assign Coef_table_table_data_5[48] = 14'sb00010000110101;
  assign Coef_table_table_data_5[49] = 14'sb00001111100011;
  assign Coef_table_table_data_5[50] = 14'sb00001110010001;
  assign Coef_table_table_data_5[51] = 14'sb00001101000001;
  assign Coef_table_table_data_5[52] = 14'sb00001011110011;
  assign Coef_table_table_data_5[53] = 14'sb00001010100101;
  assign Coef_table_table_data_5[54] = 14'sb00001001011001;
  assign Coef_table_table_data_5[55] = 14'sb00001000001111;
  assign Coef_table_table_data_5[56] = 14'sb00000111000111;
  assign Coef_table_table_data_5[57] = 14'sb00000110000000;
  assign Coef_table_table_data_5[58] = 14'sb00000100111011;
  assign Coef_table_table_data_5[59] = 14'sb00000011111000;
  assign Coef_table_table_data_5[60] = 14'sb00000010110111;
  assign Coef_table_table_data_5[61] = 14'sb00000001111000;
  assign Coef_table_table_data_5[62] = 14'sb00000000111011;
  assign Coef_table_table_data_5[63] = 14'sb00000000000000;
  assign CoefData_5 = Coef_table_table_data_5[CoefAddr_1];



  always @(posedge clk)
    begin : FilterCoef_5_process
      if (reset == 1'b1) begin
        CoefReg_5 <= 14'sb00000000000000;
      end
      else begin
        if (enb) begin
          CoefReg_5 <= CoefData_5;
        end
      end
    end



  assign CoefOut_5 = CoefReg_5;

  // CoefTable_7
  assign Coef_table_table_data_6[0] = 14'sb00000000111011;
  assign Coef_table_table_data_6[1] = 14'sb00000001111000;
  assign Coef_table_table_data_6[2] = 14'sb00000010110111;
  assign Coef_table_table_data_6[3] = 14'sb00000011111000;
  assign Coef_table_table_data_6[4] = 14'sb00000100111011;
  assign Coef_table_table_data_6[5] = 14'sb00000110000000;
  assign Coef_table_table_data_6[6] = 14'sb00000111000111;
  assign Coef_table_table_data_6[7] = 14'sb00001000001111;
  assign Coef_table_table_data_6[8] = 14'sb00001001011001;
  assign Coef_table_table_data_6[9] = 14'sb00001010100101;
  assign Coef_table_table_data_6[10] = 14'sb00001011110011;
  assign Coef_table_table_data_6[11] = 14'sb00001101000001;
  assign Coef_table_table_data_6[12] = 14'sb00001110010001;
  assign Coef_table_table_data_6[13] = 14'sb00001111100011;
  assign Coef_table_table_data_6[14] = 14'sb00010000110101;
  assign Coef_table_table_data_6[15] = 14'sb00010010001001;
  assign Coef_table_table_data_6[16] = 14'sb00010011011101;
  assign Coef_table_table_data_6[17] = 14'sb00010100110010;
  assign Coef_table_table_data_6[18] = 14'sb00010110001000;
  assign Coef_table_table_data_6[19] = 14'sb00010111011110;
  assign Coef_table_table_data_6[20] = 14'sb00011000110101;
  assign Coef_table_table_data_6[21] = 14'sb00011010001101;
  assign Coef_table_table_data_6[22] = 14'sb00011011100100;
  assign Coef_table_table_data_6[23] = 14'sb00011100111100;
  assign Coef_table_table_data_6[24] = 14'sb00011110010100;
  assign Coef_table_table_data_6[25] = 14'sb00011111101011;
  assign Coef_table_table_data_6[26] = 14'sb00100001000010;
  assign Coef_table_table_data_6[27] = 14'sb00100010011001;
  assign Coef_table_table_data_6[28] = 14'sb00100011101111;
  assign Coef_table_table_data_6[29] = 14'sb00100101000101;
  assign Coef_table_table_data_6[30] = 14'sb00100110011010;
  assign Coef_table_table_data_6[31] = 14'sb00100111101110;
  assign Coef_table_table_data_6[32] = 14'sb00101001000001;
  assign Coef_table_table_data_6[33] = 14'sb00101010010011;
  assign Coef_table_table_data_6[34] = 14'sb00101011100011;
  assign Coef_table_table_data_6[35] = 14'sb00101100110010;
  assign Coef_table_table_data_6[36] = 14'sb00101110000000;
  assign Coef_table_table_data_6[37] = 14'sb00101111001100;
  assign Coef_table_table_data_6[38] = 14'sb00110000010110;
  assign Coef_table_table_data_6[39] = 14'sb00110001011110;
  assign Coef_table_table_data_6[40] = 14'sb00110010100101;
  assign Coef_table_table_data_6[41] = 14'sb00110011101001;
  assign Coef_table_table_data_6[42] = 14'sb00110100101011;
  assign Coef_table_table_data_6[43] = 14'sb00110101101011;
  assign Coef_table_table_data_6[44] = 14'sb00110110101000;
  assign Coef_table_table_data_6[45] = 14'sb00110111100011;
  assign Coef_table_table_data_6[46] = 14'sb00111000011011;
  assign Coef_table_table_data_6[47] = 14'sb00111001010000;
  assign Coef_table_table_data_6[48] = 14'sb00111010000011;
  assign Coef_table_table_data_6[49] = 14'sb00111010110011;
  assign Coef_table_table_data_6[50] = 14'sb00111011100000;
  assign Coef_table_table_data_6[51] = 14'sb00111100001001;
  assign Coef_table_table_data_6[52] = 14'sb00111100110000;
  assign Coef_table_table_data_6[53] = 14'sb00111101010100;
  assign Coef_table_table_data_6[54] = 14'sb00111101110100;
  assign Coef_table_table_data_6[55] = 14'sb00111110010001;
  assign Coef_table_table_data_6[56] = 14'sb00111110101011;
  assign Coef_table_table_data_6[57] = 14'sb00111111000001;
  assign Coef_table_table_data_6[58] = 14'sb00111111010100;
  assign Coef_table_table_data_6[59] = 14'sb00111111100100;
  assign Coef_table_table_data_6[60] = 14'sb00111111110000;
  assign Coef_table_table_data_6[61] = 14'sb00111111111001;
  assign Coef_table_table_data_6[62] = 14'sb00111111111110;
  assign Coef_table_table_data_6[63] = 14'sb01000000000000;
  assign CoefData_6 = Coef_table_table_data_6[CoefAddr_1];



  always @(posedge clk)
    begin : FilterCoef_6_process
      if (reset == 1'b1) begin
        CoefReg_6 <= 14'sb00000000000000;
      end
      else begin
        if (enb) begin
          CoefReg_6 <= CoefData_6;
        end
      end
    end



  assign CoefOut_6 = CoefReg_6;

  // CoefTable_8
  assign Coef_table_table_data_7[0] = 14'sb11111111101011;
  assign Coef_table_table_data_7[1] = 14'sb11111111010101;
  assign Coef_table_table_data_7[2] = 14'sb11111110111110;
  assign Coef_table_table_data_7[3] = 14'sb11111110100111;
  assign Coef_table_table_data_7[4] = 14'sb11111110010000;
  assign Coef_table_table_data_7[5] = 14'sb11111101111000;
  assign Coef_table_table_data_7[6] = 14'sb11111101100000;
  assign Coef_table_table_data_7[7] = 14'sb11111101001000;
  assign Coef_table_table_data_7[8] = 14'sb11111100101111;
  assign Coef_table_table_data_7[9] = 14'sb11111100010110;
  assign Coef_table_table_data_7[10] = 14'sb11111011111101;
  assign Coef_table_table_data_7[11] = 14'sb11111011100100;
  assign Coef_table_table_data_7[12] = 14'sb11111011001011;
  assign Coef_table_table_data_7[13] = 14'sb11111010110010;
  assign Coef_table_table_data_7[14] = 14'sb11111010011001;
  assign Coef_table_table_data_7[15] = 14'sb11111010000001;
  assign Coef_table_table_data_7[16] = 14'sb11111001101001;
  assign Coef_table_table_data_7[17] = 14'sb11111001010001;
  assign Coef_table_table_data_7[18] = 14'sb11111000111001;
  assign Coef_table_table_data_7[19] = 14'sb11111000100010;
  assign Coef_table_table_data_7[20] = 14'sb11111000001100;
  assign Coef_table_table_data_7[21] = 14'sb11110111110110;
  assign Coef_table_table_data_7[22] = 14'sb11110111100001;
  assign Coef_table_table_data_7[23] = 14'sb11110111001100;
  assign Coef_table_table_data_7[24] = 14'sb11110110111001;
  assign Coef_table_table_data_7[25] = 14'sb11110110100110;
  assign Coef_table_table_data_7[26] = 14'sb11110110010101;
  assign Coef_table_table_data_7[27] = 14'sb11110110000100;
  assign Coef_table_table_data_7[28] = 14'sb11110101110101;
  assign Coef_table_table_data_7[29] = 14'sb11110101100111;
  assign Coef_table_table_data_7[30] = 14'sb11110101011011;
  assign Coef_table_table_data_7[31] = 14'sb11110101001111;
  assign Coef_table_table_data_7[32] = 14'sb11110101000101;
  assign Coef_table_table_data_7[33] = 14'sb11110100111101;
  assign Coef_table_table_data_7[34] = 14'sb11110100110110;
  assign Coef_table_table_data_7[35] = 14'sb11110100110001;
  assign Coef_table_table_data_7[36] = 14'sb11110100101110;
  assign Coef_table_table_data_7[37] = 14'sb11110100101101;
  assign Coef_table_table_data_7[38] = 14'sb11110100101101;
  assign Coef_table_table_data_7[39] = 14'sb11110100101111;
  assign Coef_table_table_data_7[40] = 14'sb11110100110011;
  assign Coef_table_table_data_7[41] = 14'sb11110100111010;
  assign Coef_table_table_data_7[42] = 14'sb11110101000010;
  assign Coef_table_table_data_7[43] = 14'sb11110101001100;
  assign Coef_table_table_data_7[44] = 14'sb11110101011001;
  assign Coef_table_table_data_7[45] = 14'sb11110101101000;
  assign Coef_table_table_data_7[46] = 14'sb11110101111001;
  assign Coef_table_table_data_7[47] = 14'sb11110110001100;
  assign Coef_table_table_data_7[48] = 14'sb11110110100010;
  assign Coef_table_table_data_7[49] = 14'sb11110110111010;
  assign Coef_table_table_data_7[50] = 14'sb11110111010100;
  assign Coef_table_table_data_7[51] = 14'sb11110111110000;
  assign Coef_table_table_data_7[52] = 14'sb11111000001111;
  assign Coef_table_table_data_7[53] = 14'sb11111000110001;
  assign Coef_table_table_data_7[54] = 14'sb11111001010100;
  assign Coef_table_table_data_7[55] = 14'sb11111001111011;
  assign Coef_table_table_data_7[56] = 14'sb11111010100011;
  assign Coef_table_table_data_7[57] = 14'sb11111011001110;
  assign Coef_table_table_data_7[58] = 14'sb11111011111011;
  assign Coef_table_table_data_7[59] = 14'sb11111100101011;
  assign Coef_table_table_data_7[60] = 14'sb11111101011101;
  assign Coef_table_table_data_7[61] = 14'sb11111110010001;
  assign Coef_table_table_data_7[62] = 14'sb11111111000111;
  assign Coef_table_table_data_7[63] = 14'sb00000000000000;
  assign CoefData_7 = Coef_table_table_data_7[CoefAddr_1];



  always @(posedge clk)
    begin : FilterCoef_7_process
      if (reset == 1'b1) begin
        CoefReg_7 <= 14'sb00000000000000;
      end
      else begin
        if (enb) begin
          CoefReg_7 <= CoefData_7;
        end
      end
    end



  assign CoefOut_7 = CoefReg_7;

  // CoefTable_9
  assign Coef_table_table_data_8[0] = 14'sb00000000001000;
  assign Coef_table_table_data_8[1] = 14'sb00000000010001;
  assign Coef_table_table_data_8[2] = 14'sb00000000011001;
  assign Coef_table_table_data_8[3] = 14'sb00000000100010;
  assign Coef_table_table_data_8[4] = 14'sb00000000101011;
  assign Coef_table_table_data_8[5] = 14'sb00000000110100;
  assign Coef_table_table_data_8[6] = 14'sb00000000111110;
  assign Coef_table_table_data_8[7] = 14'sb00000001000111;
  assign Coef_table_table_data_8[8] = 14'sb00000001010001;
  assign Coef_table_table_data_8[9] = 14'sb00000001011010;
  assign Coef_table_table_data_8[10] = 14'sb00000001100100;
  assign Coef_table_table_data_8[11] = 14'sb00000001101110;
  assign Coef_table_table_data_8[12] = 14'sb00000001111000;
  assign Coef_table_table_data_8[13] = 14'sb00000010000001;
  assign Coef_table_table_data_8[14] = 14'sb00000010001011;
  assign Coef_table_table_data_8[15] = 14'sb00000010010101;
  assign Coef_table_table_data_8[16] = 14'sb00000010011110;
  assign Coef_table_table_data_8[17] = 14'sb00000010101000;
  assign Coef_table_table_data_8[18] = 14'sb00000010110001;
  assign Coef_table_table_data_8[19] = 14'sb00000010111010;
  assign Coef_table_table_data_8[20] = 14'sb00000011000011;
  assign Coef_table_table_data_8[21] = 14'sb00000011001011;
  assign Coef_table_table_data_8[22] = 14'sb00000011010100;
  assign Coef_table_table_data_8[23] = 14'sb00000011011100;
  assign Coef_table_table_data_8[24] = 14'sb00000011100011;
  assign Coef_table_table_data_8[25] = 14'sb00000011101011;
  assign Coef_table_table_data_8[26] = 14'sb00000011110001;
  assign Coef_table_table_data_8[27] = 14'sb00000011111000;
  assign Coef_table_table_data_8[28] = 14'sb00000011111110;
  assign Coef_table_table_data_8[29] = 14'sb00000100000011;
  assign Coef_table_table_data_8[30] = 14'sb00000100001000;
  assign Coef_table_table_data_8[31] = 14'sb00000100001100;
  assign Coef_table_table_data_8[32] = 14'sb00000100010000;
  assign Coef_table_table_data_8[33] = 14'sb00000100010011;
  assign Coef_table_table_data_8[34] = 14'sb00000100010101;
  assign Coef_table_table_data_8[35] = 14'sb00000100010111;
  assign Coef_table_table_data_8[36] = 14'sb00000100011000;
  assign Coef_table_table_data_8[37] = 14'sb00000100011001;
  assign Coef_table_table_data_8[38] = 14'sb00000100011000;
  assign Coef_table_table_data_8[39] = 14'sb00000100010111;
  assign Coef_table_table_data_8[40] = 14'sb00000100010101;
  assign Coef_table_table_data_8[41] = 14'sb00000100010010;
  assign Coef_table_table_data_8[42] = 14'sb00000100001111;
  assign Coef_table_table_data_8[43] = 14'sb00000100001010;
  assign Coef_table_table_data_8[44] = 14'sb00000100000101;
  assign Coef_table_table_data_8[45] = 14'sb00000011111111;
  assign Coef_table_table_data_8[46] = 14'sb00000011111000;
  assign Coef_table_table_data_8[47] = 14'sb00000011110000;
  assign Coef_table_table_data_8[48] = 14'sb00000011101000;
  assign Coef_table_table_data_8[49] = 14'sb00000011011110;
  assign Coef_table_table_data_8[50] = 14'sb00000011010011;
  assign Coef_table_table_data_8[51] = 14'sb00000011001000;
  assign Coef_table_table_data_8[52] = 14'sb00000010111100;
  assign Coef_table_table_data_8[53] = 14'sb00000010101111;
  assign Coef_table_table_data_8[54] = 14'sb00000010100001;
  assign Coef_table_table_data_8[55] = 14'sb00000010010010;
  assign Coef_table_table_data_8[56] = 14'sb00000010000011;
  assign Coef_table_table_data_8[57] = 14'sb00000001110010;
  assign Coef_table_table_data_8[58] = 14'sb00000001100001;
  assign Coef_table_table_data_8[59] = 14'sb00000001001111;
  assign Coef_table_table_data_8[60] = 14'sb00000000111100;
  assign Coef_table_table_data_8[61] = 14'sb00000000101001;
  assign Coef_table_table_data_8[62] = 14'sb00000000010101;
  assign Coef_table_table_data_8[63] = 14'sb00000000000000;
  assign CoefData_8 = Coef_table_table_data_8[CoefAddr_1];



  always @(posedge clk)
    begin : FilterCoef_8_process
      if (reset == 1'b1) begin
        CoefReg_8 <= 14'sb00000000000000;
      end
      else begin
        if (enb) begin
          CoefReg_8 <= CoefData_8;
        end
      end
    end



  assign CoefOut_8 = CoefReg_8;

  // CoefTable_10
  assign Coef_table_table_data_9[0] = 14'sb11111111111101;
  assign Coef_table_table_data_9[1] = 14'sb11111111111011;
  assign Coef_table_table_data_9[2] = 14'sb11111111111000;
  assign Coef_table_table_data_9[3] = 14'sb11111111110101;
  assign Coef_table_table_data_9[4] = 14'sb11111111110010;
  assign Coef_table_table_data_9[5] = 14'sb11111111101111;
  assign Coef_table_table_data_9[6] = 14'sb11111111101100;
  assign Coef_table_table_data_9[7] = 14'sb11111111101001;
  assign Coef_table_table_data_9[8] = 14'sb11111111100110;
  assign Coef_table_table_data_9[9] = 14'sb11111111100010;
  assign Coef_table_table_data_9[10] = 14'sb11111111011111;
  assign Coef_table_table_data_9[11] = 14'sb11111111011100;
  assign Coef_table_table_data_9[12] = 14'sb11111111011000;
  assign Coef_table_table_data_9[13] = 14'sb11111111010101;
  assign Coef_table_table_data_9[14] = 14'sb11111111010001;
  assign Coef_table_table_data_9[15] = 14'sb11111111001110;
  assign Coef_table_table_data_9[16] = 14'sb11111111001011;
  assign Coef_table_table_data_9[17] = 14'sb11111111000111;
  assign Coef_table_table_data_9[18] = 14'sb11111111000100;
  assign Coef_table_table_data_9[19] = 14'sb11111111000001;
  assign Coef_table_table_data_9[20] = 14'sb11111110111101;
  assign Coef_table_table_data_9[21] = 14'sb11111110111010;
  assign Coef_table_table_data_9[22] = 14'sb11111110110111;
  assign Coef_table_table_data_9[23] = 14'sb11111110110100;
  assign Coef_table_table_data_9[24] = 14'sb11111110110001;
  assign Coef_table_table_data_9[25] = 14'sb11111110101111;
  assign Coef_table_table_data_9[26] = 14'sb11111110101100;
  assign Coef_table_table_data_9[27] = 14'sb11111110101001;
  assign Coef_table_table_data_9[28] = 14'sb11111110100111;
  assign Coef_table_table_data_9[29] = 14'sb11111110100101;
  assign Coef_table_table_data_9[30] = 14'sb11111110100011;
  assign Coef_table_table_data_9[31] = 14'sb11111110100001;
  assign Coef_table_table_data_9[32] = 14'sb11111110011111;
  assign Coef_table_table_data_9[33] = 14'sb11111110011110;
  assign Coef_table_table_data_9[34] = 14'sb11111110011101;
  assign Coef_table_table_data_9[35] = 14'sb11111110011100;
  assign Coef_table_table_data_9[36] = 14'sb11111110011011;
  assign Coef_table_table_data_9[37] = 14'sb11111110011011;
  assign Coef_table_table_data_9[38] = 14'sb11111110011011;
  assign Coef_table_table_data_9[39] = 14'sb11111110011011;
  assign Coef_table_table_data_9[40] = 14'sb11111110011011;
  assign Coef_table_table_data_9[41] = 14'sb11111110011100;
  assign Coef_table_table_data_9[42] = 14'sb11111110011101;
  assign Coef_table_table_data_9[43] = 14'sb11111110011111;
  assign Coef_table_table_data_9[44] = 14'sb11111110100000;
  assign Coef_table_table_data_9[45] = 14'sb11111110100010;
  assign Coef_table_table_data_9[46] = 14'sb11111110100101;
  assign Coef_table_table_data_9[47] = 14'sb11111110100111;
  assign Coef_table_table_data_9[48] = 14'sb11111110101010;
  assign Coef_table_table_data_9[49] = 14'sb11111110101110;
  assign Coef_table_table_data_9[50] = 14'sb11111110110001;
  assign Coef_table_table_data_9[51] = 14'sb11111110110101;
  assign Coef_table_table_data_9[52] = 14'sb11111110111010;
  assign Coef_table_table_data_9[53] = 14'sb11111110111111;
  assign Coef_table_table_data_9[54] = 14'sb11111111000100;
  assign Coef_table_table_data_9[55] = 14'sb11111111001001;
  assign Coef_table_table_data_9[56] = 14'sb11111111001111;
  assign Coef_table_table_data_9[57] = 14'sb11111111010101;
  assign Coef_table_table_data_9[58] = 14'sb11111111011011;
  assign Coef_table_table_data_9[59] = 14'sb11111111100010;
  assign Coef_table_table_data_9[60] = 14'sb11111111101001;
  assign Coef_table_table_data_9[61] = 14'sb11111111110000;
  assign Coef_table_table_data_9[62] = 14'sb11111111111000;
  assign Coef_table_table_data_9[63] = 14'sb00000000000000;
  assign CoefData_9 = Coef_table_table_data_9[CoefAddr_1];



  always @(posedge clk)
    begin : FilterCoef_9_process
      if (reset == 1'b1) begin
        CoefReg_9 <= 14'sb00000000000000;
      end
      else begin
        if (enb) begin
          CoefReg_9 <= CoefData_9;
        end
      end
    end



  assign CoefOut_9 = CoefReg_9;

  // CoefTable_11
  assign Coef_table_table_data_10[0] = 14'sb00000000000001;
  assign Coef_table_table_data_10[1] = 14'sb00000000000001;
  assign Coef_table_table_data_10[2] = 14'sb00000000000010;
  assign Coef_table_table_data_10[3] = 14'sb00000000000010;
  assign Coef_table_table_data_10[4] = 14'sb00000000000011;
  assign Coef_table_table_data_10[5] = 14'sb00000000000100;
  assign Coef_table_table_data_10[6] = 14'sb00000000000100;
  assign Coef_table_table_data_10[7] = 14'sb00000000000101;
  assign Coef_table_table_data_10[8] = 14'sb00000000000110;
  assign Coef_table_table_data_10[9] = 14'sb00000000000111;
  assign Coef_table_table_data_10[10] = 14'sb00000000001000;
  assign Coef_table_table_data_10[11] = 14'sb00000000001000;
  assign Coef_table_table_data_10[12] = 14'sb00000000001001;
  assign Coef_table_table_data_10[13] = 14'sb00000000001010;
  assign Coef_table_table_data_10[14] = 14'sb00000000001011;
  assign Coef_table_table_data_10[15] = 14'sb00000000001100;
  assign Coef_table_table_data_10[16] = 14'sb00000000001101;
  assign Coef_table_table_data_10[17] = 14'sb00000000001110;
  assign Coef_table_table_data_10[18] = 14'sb00000000001111;
  assign Coef_table_table_data_10[19] = 14'sb00000000001111;
  assign Coef_table_table_data_10[20] = 14'sb00000000010000;
  assign Coef_table_table_data_10[21] = 14'sb00000000010001;
  assign Coef_table_table_data_10[22] = 14'sb00000000010010;
  assign Coef_table_table_data_10[23] = 14'sb00000000010011;
  assign Coef_table_table_data_10[24] = 14'sb00000000010100;
  assign Coef_table_table_data_10[25] = 14'sb00000000010101;
  assign Coef_table_table_data_10[26] = 14'sb00000000010110;
  assign Coef_table_table_data_10[27] = 14'sb00000000010110;
  assign Coef_table_table_data_10[28] = 14'sb00000000010111;
  assign Coef_table_table_data_10[29] = 14'sb00000000011000;
  assign Coef_table_table_data_10[30] = 14'sb00000000011001;
  assign Coef_table_table_data_10[31] = 14'sb00000000011001;
  assign Coef_table_table_data_10[32] = 14'sb00000000011010;
  assign Coef_table_table_data_10[33] = 14'sb00000000011010;
  assign Coef_table_table_data_10[34] = 14'sb00000000011011;
  assign Coef_table_table_data_10[35] = 14'sb00000000011011;
  assign Coef_table_table_data_10[36] = 14'sb00000000011100;
  assign Coef_table_table_data_10[37] = 14'sb00000000011100;
  assign Coef_table_table_data_10[38] = 14'sb00000000011100;
  assign Coef_table_table_data_10[39] = 14'sb00000000011100;
  assign Coef_table_table_data_10[40] = 14'sb00000000011100;
  assign Coef_table_table_data_10[41] = 14'sb00000000011100;
  assign Coef_table_table_data_10[42] = 14'sb00000000011100;
  assign Coef_table_table_data_10[43] = 14'sb00000000011100;
  assign Coef_table_table_data_10[44] = 14'sb00000000011011;
  assign Coef_table_table_data_10[45] = 14'sb00000000011011;
  assign Coef_table_table_data_10[46] = 14'sb00000000011010;
  assign Coef_table_table_data_10[47] = 14'sb00000000011010;
  assign Coef_table_table_data_10[48] = 14'sb00000000011001;
  assign Coef_table_table_data_10[49] = 14'sb00000000011000;
  assign Coef_table_table_data_10[50] = 14'sb00000000010111;
  assign Coef_table_table_data_10[51] = 14'sb00000000010110;
  assign Coef_table_table_data_10[52] = 14'sb00000000010101;
  assign Coef_table_table_data_10[53] = 14'sb00000000010100;
  assign Coef_table_table_data_10[54] = 14'sb00000000010010;
  assign Coef_table_table_data_10[55] = 14'sb00000000010001;
  assign Coef_table_table_data_10[56] = 14'sb00000000001111;
  assign Coef_table_table_data_10[57] = 14'sb00000000001101;
  assign Coef_table_table_data_10[58] = 14'sb00000000001011;
  assign Coef_table_table_data_10[59] = 14'sb00000000001001;
  assign Coef_table_table_data_10[60] = 14'sb00000000000111;
  assign Coef_table_table_data_10[61] = 14'sb00000000000101;
  assign Coef_table_table_data_10[62] = 14'sb00000000000010;
  assign Coef_table_table_data_10[63] = 14'sb00000000000000;
  assign CoefData_10 = Coef_table_table_data_10[CoefAddr_1];



  always @(posedge clk)
    begin : FilterCoef_10_process
      if (reset == 1'b1) begin
        CoefReg_10 <= 14'sb00000000000000;
      end
      else begin
        if (enb) begin
          CoefReg_10 <= CoefData_10;
        end
      end
    end



  assign CoefOut_10 = CoefReg_10;

  // CoefTable_12
  assign Coef_table_table_data_11[0] = 14'sb00000000000000;
  assign Coef_table_table_data_11[1] = 14'sb00000000000000;
  assign Coef_table_table_data_11[2] = 14'sb00000000000000;
  assign Coef_table_table_data_11[3] = 14'sb00000000000000;
  assign Coef_table_table_data_11[4] = 14'sb00000000000000;
  assign Coef_table_table_data_11[5] = 14'sb00000000000000;
  assign Coef_table_table_data_11[6] = 14'sb00000000000000;
  assign Coef_table_table_data_11[7] = 14'sb00000000000000;
  assign Coef_table_table_data_11[8] = 14'sb00000000000000;
  assign Coef_table_table_data_11[9] = 14'sb11111111111111;
  assign Coef_table_table_data_11[10] = 14'sb11111111111111;
  assign Coef_table_table_data_11[11] = 14'sb11111111111111;
  assign Coef_table_table_data_11[12] = 14'sb11111111111111;
  assign Coef_table_table_data_11[13] = 14'sb11111111111111;
  assign Coef_table_table_data_11[14] = 14'sb11111111111111;
  assign Coef_table_table_data_11[15] = 14'sb11111111111111;
  assign Coef_table_table_data_11[16] = 14'sb11111111111111;
  assign Coef_table_table_data_11[17] = 14'sb11111111111111;
  assign Coef_table_table_data_11[18] = 14'sb11111111111110;
  assign Coef_table_table_data_11[19] = 14'sb11111111111110;
  assign Coef_table_table_data_11[20] = 14'sb11111111111110;
  assign Coef_table_table_data_11[21] = 14'sb11111111111110;
  assign Coef_table_table_data_11[22] = 14'sb11111111111110;
  assign Coef_table_table_data_11[23] = 14'sb11111111111110;
  assign Coef_table_table_data_11[24] = 14'sb11111111111110;
  assign Coef_table_table_data_11[25] = 14'sb11111111111101;
  assign Coef_table_table_data_11[26] = 14'sb11111111111101;
  assign Coef_table_table_data_11[27] = 14'sb11111111111101;
  assign Coef_table_table_data_11[28] = 14'sb11111111111101;
  assign Coef_table_table_data_11[29] = 14'sb11111111111101;
  assign Coef_table_table_data_11[30] = 14'sb11111111111101;
  assign Coef_table_table_data_11[31] = 14'sb11111111111101;
  assign Coef_table_table_data_11[32] = 14'sb11111111111100;
  assign Coef_table_table_data_11[33] = 14'sb11111111111100;
  assign Coef_table_table_data_11[34] = 14'sb11111111111100;
  assign Coef_table_table_data_11[35] = 14'sb11111111111100;
  assign Coef_table_table_data_11[36] = 14'sb11111111111100;
  assign Coef_table_table_data_11[37] = 14'sb11111111111100;
  assign Coef_table_table_data_11[38] = 14'sb11111111111100;
  assign Coef_table_table_data_11[39] = 14'sb11111111111100;
  assign Coef_table_table_data_11[40] = 14'sb11111111111100;
  assign Coef_table_table_data_11[41] = 14'sb11111111111011;
  assign Coef_table_table_data_11[42] = 14'sb11111111111011;
  assign Coef_table_table_data_11[43] = 14'sb11111111111011;
  assign Coef_table_table_data_11[44] = 14'sb11111111111011;
  assign Coef_table_table_data_11[45] = 14'sb11111111111011;
  assign Coef_table_table_data_11[46] = 14'sb11111111111011;
  assign Coef_table_table_data_11[47] = 14'sb11111111111100;
  assign Coef_table_table_data_11[48] = 14'sb11111111111100;
  assign Coef_table_table_data_11[49] = 14'sb11111111111100;
  assign Coef_table_table_data_11[50] = 14'sb11111111111100;
  assign Coef_table_table_data_11[51] = 14'sb11111111111100;
  assign Coef_table_table_data_11[52] = 14'sb11111111111100;
  assign Coef_table_table_data_11[53] = 14'sb11111111111100;
  assign Coef_table_table_data_11[54] = 14'sb11111111111101;
  assign Coef_table_table_data_11[55] = 14'sb11111111111101;
  assign Coef_table_table_data_11[56] = 14'sb11111111111101;
  assign Coef_table_table_data_11[57] = 14'sb11111111111101;
  assign Coef_table_table_data_11[58] = 14'sb11111111111110;
  assign Coef_table_table_data_11[59] = 14'sb11111111111110;
  assign Coef_table_table_data_11[60] = 14'sb11111111111111;
  assign Coef_table_table_data_11[61] = 14'sb11111111111111;
  assign Coef_table_table_data_11[62] = 14'sb11111111111111;
  assign Coef_table_table_data_11[63] = 14'sb00000000000000;
  assign CoefData_11 = Coef_table_table_data_11[CoefAddr_1];



  always @(posedge clk)
    begin : FilterCoef_11_process
      if (reset == 1'b1) begin
        CoefReg_11 <= 14'sb00000000000000;
      end
      else begin
        if (enb) begin
          CoefReg_11 <= CoefData_11;
        end
      end
    end



  assign CoefOut_11 = CoefReg_11;

endmodule  // rx_dma_test_src_FilterCoef

