// -------------------------------------------------------------
// 
// File Name: /home/draco/git/adi_dma_testing/iq_dma_example/hdl_ip/hdlsrc/rx_dma_test/rx_dma_test_src_FilterBank.v
// Created: 2025-08-21 13:52:00
// 
// Generated by MATLAB 24.1, HDL Coder 24.1, and Simulink 24.1
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: rx_dma_test_src_FilterBank
// Source Path: rx_dma_test/LDCR_D/Channelizer_CH1/FilterBank
// Hierarchy Level: 2
// Model version: 9.535
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module rx_dma_test_src_FilterBank
          (clk,
           reset,
           enb,
           dataIn_re,
           dataIn_im,
           validIn,
           filterOut_cmplx_re,
           filterOut_cmplx_im,
           filterOut_vld);


  input   clk;
  input   reset;
  input   enb;
  input   signed [13:0] dataIn_re;  // sfix14
  input   signed [13:0] dataIn_im;  // sfix14
  input   validIn;
  output  signed [13:0] filterOut_cmplx_re;  // sfix14_En5
  output  signed [13:0] filterOut_cmplx_im;  // sfix14_En5
  output  filterOut_vld;


  wire syncReset;
  reg  dinRegVld;
  reg signed [13:0] dinReg_0_re;  // sfix14
  reg signed [13:0] dinReg2_0_re;  // sfix14
  wire signed [13:0] CoefOut_0;  // sfix14_En18
  wire signed [13:0] CoefOut_1;  // sfix14_En18
  wire signed [13:0] CoefOut_2;  // sfix14_En18
  wire signed [13:0] CoefOut_3;  // sfix14_En18
  wire signed [13:0] CoefOut_4;  // sfix14_En18
  wire signed [13:0] CoefOut_5;  // sfix14_En18
  wire signed [13:0] CoefOut_6;  // sfix14_En18
  wire signed [13:0] CoefOut_7;  // sfix14_En18
  wire signed [13:0] CoefOut_8;  // sfix14_En18
  wire signed [13:0] CoefOut_9;  // sfix14_En18
  wire signed [13:0] CoefOut_10;  // sfix14_En18
  wire signed [13:0] CoefOut_11;  // sfix14_En18
  reg  dinReg2Vld;
  wire signed [13:0] dout_1_re;  // sfix14_En5
  wire doutVld;
  reg signed [13:0] dinReg_0_im;  // sfix14
  reg signed [13:0] dinReg2_0_im;  // sfix14
  wire signed [13:0] dout_1_im;  // sfix14_En5
  wire doutVlddeadOut;


  assign syncReset = 1'b0;



  always @(posedge clk)
    begin : intdelay_process
      if (reset == 1'b1) begin
        dinRegVld <= 1'b0;
      end
      else begin
        if (enb) begin
          if (syncReset == 1'b1) begin
            dinRegVld <= 1'b0;
          end
          else begin
            dinRegVld <= validIn;
          end
        end
      end
    end



  always @(posedge clk)
    begin : intdelay_1_process
      if (reset == 1'b1) begin
        dinReg_0_re <= 14'sb00000000000000;
      end
      else begin
        if (enb) begin
          if (syncReset == 1'b1) begin
            dinReg_0_re <= 14'sb00000000000000;
          end
          else begin
            if (validIn) begin
              dinReg_0_re <= dataIn_re;
            end
          end
        end
      end
    end



  always @(posedge clk)
    begin : intdelay_2_process
      if (reset == 1'b1) begin
        dinReg2_0_re <= 14'sb00000000000000;
      end
      else begin
        if (enb) begin
          if (syncReset == 1'b1) begin
            dinReg2_0_re <= 14'sb00000000000000;
          end
          else begin
            if (dinRegVld) begin
              dinReg2_0_re <= dinReg_0_re;
            end
          end
        end
      end
    end



  rx_dma_test_src_FilterCoef u_CoefTable_1 (.clk(clk),
                                            .reset(reset),
                                            .enb(enb),
                                            .validIn(validIn),
                                            .syncReset(syncReset),
                                            .CoefOut_0(CoefOut_0),  // sfix14_En18
                                            .CoefOut_1(CoefOut_1),  // sfix14_En18
                                            .CoefOut_2(CoefOut_2),  // sfix14_En18
                                            .CoefOut_3(CoefOut_3),  // sfix14_En18
                                            .CoefOut_4(CoefOut_4),  // sfix14_En18
                                            .CoefOut_5(CoefOut_5),  // sfix14_En18
                                            .CoefOut_6(CoefOut_6),  // sfix14_En18
                                            .CoefOut_7(CoefOut_7),  // sfix14_En18
                                            .CoefOut_8(CoefOut_8),  // sfix14_En18
                                            .CoefOut_9(CoefOut_9),  // sfix14_En18
                                            .CoefOut_10(CoefOut_10),  // sfix14_En18
                                            .CoefOut_11(CoefOut_11)  // sfix14_En18
                                            );

  always @(posedge clk)
    begin : intdelay_3_process
      if (reset == 1'b1) begin
        dinReg2Vld <= 1'b0;
      end
      else begin
        if (enb) begin
          if (syncReset == 1'b1) begin
            dinReg2Vld <= 1'b0;
          end
          else begin
            dinReg2Vld <= dinRegVld;
          end
        end
      end
    end



  rx_dma_test_src_subFilter u_subFilter_1_re (.clk(clk),
                                              .reset(reset),
                                              .enb(enb),
                                              .dinReg2_0_re(dinReg2_0_re),  // sfix14
                                              .coefIn_0(CoefOut_0),  // sfix14_En18
                                              .coefIn_1(CoefOut_1),  // sfix14_En18
                                              .coefIn_2(CoefOut_2),  // sfix14_En18
                                              .coefIn_3(CoefOut_3),  // sfix14_En18
                                              .coefIn_4(CoefOut_4),  // sfix14_En18
                                              .coefIn_5(CoefOut_5),  // sfix14_En18
                                              .coefIn_6(CoefOut_6),  // sfix14_En18
                                              .coefIn_7(CoefOut_7),  // sfix14_En18
                                              .coefIn_8(CoefOut_8),  // sfix14_En18
                                              .coefIn_9(CoefOut_9),  // sfix14_En18
                                              .coefIn_10(CoefOut_10),  // sfix14_En18
                                              .coefIn_11(CoefOut_11),  // sfix14_En18
                                              .dinRegVld(dinReg2Vld),
                                              .syncReset(syncReset),
                                              .dout_1_re(dout_1_re),  // sfix14_En5
                                              .doutVld(doutVld)
                                              );

  assign filterOut_cmplx_re = dout_1_re;

  always @(posedge clk)
    begin : intdelay_4_process
      if (reset == 1'b1) begin
        dinReg_0_im <= 14'sb00000000000000;
      end
      else begin
        if (enb) begin
          if (syncReset == 1'b1) begin
            dinReg_0_im <= 14'sb00000000000000;
          end
          else begin
            if (validIn) begin
              dinReg_0_im <= dataIn_im;
            end
          end
        end
      end
    end



  always @(posedge clk)
    begin : intdelay_5_process
      if (reset == 1'b1) begin
        dinReg2_0_im <= 14'sb00000000000000;
      end
      else begin
        if (enb) begin
          if (syncReset == 1'b1) begin
            dinReg2_0_im <= 14'sb00000000000000;
          end
          else begin
            if (dinRegVld) begin
              dinReg2_0_im <= dinReg_0_im;
            end
          end
        end
      end
    end



  rx_dma_test_src_subFilter u_subFilter_1_im (.clk(clk),
                                              .reset(reset),
                                              .enb(enb),
                                              .dinReg2_0_re(dinReg2_0_im),  // sfix14
                                              .coefIn_0(CoefOut_0),  // sfix14_En18
                                              .coefIn_1(CoefOut_1),  // sfix14_En18
                                              .coefIn_2(CoefOut_2),  // sfix14_En18
                                              .coefIn_3(CoefOut_3),  // sfix14_En18
                                              .coefIn_4(CoefOut_4),  // sfix14_En18
                                              .coefIn_5(CoefOut_5),  // sfix14_En18
                                              .coefIn_6(CoefOut_6),  // sfix14_En18
                                              .coefIn_7(CoefOut_7),  // sfix14_En18
                                              .coefIn_8(CoefOut_8),  // sfix14_En18
                                              .coefIn_9(CoefOut_9),  // sfix14_En18
                                              .coefIn_10(CoefOut_10),  // sfix14_En18
                                              .coefIn_11(CoefOut_11),  // sfix14_En18
                                              .dinRegVld(dinReg2Vld),
                                              .syncReset(syncReset),
                                              .dout_1_re(dout_1_im),  // sfix14_En5
                                              .doutVld(doutVlddeadOut)
                                              );

  assign filterOut_cmplx_im = dout_1_im;

  assign filterOut_vld = doutVld;

endmodule  // rx_dma_test_src_FilterBank

