open_system('gm_rx_dma_test');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_rx_dma_test/LDCR_D/Subsystem', 'user2');
annotate_port('gm_rx_dma_test/LDCR_D/Subsystem', 0, 1, 'cp : 3.549 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_rx_dma_test/LDCR_D/Subsystem/HDL Counter1', 'user2');
annotate_port('gm_rx_dma_test/LDCR_D/Subsystem/HDL Counter1', 0, 1, 'cp : 3.549 ns');
