open_system('gm_rx_dma_test');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_rx_dma_test/LDCR_D/counter_subsystem', 'user2');
annotate_port('gm_rx_dma_test/LDCR_D/counter_subsystem', 0, 4, 'cp : 4.02 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_rx_dma_test/LDCR_D/counter_subsystem/HDL Counter', 'user2');
annotate_port('gm_rx_dma_test/LDCR_D/counter_subsystem/HDL Counter', 0, 1, 'cp : 0.511 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_rx_dma_test/LDCR_D/counter_subsystem/Add', 'user2');
annotate_port('gm_rx_dma_test/LDCR_D/counter_subsystem/Add', 0, 1, 'cp : 1.642 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_rx_dma_test/LDCR_D/counter_subsystem/Add1', 'user2');
annotate_port('gm_rx_dma_test/LDCR_D/counter_subsystem/Add1', 0, 1, 'cp : 2.831 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_rx_dma_test/LDCR_D/counter_subsystem/Add2', 'user2');
annotate_port('gm_rx_dma_test/LDCR_D/counter_subsystem/Add2', 0, 1, 'cp : 4.02 ns');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'blue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_rx_dma_test/LDCR_D/counter_subsystem/Data Type Conversion3', 'user1');
annotate_port('gm_rx_dma_test/LDCR_D/counter_subsystem/Data Type Conversion3', 0, 1, 'cp : 4.02 ns');
