cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'red';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('rx_dma_test/LDCR_D/AND1','user1');
hilite_system('rx_dma_test/LDCR_D/Cast1','user1');
hilite_system('rx_dma_test/LDCR_D/Cast3','user1');
hilite_system('rx_dma_test/LDCR_D/Channelizer_CH2','user1');
hilite_system('rx_dma_test/LDCR_D/Delay12','user1');
hilite_system('rx_dma_test/LDCR_D/Delay13','user1');
hilite_system('rx_dma_test/LDCR_D/Delay14','user1');
hilite_system('rx_dma_test/LDCR_D/Delay16','user1');
hilite_system('rx_dma_test/LDCR_D/Delay6','user1');
hilite_system('rx_dma_test/LDCR_D/Delay7','user1');
hilite_system('rx_dma_test/LDCR_D/Delay8','user1');
hilite_system('rx_dma_test/LDCR_D/DropBits1','user1');
hilite_system('rx_dma_test/LDCR_D/DropBits1/Bit Slice','user1');
hilite_system('rx_dma_test/LDCR_D/DropBits2','user1');
hilite_system('rx_dma_test/LDCR_D/DropBits2/Bit Slice','user1');
hilite_system('rx_dma_test/LDCR_D/FIFOSerializer','user1');
hilite_system('rx_dma_test/LDCR_D/FIFOSerializer/Compare To Constant1','user1');
hilite_system('rx_dma_test/LDCR_D/FIFOSerializer/Delay1','user1');
hilite_system('rx_dma_test/LDCR_D/MAC_C11','user1');
hilite_system('rx_dma_test/LDCR_D/MAC_C11/ComplexMultiply','user1');
hilite_system('rx_dma_test/LDCR_D/MAC_C21','user1');
hilite_system('rx_dma_test/LDCR_D/MAC_C21/ComplexMultiply','user1');
hilite_system('rx_dma_test/LDCR_D/MAC_C22','user1');
hilite_system('rx_dma_test/LDCR_D/MAC_C22/ComplexMultiply','user1');
hilite_system('rx_dma_test/LDCR_D/Subsystem/NOT','user1');
hilite_system('rx_dma_test/LDCR_D/Real-Imag to Complex1','user1');
hilite_system('rx_dma_test/LDCR_D/Vector Concatenate','user1');
hilite_system('rx_dma_test/LDCR_D/MAC_C11/ComplexMultiply/Add','user1');
hilite_system('rx_dma_test/LDCR_D/MAC_C11/ComplexMultiply/Add1','user1');
hilite_system('rx_dma_test/LDCR_D/MAC_C11/ComplexMultiply/Complex to Real-Imag','user1');
hilite_system('rx_dma_test/LDCR_D/MAC_C11/ComplexMultiply/Complex to Real-Imag1','user1');
hilite_system('rx_dma_test/LDCR_D/MAC_C11/ComplexMultiply/Delay1','user1');
hilite_system('rx_dma_test/LDCR_D/MAC_C11/ComplexMultiply/Delay2','user1');
hilite_system('rx_dma_test/LDCR_D/MAC_C11/ComplexMultiply/Delay3','user1');
hilite_system('rx_dma_test/LDCR_D/MAC_C11/ComplexMultiply/Delay4','user1');
hilite_system('rx_dma_test/LDCR_D/MAC_C11/ComplexMultiply/Delay5','user1');
hilite_system('rx_dma_test/LDCR_D/MAC_C11/ComplexMultiply/Delay6','user1');
hilite_system('rx_dma_test/LDCR_D/MAC_C11/ComplexMultiply/Delay7','user1');
hilite_system('rx_dma_test/LDCR_D/MAC_C11/ComplexMultiply/Delay8','user1');
hilite_system('rx_dma_test/LDCR_D/MAC_C11/ComplexMultiply/Product','user1');
hilite_system('rx_dma_test/LDCR_D/MAC_C11/ComplexMultiply/Product1','user1');
hilite_system('rx_dma_test/LDCR_D/MAC_C11/ComplexMultiply/Product2','user1');
hilite_system('rx_dma_test/LDCR_D/MAC_C11/ComplexMultiply/Product3','user1');
hilite_system('rx_dma_test/LDCR_D/MAC_C11/Conjugate1','user1');
hilite_system('rx_dma_test/LDCR_D/MAC_C11/Delay10','user1');
hilite_system('rx_dma_test/LDCR_D/MAC_C11/Delay9','user1');
hilite_system('rx_dma_test/LDCR_D/MAC_C11/Subsystem1','user1');
hilite_system('rx_dma_test/LDCR_D/MAC_C11/Subsystem1/AND','user1');
hilite_system('rx_dma_test/LDCR_D/MAC_C11/Subsystem1/Add','user1');
hilite_system('rx_dma_test/LDCR_D/MAC_C11/Subsystem1/Add1','user1');
hilite_system('rx_dma_test/LDCR_D/MAC_C11/Subsystem1/Constant1','user1');
hilite_system('rx_dma_test/LDCR_D/MAC_C11/Subsystem1/Data Type Conversion','user1');
hilite_system('rx_dma_test/LDCR_D/MAC_C11/Subsystem1/For Each Subsystem','user1');
hilite_system('rx_dma_test/LDCR_D/MAC_C11/Subsystem1/For Each Subsystem/For Each','user1');
hilite_system('rx_dma_test/LDCR_D/MAC_C11/Subsystem1/For Each Subsystem/Simple Dual Port RAM','user1');
hilite_system('rx_dma_test/LDCR_D/MAC_C11/Subsystem1/HDL Counter1','user1');
hilite_system('rx_dma_test/LDCR_D/MAC_C11/Subsystem1/NOT','user1');
hilite_system('rx_dma_test/LDCR_D/MAC_C11/Subsystem1/Switch','user1');
hilite_system('rx_dma_test/LDCR_D/MAC_C11/Subsystem16','user1');
hilite_system('rx_dma_test/LDCR_D/MAC_C11/Subsystem16/AND','user1');
hilite_system('rx_dma_test/LDCR_D/MAC_C11/Subsystem16/Add','user1');
hilite_system('rx_dma_test/LDCR_D/MAC_C11/Subsystem16/Add1','user1');
hilite_system('rx_dma_test/LDCR_D/MAC_C11/Subsystem16/Constant1','user1');
hilite_system('rx_dma_test/LDCR_D/MAC_C11/Subsystem16/Data Type Conversion','user1');
hilite_system('rx_dma_test/LDCR_D/MAC_C11/Subsystem16/For Each Subsystem','user1');
hilite_system('rx_dma_test/LDCR_D/MAC_C11/Subsystem16/HDL Counter1','user1');
hilite_system('rx_dma_test/LDCR_D/MAC_C11/Subsystem16/NOT','user1');
hilite_system('rx_dma_test/LDCR_D/MAC_C11/Subsystem16/Switch','user1');
hilite_system('rx_dma_test/LDCR_D/DropBits2/Bit Slice1','user1');
hilite_system('rx_dma_test/LDCR_D/DropBits2/Complex to Real-Imag','user1');
hilite_system('rx_dma_test/LDCR_D/DropBits2/Data Type Conversion1','user1');
hilite_system('rx_dma_test/LDCR_D/DropBits2/Data Type Conversion2','user1');
hilite_system('rx_dma_test/LDCR_D/DropBits2/Real-Imag to Complex','user1');
hilite_system('rx_dma_test/LDCR_D/DropBits1/Bit Slice1','user1');
hilite_system('rx_dma_test/LDCR_D/DropBits1/Complex to Real-Imag','user1');
hilite_system('rx_dma_test/LDCR_D/DropBits1/Data Type Conversion1','user1');
hilite_system('rx_dma_test/LDCR_D/DropBits1/Data Type Conversion2','user1');
hilite_system('rx_dma_test/LDCR_D/DropBits1/Real-Imag to Complex','user1');
hilite_system('rx_dma_test/LDCR_D/MAC_C21/ComplexMultiply/Add','user1');
hilite_system('rx_dma_test/LDCR_D/MAC_C21/ComplexMultiply/Add1','user1');
hilite_system('rx_dma_test/LDCR_D/MAC_C21/ComplexMultiply/Complex to Real-Imag','user1');
hilite_system('rx_dma_test/LDCR_D/MAC_C21/ComplexMultiply/Complex to Real-Imag1','user1');
hilite_system('rx_dma_test/LDCR_D/MAC_C21/ComplexMultiply/Delay1','user1');
hilite_system('rx_dma_test/LDCR_D/MAC_C21/ComplexMultiply/Delay2','user1');
hilite_system('rx_dma_test/LDCR_D/MAC_C21/ComplexMultiply/Delay3','user1');
hilite_system('rx_dma_test/LDCR_D/MAC_C21/ComplexMultiply/Delay4','user1');
hilite_system('rx_dma_test/LDCR_D/MAC_C21/ComplexMultiply/Delay5','user1');
hilite_system('rx_dma_test/LDCR_D/MAC_C21/ComplexMultiply/Delay6','user1');
hilite_system('rx_dma_test/LDCR_D/MAC_C21/ComplexMultiply/Delay7','user1');
hilite_system('rx_dma_test/LDCR_D/MAC_C21/ComplexMultiply/Delay8','user1');
hilite_system('rx_dma_test/LDCR_D/MAC_C21/ComplexMultiply/Product','user1');
hilite_system('rx_dma_test/LDCR_D/MAC_C21/ComplexMultiply/Product1','user1');
hilite_system('rx_dma_test/LDCR_D/MAC_C21/ComplexMultiply/Product2','user1');
hilite_system('rx_dma_test/LDCR_D/MAC_C21/ComplexMultiply/Product3','user1');
hilite_system('rx_dma_test/LDCR_D/MAC_C21/Conjugate1','user1');
hilite_system('rx_dma_test/LDCR_D/MAC_C21/Delay10','user1');
hilite_system('rx_dma_test/LDCR_D/MAC_C21/Delay9','user1');
hilite_system('rx_dma_test/LDCR_D/MAC_C21/Subsystem1','user1');
hilite_system('rx_dma_test/LDCR_D/MAC_C21/Subsystem1/AND','user1');
hilite_system('rx_dma_test/LDCR_D/MAC_C21/Subsystem1/Add','user1');
hilite_system('rx_dma_test/LDCR_D/MAC_C21/Subsystem1/Add1','user1');
hilite_system('rx_dma_test/LDCR_D/MAC_C21/Subsystem1/Constant1','user1');
hilite_system('rx_dma_test/LDCR_D/MAC_C21/Subsystem1/Data Type Conversion','user1');
hilite_system('rx_dma_test/LDCR_D/MAC_C21/Subsystem1/For Each Subsystem','user1');
hilite_system('rx_dma_test/LDCR_D/MAC_C21/Subsystem1/HDL Counter1','user1');
hilite_system('rx_dma_test/LDCR_D/MAC_C21/Subsystem1/NOT','user1');
hilite_system('rx_dma_test/LDCR_D/MAC_C21/Subsystem1/Switch','user1');
hilite_system('rx_dma_test/LDCR_D/MAC_C21/Subsystem16','user1');
hilite_system('rx_dma_test/LDCR_D/MAC_C21/Subsystem16/AND','user1');
hilite_system('rx_dma_test/LDCR_D/MAC_C21/Subsystem16/Add','user1');
hilite_system('rx_dma_test/LDCR_D/MAC_C21/Subsystem16/Add1','user1');
hilite_system('rx_dma_test/LDCR_D/MAC_C21/Subsystem16/Constant1','user1');
hilite_system('rx_dma_test/LDCR_D/MAC_C21/Subsystem16/Data Type Conversion','user1');
hilite_system('rx_dma_test/LDCR_D/MAC_C21/Subsystem16/For Each Subsystem','user1');
hilite_system('rx_dma_test/LDCR_D/MAC_C21/Subsystem16/HDL Counter1','user1');
hilite_system('rx_dma_test/LDCR_D/MAC_C21/Subsystem16/NOT','user1');
hilite_system('rx_dma_test/LDCR_D/MAC_C21/Subsystem16/Switch','user1');
hilite_system('rx_dma_test/LDCR_D/FIFOSerializer/Delay3','user1');
hilite_system('rx_dma_test/LDCR_D/FIFOSerializer/Delay4','user1');
hilite_system('rx_dma_test/LDCR_D/FIFOSerializer/Delay5','user1');
hilite_system('rx_dma_test/LDCR_D/FIFOSerializer/For Each Subsystem1','user1');
hilite_system('rx_dma_test/LDCR_D/FIFOSerializer/For Each Subsystem1/AND1','user1');
hilite_system('rx_dma_test/LDCR_D/FIFOSerializer/For Each Subsystem1/Delay','user1');
hilite_system('rx_dma_test/LDCR_D/FIFOSerializer/For Each Subsystem1/Delay6','user1');
hilite_system('rx_dma_test/LDCR_D/FIFOSerializer/For Each Subsystem1/HDL FIFO','user1');
hilite_system('rx_dma_test/LDCR_D/FIFOSerializer/For Each Subsystem1/Relational Operator','user1');
hilite_system('rx_dma_test/LDCR_D/FIFOSerializer/HDL Counter','user1');
hilite_system('rx_dma_test/LDCR_D/FIFOSerializer/HDL Counter1','user1');
hilite_system('rx_dma_test/LDCR_D/FIFOSerializer/Index Vector','user1');
hilite_system('rx_dma_test/LDCR_D/FIFOSerializer/OR','user1');
hilite_system('rx_dma_test/LDCR_D/MAC_C22/ComplexMultiply/Add','user1');
hilite_system('rx_dma_test/LDCR_D/MAC_C22/ComplexMultiply/Add1','user1');
hilite_system('rx_dma_test/LDCR_D/MAC_C22/ComplexMultiply/Complex to Real-Imag','user1');
hilite_system('rx_dma_test/LDCR_D/MAC_C22/ComplexMultiply/Complex to Real-Imag1','user1');
hilite_system('rx_dma_test/LDCR_D/MAC_C22/ComplexMultiply/Delay1','user1');
hilite_system('rx_dma_test/LDCR_D/MAC_C22/ComplexMultiply/Delay2','user1');
hilite_system('rx_dma_test/LDCR_D/MAC_C22/ComplexMultiply/Delay3','user1');
hilite_system('rx_dma_test/LDCR_D/MAC_C22/ComplexMultiply/Delay4','user1');
hilite_system('rx_dma_test/LDCR_D/MAC_C22/ComplexMultiply/Delay5','user1');
hilite_system('rx_dma_test/LDCR_D/MAC_C22/ComplexMultiply/Delay6','user1');
hilite_system('rx_dma_test/LDCR_D/MAC_C22/ComplexMultiply/Delay7','user1');
hilite_system('rx_dma_test/LDCR_D/MAC_C22/ComplexMultiply/Delay8','user1');
hilite_system('rx_dma_test/LDCR_D/MAC_C22/ComplexMultiply/Product','user1');
hilite_system('rx_dma_test/LDCR_D/MAC_C22/ComplexMultiply/Product1','user1');
hilite_system('rx_dma_test/LDCR_D/MAC_C22/ComplexMultiply/Product2','user1');
hilite_system('rx_dma_test/LDCR_D/MAC_C22/ComplexMultiply/Product3','user1');
hilite_system('rx_dma_test/LDCR_D/MAC_C22/Conjugate1','user1');
hilite_system('rx_dma_test/LDCR_D/MAC_C22/Delay10','user1');
hilite_system('rx_dma_test/LDCR_D/MAC_C22/Delay9','user1');
hilite_system('rx_dma_test/LDCR_D/MAC_C22/Subsystem1','user1');
hilite_system('rx_dma_test/LDCR_D/MAC_C22/Subsystem1/AND','user1');
hilite_system('rx_dma_test/LDCR_D/MAC_C22/Subsystem1/Add','user1');
hilite_system('rx_dma_test/LDCR_D/MAC_C22/Subsystem1/Add1','user1');
hilite_system('rx_dma_test/LDCR_D/MAC_C22/Subsystem1/Constant1','user1');
hilite_system('rx_dma_test/LDCR_D/MAC_C22/Subsystem1/Data Type Conversion','user1');
hilite_system('rx_dma_test/LDCR_D/MAC_C22/Subsystem1/For Each Subsystem','user1');
hilite_system('rx_dma_test/LDCR_D/MAC_C22/Subsystem1/HDL Counter1','user1');
hilite_system('rx_dma_test/LDCR_D/MAC_C22/Subsystem1/NOT','user1');
hilite_system('rx_dma_test/LDCR_D/MAC_C22/Subsystem1/Switch','user1');
hilite_system('rx_dma_test/LDCR_D/MAC_C22/Subsystem16','user1');
hilite_system('rx_dma_test/LDCR_D/MAC_C22/Subsystem16/AND','user1');
hilite_system('rx_dma_test/LDCR_D/MAC_C22/Subsystem16/Add','user1');
hilite_system('rx_dma_test/LDCR_D/MAC_C22/Subsystem16/Add1','user1');
hilite_system('rx_dma_test/LDCR_D/MAC_C22/Subsystem16/Constant1','user1');
hilite_system('rx_dma_test/LDCR_D/MAC_C22/Subsystem16/Data Type Conversion','user1');
hilite_system('rx_dma_test/LDCR_D/MAC_C22/Subsystem16/For Each Subsystem','user1');
hilite_system('rx_dma_test/LDCR_D/MAC_C22/Subsystem16/HDL Counter1','user1');
hilite_system('rx_dma_test/LDCR_D/MAC_C22/Subsystem16/NOT','user1');
hilite_system('rx_dma_test/LDCR_D/MAC_C22/Subsystem16/Switch','user1');
