// -------------------------------------------------------------
// 
// File Name: /home/draco/git/adi_dma_testing/iq_dma_example/hdl_ip/hdlsrc/rx_dma_test/rx_dma_test_src_RADIX22FFT_SDF2_2.v
// Created: 2025-08-22 09:27:16
// 
// Generated by MATLAB 24.1, HDL Coder 24.1, and Simulink 24.1
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: rx_dma_test_src_RADIX22FFT_SDF2_2
// Source Path: rx_dma_test/LDCR_D/Channelizer_CH1/FFT/RADIX22FFT_SDF2_2
// Hierarchy Level: 3
// Model version: 9.625
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module rx_dma_test_src_RADIX22FFT_SDF2_2
          (clk,
           reset,
           enb,
           dout_1_1_re,
           dout_1_1_im,
           dout_1_1_vld,
           rd_2_Addr,
           rd_2_Enb,
           proc_2_enb,
           multiply_2_J,
           dout_2_1_re,
           dout_2_1_im,
           dout_2_1_vld,
           dinXTwdl_2_1_vld);


  input   clk;
  input   reset;
  input   enb;
  input   signed [14:0] dout_1_1_re;  // sfix15_En5
  input   signed [14:0] dout_1_1_im;  // sfix15_En5
  input   dout_1_1_vld;
  input   [3:0] rd_2_Addr;  // ufix4
  input   rd_2_Enb;
  input   proc_2_enb;
  input   multiply_2_J;
  output  signed [15:0] dout_2_1_re;  // sfix16_En5
  output  signed [15:0] dout_2_1_im;  // sfix16_En5
  output  dout_2_1_vld;
  output  dinXTwdl_2_1_vld;


  wire signed [15:0] din_re;  // sfix16_En5
  wire signed [15:0] din_im;  // sfix16_En5
  wire btfin_vld;
  wire saveEnb;
  wire dinVld;
  reg  x_vld;
  reg  x_vld_dly;
  wire signed [15:0] wrData_im;  // sfix16_En5
  wire [3:0] wrAddr;  // ufix4
  wire wrEnb;
  wire signed [15:0] x_im;  // sfix16_En5
  reg signed [15:0] x_im_dly;  // sfix16_En5
  wire signed [15:0] wrData_re;  // sfix16_En5
  wire signed [15:0] x_re;  // sfix16_En5
  reg signed [15:0] x_re_dly;  // sfix16_En5
  reg  Radix22ButterflyG2_procEnb_dly;
  reg  Radix22ButterflyG2_procEnb_dly1;
  reg  Radix22ButterflyG2_procEnb_dly2;
  reg signed [16:0] Radix22ButterflyG2_btf1_re_reg;  // sfix17
  reg signed [16:0] Radix22ButterflyG2_btf1_im_reg;  // sfix17
  reg signed [16:0] Radix22ButterflyG2_btf2_re_reg;  // sfix17
  reg signed [16:0] Radix22ButterflyG2_btf2_im_reg;  // sfix17
  reg signed [15:0] Radix22ButterflyG2_din_re_dly;  // sfix16
  reg signed [15:0] Radix22ButterflyG2_din_im_dly;  // sfix16
  reg  Radix22ButterflyG2_din_vld_dly;
  reg signed [15:0] Radix22ButterflyG2_x_re_dly;  // sfix16
  reg signed [15:0] Radix22ButterflyG2_x_im_dly;  // sfix16
  reg  Radix22ButterflyG2_x_vld_dly;
  reg signed [15:0] Radix22ButterflyG2_dinXTwdl_re_dly1;  // sfix16
  reg signed [15:0] Radix22ButterflyG2_dinXTwdl_im_dly1;  // sfix16
  reg signed [15:0] Radix22ButterflyG2_dinXTwdl_re_dly2;  // sfix16
  reg signed [15:0] Radix22ButterflyG2_dinXTwdl_im_dly2;  // sfix16
  reg  Radix22ButterflyG2_multiply_J_dly1;
  reg  Radix22ButterflyG2_procEnb_dly_next;
  reg  Radix22ButterflyG2_procEnb_dly1_next;
  reg  Radix22ButterflyG2_procEnb_dly2_next;
  reg signed [16:0] Radix22ButterflyG2_btf1_re_reg_next;  // sfix17_En5
  reg signed [16:0] Radix22ButterflyG2_btf1_im_reg_next;  // sfix17_En5
  reg signed [16:0] Radix22ButterflyG2_btf2_re_reg_next;  // sfix17_En5
  reg signed [16:0] Radix22ButterflyG2_btf2_im_reg_next;  // sfix17_En5
  reg signed [15:0] Radix22ButterflyG2_din_re_dly_next;  // sfix16_En5
  reg signed [15:0] Radix22ButterflyG2_din_im_dly_next;  // sfix16_En5
  reg  Radix22ButterflyG2_din_vld_dly_next;
  reg signed [15:0] Radix22ButterflyG2_x_re_dly_next;  // sfix16_En5
  reg signed [15:0] Radix22ButterflyG2_x_im_dly_next;  // sfix16_En5
  reg  Radix22ButterflyG2_x_vld_dly_next;
  reg signed [15:0] Radix22ButterflyG2_dinXTwdl_re_dly1_next;  // sfix16_En5
  reg signed [15:0] Radix22ButterflyG2_dinXTwdl_im_dly1_next;  // sfix16_En5
  reg signed [15:0] Radix22ButterflyG2_dinXTwdl_re_dly2_next;  // sfix16_En5
  reg signed [15:0] Radix22ButterflyG2_dinXTwdl_im_dly2_next;  // sfix16_En5
  reg  Radix22ButterflyG2_multiply_J_dly1_next;
  reg signed [15:0] xf_re;  // sfix16_En5
  reg signed [15:0] xf_im;  // sfix16_En5
  reg  xf_vld;
  reg signed [15:0] dinf_re;  // sfix16_En5
  reg signed [15:0] dinf_im;  // sfix16_En5
  reg  dinf_vld;
  reg signed [15:0] btf1_re;  // sfix16_En5
  reg signed [15:0] btf1_im;  // sfix16_En5
  reg signed [15:0] btf2_re;  // sfix16_En5
  reg signed [15:0] btf2_im;  // sfix16_En5
  reg  btfout_vld;
  reg signed [16:0] Radix22ButterflyG2_add_cast;  // sfix17_En5
  reg signed [16:0] Radix22ButterflyG2_add_cast_0;  // sfix17_En5
  reg signed [16:0] Radix22ButterflyG2_add_cast_1;  // sfix17_En5
  reg signed [16:0] Radix22ButterflyG2_add_cast_2;  // sfix17_En5
  reg signed [16:0] Radix22ButterflyG2_sub_cast;  // sfix17_En5
  reg signed [16:0] Radix22ButterflyG2_sub_cast_0;  // sfix17_En5
  reg signed [16:0] Radix22ButterflyG2_sub_cast_1;  // sfix17_En5
  reg signed [16:0] Radix22ButterflyG2_sub_cast_2;  // sfix17_En5
  reg signed [16:0] Radix22ButterflyG2_add_cast_3;  // sfix17_En5
  reg signed [16:0] Radix22ButterflyG2_add_cast_4;  // sfix17_En5
  reg signed [16:0] Radix22ButterflyG2_add_cast_5;  // sfix17_En5
  reg signed [16:0] Radix22ButterflyG2_add_cast_6;  // sfix17_En5
  reg signed [16:0] Radix22ButterflyG2_sub_cast_3;  // sfix17_En5
  reg signed [16:0] Radix22ButterflyG2_sub_cast_4;  // sfix17_En5
  reg signed [16:0] Radix22ButterflyG2_sub_cast_5;  // sfix17_En5
  reg signed [16:0] Radix22ButterflyG2_sub_cast_6;  // sfix17_En5


  assign din_re = {dout_1_1_re[14], dout_1_1_re};



  assign din_im = {dout_1_1_im[14], dout_1_1_im};



  assign btfin_vld = dout_1_1_vld & proc_2_enb;



  assign saveEnb =  ~ btfin_vld;



  assign dinVld = dout_1_1_vld & saveEnb;



  always @(posedge clk)
    begin : intdelay_process
      if (reset == 1'b1) begin
        x_vld <= 1'b0;
      end
      else begin
        if (enb) begin
          x_vld <= rd_2_Enb;
        end
      end
    end



  always @(posedge clk)
    begin : intdelay_1_process
      if (reset == 1'b1) begin
        x_vld_dly <= 1'b0;
      end
      else begin
        if (enb) begin
          x_vld_dly <= x_vld;
        end
      end
    end



  rx_dma_test_src_SimpleDualPortRAM_generic #(.AddrWidth(4),
                                              .DataWidth(16)
                                              )
                                            u_dataMEM_im_0_2 (.clk(clk),
                                                              .enb(enb),
                                                              .wr_din(wrData_im),
                                                              .wr_addr(wrAddr),
                                                              .wr_en(wrEnb),
                                                              .rd_addr(rd_2_Addr),
                                                              .dout(x_im)
                                                              );

  always @(posedge clk)
    begin : intdelay_2_process
      if (reset == 1'b1) begin
        x_im_dly <= 16'sb0000000000000000;
      end
      else begin
        if (enb) begin
          x_im_dly <= x_im;
        end
      end
    end



  rx_dma_test_src_SimpleDualPortRAM_generic #(.AddrWidth(4),
                                              .DataWidth(16)
                                              )
                                            u_dataMEM_re_0_2 (.clk(clk),
                                                              .enb(enb),
                                                              .wr_din(wrData_re),
                                                              .wr_addr(wrAddr),
                                                              .wr_en(wrEnb),
                                                              .rd_addr(rd_2_Addr),
                                                              .dout(x_re)
                                                              );

  always @(posedge clk)
    begin : intdelay_3_process
      if (reset == 1'b1) begin
        x_re_dly <= 16'sb0000000000000000;
      end
      else begin
        if (enb) begin
          x_re_dly <= x_re;
        end
      end
    end



  // Radix22ButterflyG2
  always @(posedge clk)
    begin : Radix22ButterflyG2_process
      if (reset == 1'b1) begin
        Radix22ButterflyG2_procEnb_dly <= 1'b0;
        Radix22ButterflyG2_procEnb_dly1 <= 1'b0;
        Radix22ButterflyG2_procEnb_dly2 <= 1'b0;
        Radix22ButterflyG2_btf1_re_reg <= 17'sb00000000000000000;
        Radix22ButterflyG2_btf1_im_reg <= 17'sb00000000000000000;
        Radix22ButterflyG2_btf2_re_reg <= 17'sb00000000000000000;
        Radix22ButterflyG2_btf2_im_reg <= 17'sb00000000000000000;
        Radix22ButterflyG2_din_re_dly <= 16'sb0000000000000000;
        Radix22ButterflyG2_din_im_dly <= 16'sb0000000000000000;
        Radix22ButterflyG2_din_vld_dly <= 1'b0;
        Radix22ButterflyG2_x_re_dly <= 16'sb0000000000000000;
        Radix22ButterflyG2_x_im_dly <= 16'sb0000000000000000;
        Radix22ButterflyG2_x_vld_dly <= 1'b0;
        Radix22ButterflyG2_dinXTwdl_re_dly1 <= 16'sb0000000000000000;
        Radix22ButterflyG2_dinXTwdl_im_dly1 <= 16'sb0000000000000000;
        Radix22ButterflyG2_dinXTwdl_re_dly2 <= 16'sb0000000000000000;
        Radix22ButterflyG2_dinXTwdl_im_dly2 <= 16'sb0000000000000000;
        Radix22ButterflyG2_multiply_J_dly1 <= 1'b0;
      end
      else begin
        if (enb) begin
          Radix22ButterflyG2_procEnb_dly <= Radix22ButterflyG2_procEnb_dly_next;
          Radix22ButterflyG2_procEnb_dly1 <= Radix22ButterflyG2_procEnb_dly1_next;
          Radix22ButterflyG2_procEnb_dly2 <= Radix22ButterflyG2_procEnb_dly2_next;
          Radix22ButterflyG2_btf1_re_reg <= Radix22ButterflyG2_btf1_re_reg_next;
          Radix22ButterflyG2_btf1_im_reg <= Radix22ButterflyG2_btf1_im_reg_next;
          Radix22ButterflyG2_btf2_re_reg <= Radix22ButterflyG2_btf2_re_reg_next;
          Radix22ButterflyG2_btf2_im_reg <= Radix22ButterflyG2_btf2_im_reg_next;
          Radix22ButterflyG2_din_re_dly <= Radix22ButterflyG2_din_re_dly_next;
          Radix22ButterflyG2_din_im_dly <= Radix22ButterflyG2_din_im_dly_next;
          Radix22ButterflyG2_din_vld_dly <= Radix22ButterflyG2_din_vld_dly_next;
          Radix22ButterflyG2_x_re_dly <= Radix22ButterflyG2_x_re_dly_next;
          Radix22ButterflyG2_x_im_dly <= Radix22ButterflyG2_x_im_dly_next;
          Radix22ButterflyG2_x_vld_dly <= Radix22ButterflyG2_x_vld_dly_next;
          Radix22ButterflyG2_dinXTwdl_re_dly1 <= Radix22ButterflyG2_dinXTwdl_re_dly1_next;
          Radix22ButterflyG2_dinXTwdl_im_dly1 <= Radix22ButterflyG2_dinXTwdl_im_dly1_next;
          Radix22ButterflyG2_dinXTwdl_re_dly2 <= Radix22ButterflyG2_dinXTwdl_re_dly2_next;
          Radix22ButterflyG2_dinXTwdl_im_dly2 <= Radix22ButterflyG2_dinXTwdl_im_dly2_next;
          Radix22ButterflyG2_multiply_J_dly1 <= Radix22ButterflyG2_multiply_J_dly1_next;
        end
      end
    end

  always @(Radix22ButterflyG2_btf1_im_reg, Radix22ButterflyG2_btf1_re_reg,
       Radix22ButterflyG2_btf2_im_reg, Radix22ButterflyG2_btf2_re_reg,
       Radix22ButterflyG2_dinXTwdl_im_dly1, Radix22ButterflyG2_dinXTwdl_im_dly2,
       Radix22ButterflyG2_dinXTwdl_re_dly1, Radix22ButterflyG2_dinXTwdl_re_dly2,
       Radix22ButterflyG2_din_im_dly, Radix22ButterflyG2_din_re_dly,
       Radix22ButterflyG2_din_vld_dly, Radix22ButterflyG2_multiply_J_dly1,
       Radix22ButterflyG2_procEnb_dly, Radix22ButterflyG2_procEnb_dly1,
       Radix22ButterflyG2_procEnb_dly2, Radix22ButterflyG2_x_im_dly,
       Radix22ButterflyG2_x_re_dly, Radix22ButterflyG2_x_vld_dly, btfin_vld,
       dinVld, din_im, din_re, multiply_2_J, x_im_dly, x_re_dly, x_vld_dly) begin
    Radix22ButterflyG2_add_cast_1 = 17'sb00000000000000000;
    Radix22ButterflyG2_add_cast_2 = 17'sb00000000000000000;
    Radix22ButterflyG2_sub_cast_1 = 17'sb00000000000000000;
    Radix22ButterflyG2_sub_cast_2 = 17'sb00000000000000000;
    Radix22ButterflyG2_add_cast_5 = 17'sb00000000000000000;
    Radix22ButterflyG2_add_cast_6 = 17'sb00000000000000000;
    Radix22ButterflyG2_sub_cast_5 = 17'sb00000000000000000;
    Radix22ButterflyG2_sub_cast_6 = 17'sb00000000000000000;
    Radix22ButterflyG2_add_cast = 17'sb00000000000000000;
    Radix22ButterflyG2_add_cast_0 = 17'sb00000000000000000;
    Radix22ButterflyG2_sub_cast = 17'sb00000000000000000;
    Radix22ButterflyG2_sub_cast_0 = 17'sb00000000000000000;
    Radix22ButterflyG2_add_cast_3 = 17'sb00000000000000000;
    Radix22ButterflyG2_add_cast_4 = 17'sb00000000000000000;
    Radix22ButterflyG2_sub_cast_3 = 17'sb00000000000000000;
    Radix22ButterflyG2_sub_cast_4 = 17'sb00000000000000000;
    Radix22ButterflyG2_x_re_dly_next = x_re_dly;
    Radix22ButterflyG2_x_im_dly_next = x_im_dly;
    Radix22ButterflyG2_x_vld_dly_next = x_vld_dly;
    Radix22ButterflyG2_din_re_dly_next = din_re;
    Radix22ButterflyG2_din_im_dly_next = din_im;
    Radix22ButterflyG2_din_vld_dly_next = dinVld;
    Radix22ButterflyG2_procEnb_dly2_next = Radix22ButterflyG2_procEnb_dly1;
    Radix22ButterflyG2_procEnb_dly1_next = Radix22ButterflyG2_procEnb_dly;
    Radix22ButterflyG2_procEnb_dly_next = btfin_vld;
    if (Radix22ButterflyG2_multiply_J_dly1) begin
      Radix22ButterflyG2_add_cast_1 = {x_re_dly[15], x_re_dly};
      Radix22ButterflyG2_add_cast_2 = {Radix22ButterflyG2_dinXTwdl_im_dly2[15], Radix22ButterflyG2_dinXTwdl_im_dly2};
      Radix22ButterflyG2_btf1_re_reg_next = Radix22ButterflyG2_add_cast_1 + Radix22ButterflyG2_add_cast_2;
      Radix22ButterflyG2_sub_cast_1 = {x_re_dly[15], x_re_dly};
      Radix22ButterflyG2_sub_cast_2 = {Radix22ButterflyG2_dinXTwdl_im_dly2[15], Radix22ButterflyG2_dinXTwdl_im_dly2};
      Radix22ButterflyG2_btf2_re_reg_next = Radix22ButterflyG2_sub_cast_1 - Radix22ButterflyG2_sub_cast_2;
      Radix22ButterflyG2_add_cast_5 = {x_im_dly[15], x_im_dly};
      Radix22ButterflyG2_add_cast_6 = {Radix22ButterflyG2_dinXTwdl_re_dly2[15], Radix22ButterflyG2_dinXTwdl_re_dly2};
      Radix22ButterflyG2_btf2_im_reg_next = Radix22ButterflyG2_add_cast_5 + Radix22ButterflyG2_add_cast_6;
      Radix22ButterflyG2_sub_cast_5 = {x_im_dly[15], x_im_dly};
      Radix22ButterflyG2_sub_cast_6 = {Radix22ButterflyG2_dinXTwdl_re_dly2[15], Radix22ButterflyG2_dinXTwdl_re_dly2};
      Radix22ButterflyG2_btf1_im_reg_next = Radix22ButterflyG2_sub_cast_5 - Radix22ButterflyG2_sub_cast_6;
    end
    else begin
      Radix22ButterflyG2_add_cast = {x_re_dly[15], x_re_dly};
      Radix22ButterflyG2_add_cast_0 = {Radix22ButterflyG2_dinXTwdl_re_dly2[15], Radix22ButterflyG2_dinXTwdl_re_dly2};
      Radix22ButterflyG2_btf1_re_reg_next = Radix22ButterflyG2_add_cast + Radix22ButterflyG2_add_cast_0;
      Radix22ButterflyG2_sub_cast = {x_re_dly[15], x_re_dly};
      Radix22ButterflyG2_sub_cast_0 = {Radix22ButterflyG2_dinXTwdl_re_dly2[15], Radix22ButterflyG2_dinXTwdl_re_dly2};
      Radix22ButterflyG2_btf2_re_reg_next = Radix22ButterflyG2_sub_cast - Radix22ButterflyG2_sub_cast_0;
      Radix22ButterflyG2_add_cast_3 = {x_im_dly[15], x_im_dly};
      Radix22ButterflyG2_add_cast_4 = {Radix22ButterflyG2_dinXTwdl_im_dly2[15], Radix22ButterflyG2_dinXTwdl_im_dly2};
      Radix22ButterflyG2_btf1_im_reg_next = Radix22ButterflyG2_add_cast_3 + Radix22ButterflyG2_add_cast_4;
      Radix22ButterflyG2_sub_cast_3 = {x_im_dly[15], x_im_dly};
      Radix22ButterflyG2_sub_cast_4 = {Radix22ButterflyG2_dinXTwdl_im_dly2[15], Radix22ButterflyG2_dinXTwdl_im_dly2};
      Radix22ButterflyG2_btf2_im_reg_next = Radix22ButterflyG2_sub_cast_3 - Radix22ButterflyG2_sub_cast_4;
    end
    Radix22ButterflyG2_dinXTwdl_re_dly2_next = Radix22ButterflyG2_dinXTwdl_re_dly1;
    Radix22ButterflyG2_dinXTwdl_im_dly2_next = Radix22ButterflyG2_dinXTwdl_im_dly1;
    Radix22ButterflyG2_dinXTwdl_re_dly1_next = din_re;
    Radix22ButterflyG2_dinXTwdl_im_dly1_next = din_im;
    Radix22ButterflyG2_multiply_J_dly1_next = multiply_2_J;
    xf_re = Radix22ButterflyG2_x_re_dly;
    xf_im = Radix22ButterflyG2_x_im_dly;
    xf_vld = Radix22ButterflyG2_x_vld_dly;
    dinf_re = Radix22ButterflyG2_din_re_dly;
    dinf_im = Radix22ButterflyG2_din_im_dly;
    dinf_vld = Radix22ButterflyG2_din_vld_dly;
    btf1_re = Radix22ButterflyG2_btf1_re_reg[15:0];
    btf1_im = Radix22ButterflyG2_btf1_im_reg[15:0];
    btf2_re = Radix22ButterflyG2_btf2_re_reg[15:0];
    btf2_im = Radix22ButterflyG2_btf2_im_reg[15:0];
    btfout_vld = Radix22ButterflyG2_procEnb_dly2;
  end



  rx_dma_test_src_SDFCommutator2 u_SDFCOMMUTATOR_2 (.clk(clk),
                                                    .reset(reset),
                                                    .enb(enb),
                                                    .dout_1_1_vld(dout_1_1_vld),
                                                    .xf_re(xf_re),  // sfix16_En5
                                                    .xf_im(xf_im),  // sfix16_En5
                                                    .xf_vld(xf_vld),
                                                    .dinf_re(dinf_re),  // sfix16_En5
                                                    .dinf_im(dinf_im),  // sfix16_En5
                                                    .dinf_vld(dinf_vld),
                                                    .btf1_re(btf1_re),  // sfix16_En5
                                                    .btf1_im(btf1_im),  // sfix16_En5
                                                    .btf2_re(btf2_re),  // sfix16_En5
                                                    .btf2_im(btf2_im),  // sfix16_En5
                                                    .btfout_vld(btfout_vld),
                                                    .wrData_re(wrData_re),  // sfix16_En5
                                                    .wrData_im(wrData_im),  // sfix16_En5
                                                    .wrAddr(wrAddr),  // ufix4
                                                    .wrEnb(wrEnb),
                                                    .dout_2_1_re(dout_2_1_re),  // sfix16_En5
                                                    .dout_2_1_im(dout_2_1_im),  // sfix16_En5
                                                    .dout_2_1_vld(dout_2_1_vld)
                                                    );

  assign dinXTwdl_2_1_vld = btfin_vld;

endmodule  // rx_dma_test_src_RADIX22FFT_SDF2_2

