// -------------------------------------------------------------
// 
// File Name: /home/draco/git/adi_dma_testing/iq_dma_example/hdl_ip/hdlsrc/rx_dma_test/rx_dma_test_src_RADIX22FFT_SDF1_3.v
// Created: 2025-08-22 09:27:16
// 
// Generated by MATLAB 24.1, HDL Coder 24.1, and Simulink 24.1
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: rx_dma_test_src_RADIX22FFT_SDF1_3
// Source Path: rx_dma_test/LDCR_D/Channelizer_CH1/FFT/RADIX22FFT_SDF1_3
// Hierarchy Level: 3
// Model version: 9.625
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module rx_dma_test_src_RADIX22FFT_SDF1_3
          (clk,
           reset,
           enb,
           din_3_1_re_dly,
           din_3_1_im_dly,
           din_3_vld_dly,
           rd_3_Addr,
           rd_3_Enb,
           twdl_3_1_re,
           twdl_3_1_im,
           proc_3_enb,
           softReset,
           dout_3_1_re,
           dout_3_1_im,
           dout_3_1_vld,
           dinXTwdl_3_1_vld);


  input   clk;
  input   reset;
  input   enb;
  input   signed [15:0] din_3_1_re_dly;  // sfix16_En5
  input   signed [15:0] din_3_1_im_dly;  // sfix16_En5
  input   din_3_vld_dly;
  input   [2:0] rd_3_Addr;  // ufix3
  input   rd_3_Enb;
  input   signed [13:0] twdl_3_1_re;  // sfix14_En12
  input   signed [13:0] twdl_3_1_im;  // sfix14_En12
  input   proc_3_enb;
  input   softReset;
  output  signed [16:0] dout_3_1_re;  // sfix17_En5
  output  signed [16:0] dout_3_1_im;  // sfix17_En5
  output  dout_3_1_vld;
  output  dinXTwdl_3_1_vld;


  wire signed [16:0] din_re;  // sfix17_En5
  wire signed [16:0] din_im;  // sfix17_En5
  wire signed [16:0] dinXTwdl_re;  // sfix17_En5
  wire signed [16:0] dinXTwdl_im;  // sfix17_En5
  reg  x_vld;
  wire signed [16:0] wrData_im;  // sfix17_En5
  wire [2:0] wrAddr;  // ufix3
  wire wrEnb;
  wire signed [16:0] x_im;  // sfix17_En5
  wire signed [16:0] wrData_re;  // sfix17_En5
  wire signed [16:0] x_re;  // sfix17_En5
  reg signed [17:0] Radix22ButterflyG1_btf1_re_reg;  // sfix18
  reg signed [17:0] Radix22ButterflyG1_btf1_im_reg;  // sfix18
  reg signed [17:0] Radix22ButterflyG1_btf2_re_reg;  // sfix18
  reg signed [17:0] Radix22ButterflyG1_btf2_im_reg;  // sfix18
  reg signed [16:0] Radix22ButterflyG1_x_re_dly1;  // sfix17
  reg signed [16:0] Radix22ButterflyG1_x_im_dly1;  // sfix17
  reg  Radix22ButterflyG1_x_vld_dly1;
  reg signed [16:0] Radix22ButterflyG1_dinXtwdl_re_dly1;  // sfix17
  reg signed [16:0] Radix22ButterflyG1_dinXtwdl_im_dly1;  // sfix17
  reg signed [16:0] Radix22ButterflyG1_dinXtwdl_re_dly2;  // sfix17
  reg signed [16:0] Radix22ButterflyG1_dinXtwdl_im_dly2;  // sfix17
  reg  Radix22ButterflyG1_dinXtwdl_vld_dly1;
  reg  Radix22ButterflyG1_dinXtwdl_vld_dly2;
  wire signed [17:0] Radix22ButterflyG1_btf1_re_reg_next;  // sfix18_En5
  wire signed [17:0] Radix22ButterflyG1_btf1_im_reg_next;  // sfix18_En5
  wire signed [17:0] Radix22ButterflyG1_btf2_re_reg_next;  // sfix18_En5
  wire signed [17:0] Radix22ButterflyG1_btf2_im_reg_next;  // sfix18_En5
  wire signed [17:0] Radix22ButterflyG1_add_cast;  // sfix18_En5
  wire signed [17:0] Radix22ButterflyG1_add_cast_1;  // sfix18_En5
  wire signed [17:0] Radix22ButterflyG1_sub_cast;  // sfix18_En5
  wire signed [17:0] Radix22ButterflyG1_sub_cast_1;  // sfix18_En5
  wire signed [17:0] Radix22ButterflyG1_add_cast_2;  // sfix18_En5
  wire signed [17:0] Radix22ButterflyG1_add_cast_3;  // sfix18_En5
  wire signed [17:0] Radix22ButterflyG1_sub_cast_2;  // sfix18_En5
  wire signed [17:0] Radix22ButterflyG1_sub_cast_3;  // sfix18_En5
  reg signed [16:0] xf_re;  // sfix17_En5
  reg signed [16:0] xf_im;  // sfix17_En5
  reg  xf_vld;
  wire signed [16:0] dinXTwdlf_re;  // sfix17_En5
  wire signed [16:0] dinXTwdlf_im;  // sfix17_En5
  wire dinxTwdlf_vld;
  wire signed [16:0] btf1_re;  // sfix17_En5
  wire signed [16:0] btf1_im;  // sfix17_En5
  wire signed [16:0] btf2_re;  // sfix17_En5
  wire signed [16:0] btf2_im;  // sfix17_En5
  reg  btf_vld;


  assign din_re = {din_3_1_re_dly[15], din_3_1_re_dly};



  assign din_im = {din_3_1_im_dly[15], din_3_1_im_dly};



  rx_dma_test_src_Complex3Multiply u_MUL3 (.clk(clk),
                                           .reset(reset),
                                           .enb(enb),
                                           .din_re(din_re),  // sfix17_En5
                                           .din_im(din_im),  // sfix17_En5
                                           .din_3_vld_dly(din_3_vld_dly),
                                           .twdl_3_1_re(twdl_3_1_re),  // sfix14_En12
                                           .twdl_3_1_im(twdl_3_1_im),  // sfix14_En12
                                           .softReset(softReset),
                                           .dinXTwdl_re(dinXTwdl_re),  // sfix17_En5
                                           .dinXTwdl_im(dinXTwdl_im),  // sfix17_En5
                                           .dinXTwdl_3_1_vld(dinXTwdl_3_1_vld)
                                           );

  always @(posedge clk)
    begin : intdelay_process
      if (reset == 1'b1) begin
        x_vld <= 1'b0;
      end
      else begin
        if (enb) begin
          x_vld <= rd_3_Enb;
        end
      end
    end



  rx_dma_test_src_SimpleDualPortRAM_generic #(.AddrWidth(3),
                                              .DataWidth(17)
                                              )
                                            u_dataMEM_im_0_3 (.clk(clk),
                                                              .enb(enb),
                                                              .wr_din(wrData_im),
                                                              .wr_addr(wrAddr),
                                                              .wr_en(wrEnb),
                                                              .rd_addr(rd_3_Addr),
                                                              .dout(x_im)
                                                              );

  rx_dma_test_src_SimpleDualPortRAM_generic #(.AddrWidth(3),
                                              .DataWidth(17)
                                              )
                                            u_dataMEM_re_0_3 (.clk(clk),
                                                              .enb(enb),
                                                              .wr_din(wrData_re),
                                                              .wr_addr(wrAddr),
                                                              .wr_en(wrEnb),
                                                              .rd_addr(rd_3_Addr),
                                                              .dout(x_re)
                                                              );

  // Radix22ButterflyG1
  always @(posedge clk)
    begin : Radix22ButterflyG1_process
      if (reset == 1'b1) begin
        Radix22ButterflyG1_btf1_re_reg <= 18'sb000000000000000000;
        Radix22ButterflyG1_btf1_im_reg <= 18'sb000000000000000000;
        Radix22ButterflyG1_btf2_re_reg <= 18'sb000000000000000000;
        Radix22ButterflyG1_btf2_im_reg <= 18'sb000000000000000000;
        Radix22ButterflyG1_x_re_dly1 <= 17'sb00000000000000000;
        Radix22ButterflyG1_x_im_dly1 <= 17'sb00000000000000000;
        Radix22ButterflyG1_x_vld_dly1 <= 1'b0;
        xf_re <= 17'sb00000000000000000;
        xf_im <= 17'sb00000000000000000;
        xf_vld <= 1'b0;
        Radix22ButterflyG1_dinXtwdl_re_dly1 <= 17'sb00000000000000000;
        Radix22ButterflyG1_dinXtwdl_im_dly1 <= 17'sb00000000000000000;
        Radix22ButterflyG1_dinXtwdl_re_dly2 <= 17'sb00000000000000000;
        Radix22ButterflyG1_dinXtwdl_im_dly2 <= 17'sb00000000000000000;
        Radix22ButterflyG1_dinXtwdl_vld_dly1 <= 1'b0;
        Radix22ButterflyG1_dinXtwdl_vld_dly2 <= 1'b0;
        btf_vld <= 1'b0;
      end
      else begin
        if (enb) begin
          Radix22ButterflyG1_btf1_re_reg <= Radix22ButterflyG1_btf1_re_reg_next;
          Radix22ButterflyG1_btf1_im_reg <= Radix22ButterflyG1_btf1_im_reg_next;
          Radix22ButterflyG1_btf2_re_reg <= Radix22ButterflyG1_btf2_re_reg_next;
          Radix22ButterflyG1_btf2_im_reg <= Radix22ButterflyG1_btf2_im_reg_next;
          xf_re <= Radix22ButterflyG1_x_re_dly1;
          xf_im <= Radix22ButterflyG1_x_im_dly1;
          xf_vld <= Radix22ButterflyG1_x_vld_dly1;
          btf_vld <= Radix22ButterflyG1_dinXtwdl_vld_dly2;
          Radix22ButterflyG1_dinXtwdl_vld_dly2 <= Radix22ButterflyG1_dinXtwdl_vld_dly1;
          Radix22ButterflyG1_dinXtwdl_re_dly2 <= Radix22ButterflyG1_dinXtwdl_re_dly1;
          Radix22ButterflyG1_dinXtwdl_im_dly2 <= Radix22ButterflyG1_dinXtwdl_im_dly1;
          Radix22ButterflyG1_dinXtwdl_re_dly1 <= dinXTwdl_re;
          Radix22ButterflyG1_dinXtwdl_im_dly1 <= dinXTwdl_im;
          Radix22ButterflyG1_x_re_dly1 <= x_re;
          Radix22ButterflyG1_x_im_dly1 <= x_im;
          Radix22ButterflyG1_x_vld_dly1 <= x_vld;
          Radix22ButterflyG1_dinXtwdl_vld_dly1 <= proc_3_enb && dinXTwdl_3_1_vld;
        end
      end
    end

  assign dinxTwdlf_vld = ( ! proc_3_enb) && dinXTwdl_3_1_vld;
  assign Radix22ButterflyG1_add_cast = {Radix22ButterflyG1_x_re_dly1[16], Radix22ButterflyG1_x_re_dly1};
  assign Radix22ButterflyG1_add_cast_1 = {Radix22ButterflyG1_dinXtwdl_re_dly2[16], Radix22ButterflyG1_dinXtwdl_re_dly2};
  assign Radix22ButterflyG1_btf1_re_reg_next = Radix22ButterflyG1_add_cast + Radix22ButterflyG1_add_cast_1;
  assign Radix22ButterflyG1_sub_cast = {Radix22ButterflyG1_x_re_dly1[16], Radix22ButterflyG1_x_re_dly1};
  assign Radix22ButterflyG1_sub_cast_1 = {Radix22ButterflyG1_dinXtwdl_re_dly2[16], Radix22ButterflyG1_dinXtwdl_re_dly2};
  assign Radix22ButterflyG1_btf2_re_reg_next = Radix22ButterflyG1_sub_cast - Radix22ButterflyG1_sub_cast_1;
  assign Radix22ButterflyG1_add_cast_2 = {Radix22ButterflyG1_x_im_dly1[16], Radix22ButterflyG1_x_im_dly1};
  assign Radix22ButterflyG1_add_cast_3 = {Radix22ButterflyG1_dinXtwdl_im_dly2[16], Radix22ButterflyG1_dinXtwdl_im_dly2};
  assign Radix22ButterflyG1_btf1_im_reg_next = Radix22ButterflyG1_add_cast_2 + Radix22ButterflyG1_add_cast_3;
  assign Radix22ButterflyG1_sub_cast_2 = {Radix22ButterflyG1_x_im_dly1[16], Radix22ButterflyG1_x_im_dly1};
  assign Radix22ButterflyG1_sub_cast_3 = {Radix22ButterflyG1_dinXtwdl_im_dly2[16], Radix22ButterflyG1_dinXtwdl_im_dly2};
  assign Radix22ButterflyG1_btf2_im_reg_next = Radix22ButterflyG1_sub_cast_2 - Radix22ButterflyG1_sub_cast_3;
  assign dinXTwdlf_re = dinXTwdl_re;
  assign dinXTwdlf_im = dinXTwdl_im;
  assign btf1_re = Radix22ButterflyG1_btf1_re_reg[16:0];
  assign btf1_im = Radix22ButterflyG1_btf1_im_reg[16:0];
  assign btf2_re = Radix22ButterflyG1_btf2_re_reg[16:0];
  assign btf2_im = Radix22ButterflyG1_btf2_im_reg[16:0];



  rx_dma_test_src_SDFCommutator3 u_SDFCOMMUTATOR_3 (.clk(clk),
                                                    .reset(reset),
                                                    .enb(enb),
                                                    .din_3_vld_dly(din_3_vld_dly),
                                                    .xf_re(xf_re),  // sfix17_En5
                                                    .xf_im(xf_im),  // sfix17_En5
                                                    .xf_vld(xf_vld),
                                                    .dinXTwdlf_re(dinXTwdlf_re),  // sfix17_En5
                                                    .dinXTwdlf_im(dinXTwdlf_im),  // sfix17_En5
                                                    .dinxTwdlf_vld(dinxTwdlf_vld),
                                                    .btf1_re(btf1_re),  // sfix17_En5
                                                    .btf1_im(btf1_im),  // sfix17_En5
                                                    .btf2_re(btf2_re),  // sfix17_En5
                                                    .btf2_im(btf2_im),  // sfix17_En5
                                                    .btf_vld(btf_vld),
                                                    .wrData_re(wrData_re),  // sfix17_En5
                                                    .wrData_im(wrData_im),  // sfix17_En5
                                                    .wrAddr(wrAddr),  // ufix3
                                                    .wrEnb(wrEnb),
                                                    .dout_3_1_re(dout_3_1_re),  // sfix17_En5
                                                    .dout_3_1_im(dout_3_1_im),  // sfix17_En5
                                                    .dout_3_1_vld(dout_3_1_vld)
                                                    );

endmodule  // rx_dma_test_src_RADIX22FFT_SDF1_3

