// -------------------------------------------------------------
// 
// File Name: /home/draco/git/adi_dma_testing/iq_dma_example/hdl_ip/hdlsrc/rx_dma_test/rx_dma_test_rdfifo_rid.v
// Created: 2025-08-22 09:27:26
// 
// Generated by MATLAB 24.1, HDL Coder 24.1, and Simulink 24.1
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: rx_dma_test_rdfifo_rid
// Source Path: rx_dma_test/rx_dma_test_axi4/rx_dma_test_axi4_module/rx_dma_test_rdfifo_rid
// Hierarchy Level: 3
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module rx_dma_test_rdfifo_rid
          (clk,
           reset,
           enb,
           In,
           Push,
           Pop,
           Out);


  input   clk;
  input   reset;
  input   enb;
  input   [11:0] In;  // ufix12
  input   Push;  // ufix1
  input   Pop;  // ufix1
  output  [11:0] Out;  // ufix12


  wire R_x;  // ufix1
  wire cache_wr_en;  // ufix1
  wire out_wr_en;  // ufix1
  wire fwft_wr_en;  // ufix1
  wire R_x_1;  // ufix1
  reg  fifo_valid;  // ufix1
  wire Q_keep;  // ufix1
  reg  out_valid;  // ufix1
  wire fifo_and_out_valid;  // ufix1
  wire R_x_2;  // ufix1
  reg  cache_valid;  // ufix1
  wire Q_keep_1;  // ufix1
  wire cache_update;  // ufix1
  wire Q_next;  // ufix1
  wire all_valid;  // ufix1
  wire Full;  // ufix1
  wire fifo_nfull;  // ufix1
  wire fifo_push;  // ufix1
  wire fifo_pop;  // ufix1
  reg [3:0] fifo_front_indx;  // ufix4
  reg [3:0] fifo_front_dir;  // ufix4
  reg [3:0] fifo_back_indx;  // ufix4
  reg [3:0] fifo_back_dir;  // ufix4
  reg [4:0] fifo_sample_count;  // ufix5
  wire [3:0] fifo_front_indx_next;  // ufix4
  wire [3:0] fifo_front_dir_next;  // ufix4
  wire [3:0] fifo_back_indx_next;  // ufix4
  wire [3:0] fifo_back_dir_next;  // ufix4
  wire [4:0] fifo_sample_count_next;  // ufix5
  wire fifo_out3;
  wire fifo_out4;
  wire fifo_write_enable;
  wire fifo_read_enable;
  wire [3:0] fifo_front_indx_temp;  // ufix4
  wire [3:0] fifo_back_indx_temp;  // ufix4
  wire [3:0] w_waddr;  // ufix4
  wire w_we;  // ufix1
  wire [3:0] w_raddr;  // ufix4
  wire Empty;  // ufix1
  wire [4:0] Num;  // ufix5
  wire Q_next_1;  // ufix1
  wire int_valid;  // ufix1
  wire Q_keep_2;  // ufix1
  wire Q_next_2;  // ufix1
  wire fwft_empty;  // ufix1
  wire data_flow;  // ufix1
  wire w_cz;
  wire w_const;  // ufix1
  wire w_mux1;  // ufix1
  reg  w_d1;  // ufix1
  wire [11:0] w_waddr_1;  // ufix12
  reg [11:0] w_d2;  // ufix12
  wire [11:0] w_out;  // ufix12
  reg [11:0] cache_data;  // ufix12
  wire [11:0] data_out_next;  // ufix12
  reg [11:0] Out_1;  // ufix12


  assign R_x =  ~ Pop;



  assign fwft_wr_en = cache_wr_en | out_wr_en;



  assign R_x_1 =  ~ fwft_wr_en;



  assign Q_keep = R_x_1 & fifo_valid;



  assign fifo_and_out_valid = fifo_valid & out_valid;



  assign R_x_2 =  ~ out_wr_en;



  assign Q_keep_1 = R_x_2 & cache_valid;



  assign cache_update = cache_valid == out_wr_en;



  assign cache_wr_en = cache_update & fifo_valid;



  assign Q_next = cache_wr_en | Q_keep_1;



  always @(posedge clk)
    begin : Q_reg_process
      if (reset == 1'b1) begin
        cache_valid <= 1'b0;
      end
      else begin
        if (enb) begin
          cache_valid <= Q_next;
        end
      end
    end



  assign all_valid = cache_valid & fifo_and_out_valid;



  assign fifo_nfull =  ~ Full;



  // us2: Upsample by 1, Sample offset 0 
  assign fifo_push = Push & fifo_nfull;



  // FIFO logic controller
  always @(posedge clk)
    begin : fifo_process
      if (reset == 1'b1) begin
        fifo_front_indx <= 4'b0000;
        fifo_front_dir <= 4'b0001;
        fifo_back_indx <= 4'b0000;
        fifo_back_dir <= 4'b0001;
        fifo_sample_count <= 5'b00000;
      end
      else begin
        if (enb) begin
          fifo_front_indx <= fifo_front_indx_next;
          fifo_front_dir <= fifo_front_dir_next;
          fifo_back_indx <= fifo_back_indx_next;
          fifo_back_dir <= fifo_back_dir_next;
          fifo_sample_count <= fifo_sample_count_next;
        end
      end
    end

  assign fifo_out4 = fifo_sample_count == 5'b10000;
  assign fifo_out3 = fifo_sample_count == 5'b00000;
  assign fifo_write_enable = fifo_push && (fifo_pop || ( ! fifo_out4));
  assign fifo_read_enable = fifo_pop && ( ! fifo_out3);
  assign fifo_front_indx_temp = (fifo_read_enable ? fifo_front_indx + fifo_front_dir :
              fifo_front_indx);
  assign fifo_front_dir_next = (fifo_front_indx_temp == 4'b1111 ? 4'b0001 :
              4'b0001);
  assign fifo_back_indx_temp = (fifo_write_enable ? fifo_back_indx + fifo_back_dir :
              fifo_back_indx);
  assign fifo_back_dir_next = (fifo_back_indx_temp == 4'b1111 ? 4'b0001 :
              4'b0001);
  assign fifo_sample_count_next = (fifo_write_enable && ( ! fifo_read_enable) ? fifo_sample_count + 5'b00001 :
              (( ! fifo_write_enable) && fifo_read_enable ? fifo_sample_count + 5'b11111 :
              fifo_sample_count));
  assign w_waddr = fifo_back_indx;
  assign w_we = fifo_write_enable;
  assign w_raddr = fifo_front_indx;
  assign Empty = fifo_out3;
  assign Full = fifo_out4;
  assign Num = fifo_sample_count;
  assign fifo_front_indx_next = fifo_front_indx_temp;
  assign fifo_back_indx_next = fifo_back_indx_temp;



  // us3: Upsample by 1, Sample offset 0 
  assign fifo_pop =  ~ (Empty | all_valid);



  assign Q_next_1 = fifo_pop | Q_keep;



  always @(posedge clk)
    begin : Q_reg_1_process
      if (reset == 1'b1) begin
        fifo_valid <= 1'b0;
      end
      else begin
        if (enb) begin
          fifo_valid <= Q_next_1;
        end
      end
    end



  assign int_valid = fifo_valid | cache_valid;



  assign Q_keep_2 = R_x & out_valid;



  assign Q_next_2 = out_wr_en | Q_keep_2;



  always @(posedge clk)
    begin : Q_reg_2_process
      if (reset == 1'b1) begin
        out_valid <= 1'b0;
      end
      else begin
        if (enb) begin
          out_valid <= Q_next_2;
        end
      end
    end



  assign fwft_empty =  ~ out_valid;



  assign data_flow = Pop | fwft_empty;



  assign out_wr_en = data_flow & int_valid;



  assign w_cz = Num > 5'b00000;



  assign w_const = 1'b0;



  assign w_mux1 = (w_cz == 1'b0 ? w_const :
              fifo_pop);



  always @(posedge clk)
    begin : f_d1_process
      if (reset == 1'b1) begin
        w_d1 <= 1'b0;
      end
      else begin
        if (enb) begin
          w_d1 <= w_mux1;
        end
      end
    end



  // us1: Upsample by 1, Sample offset 0 
  rx_dma_test_SimpleDualPortRAM_generic #(.AddrWidth(4),
                                          .DataWidth(12)
                                          )
                                        u_rx_dma_test_rdfifo_rid_classic_ram (.clk(clk),
                                                                              .enb(enb),
                                                                              .wr_din(In),
                                                                              .wr_addr(w_waddr),
                                                                              .wr_en(w_we),  // ufix1
                                                                              .rd_addr(w_raddr),
                                                                              .dout(w_waddr_1)
                                                                              );

  always @(posedge clk)
    begin : f_d2_process
      if (reset == 1'b1) begin
        w_d2 <= 12'b000000000000;
      end
      else begin
        if (enb && w_d1) begin
          w_d2 <= w_waddr_1;
        end
      end
    end



  assign w_out = (w_d1 == 1'b0 ? w_d2 :
              w_waddr_1);



  always @(posedge clk)
    begin : cache_data_reg_process
      if (reset == 1'b1) begin
        cache_data <= 12'b000000000000;
      end
      else begin
        if (enb && cache_wr_en) begin
          cache_data <= w_out;
        end
      end
    end



  assign data_out_next = (cache_valid == 1'b0 ? w_out :
              cache_data);



  always @(posedge clk)
    begin : out_data_reg_process
      if (reset == 1'b1) begin
        Out_1 <= 12'b000000000000;
      end
      else begin
        if (enb && out_wr_en) begin
          Out_1 <= data_out_next;
        end
      end
    end



  assign Out = Out_1;

endmodule  // rx_dma_test_rdfifo_rid

