// -------------------------------------------------------------
// 
// File Name: /home/draco/git/adi_dma_testing/iq_dma_example/hdl_ip/hdlsrc/rx_dma_test/rx_dma_test_src_Channelizer_CH1.v
// Created: 2025-08-22 09:27:16
// 
// Generated by MATLAB 24.1, HDL Coder 24.1, and Simulink 24.1
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: rx_dma_test_src_Channelizer_CH1
// Source Path: rx_dma_test/LDCR_D/Channelizer_CH1
// Hierarchy Level: 1
// Model version: 9.625
// 
// HDLChannelizer
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module rx_dma_test_src_Channelizer_CH1
          (clk,
           reset,
           enb,
           dataIn_re,
           dataIn_im,
           validIn,
           startOut,
           endOut);


  input   clk;
  input   reset;
  input   enb;
  input   signed [13:0] dataIn_re;  // sfix14
  input   signed [13:0] dataIn_im;  // sfix14
  input   validIn;
  output  startOut;
  output  endOut;


  wire signed [13:0] filterOut_cmplx_re;  // sfix14_En5
  wire signed [13:0] filterOut_cmplx_im;  // sfix14_En5
  wire filterOut_vld;


  rx_dma_test_src_FilterBank u_FilterBank (.clk(clk),
                                           .reset(reset),
                                           .enb(enb),
                                           .dataIn_re(dataIn_re),  // sfix14
                                           .dataIn_im(dataIn_im),  // sfix14
                                           .validIn(validIn),
                                           .filterOut_cmplx_re(filterOut_cmplx_re),  // sfix14_En5
                                           .filterOut_cmplx_im(filterOut_cmplx_im),  // sfix14_En5
                                           .filterOut_vld(filterOut_vld)
                                           );

  rx_dma_test_src_FFT u_FFT (.clk(clk),
                             .reset(reset),
                             .enb(enb),
                             .filterOut_cmplx_re(filterOut_cmplx_re),  // sfix14_En5
                             .filterOut_cmplx_im(filterOut_cmplx_im),  // sfix14_En5
                             .filterOut_vld(filterOut_vld),
                             .startOut(startOut),
                             .endOut(endOut)
                             );

endmodule  // rx_dma_test_src_Channelizer_CH1

