// -------------------------------------------------------------
// 
// File Name: /home/draco/git/adi_dma_testing/iq_dma_example/hdl_ip/hdlsrc/rx_dma_test/rx_dma_test_reset_sync.v
// Created: 2025-08-22 09:27:26
// 
// Generated by MATLAB 24.1, HDL Coder 24.1, and Simulink 24.1
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: rx_dma_test_reset_sync
// Source Path: rx_dma_test/rx_dma_test_reset_sync
// Hierarchy Level: 1
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module rx_dma_test_reset_sync
          (clk,
           reset_in,
           reset_out);


  input   clk;
  input   reset_in;  // ufix1
  output  reset_out;  // ufix1


  wire enb;
  wire const_0;  // ufix1
  wire const_1;  // ufix1
  reg  reset_pipe;  // ufix1
  reg  reset_out_1;  // ufix1


  assign const_0 = 1'b0;



  assign const_1 = 1'b1;



  assign enb = const_1;

  always @(posedge clk)
    begin : reg_reset_pipe_process
      if (reset_in == 1'b1) begin
        reset_pipe <= 1'b1;
      end
      else begin
        if (enb) begin
          reset_pipe <= const_0;
        end
      end
    end



  always @(posedge clk)
    begin : reg_reset_delay_process
      if (reset_in == 1'b1) begin
        reset_out_1 <= 1'b1;
      end
      else begin
        if (enb) begin
          reset_out_1 <= reset_pipe;
        end
      end
    end



  assign reset_out = reset_out_1;

endmodule  // rx_dma_test_reset_sync

