// -------------------------------------------------------------
// 
// File Name: /home/draco/git/adi_dma_testing/iq_dma_example/hdl_ip/hdlsrc/rx_dma_test/rx_dma_test_dut.v
// Created: 2025-08-22 09:27:26
// 
// Generated by MATLAB 24.1, HDL Coder 24.1, and Simulink 24.1
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: rx_dma_test_dut
// Source Path: rx_dma_test/rx_dma_test_dut
// Hierarchy Level: 1
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module rx_dma_test_dut
          (clk,
           reset,
           dut_enable,
           adc_data_i0,
           adc_valid_i0,
           adc_data_q0,
           adc_valid_q0,
           adc_data_i1,
           adc_valid_i1,
           adc_data_q1,
           adc_valid_q1,
           Accumulations,
           frame_rx_trigger,
           autoTrigger_i,
           frameLen_i,
           idleTime_i,
           ce_out,
           AccumulatorCount,
           ch1_rx_dma_i,
           ch1_rx_dma_q,
           ch2_rx_dma_i,
           ch2_rx_dma_q,
           rx_dma_valid);


  input   clk;
  input   reset;
  input   dut_enable;  // ufix1
  input   signed [15:0] adc_data_i0;  // sfix16
  input   adc_valid_i0;  // ufix1
  input   signed [15:0] adc_data_q0;  // sfix16
  input   adc_valid_q0;  // ufix1
  input   signed [15:0] adc_data_i1;  // sfix16
  input   adc_valid_i1;  // ufix1
  input   signed [15:0] adc_data_q1;  // sfix16
  input   adc_valid_q1;  // ufix1
  input   [31:0] Accumulations;  // ufix32
  input   frame_rx_trigger;  // ufix1
  input   autoTrigger_i;  // ufix1
  input   [15:0] frameLen_i;  // ufix16
  input   signed [23:0] idleTime_i;  // sfix24
  output  ce_out;  // ufix1
  output  [31:0] AccumulatorCount;  // ufix32
  output  [15:0] ch1_rx_dma_i;  // ufix16
  output  [15:0] ch1_rx_dma_q;  // ufix16
  output  [15:0] ch2_rx_dma_i;  // ufix16
  output  [15:0] ch2_rx_dma_q;  // ufix16
  output  rx_dma_valid;  // ufix1


  wire enb;
  wire ce_out_sig;  // ufix1
  wire [31:0] AccumulatorCount_sig;  // ufix32
  wire [15:0] ch1_rx_dma_i_sig;  // ufix16
  wire [15:0] ch1_rx_dma_q_sig;  // ufix16
  wire [15:0] ch2_rx_dma_i_sig;  // ufix16
  wire [15:0] ch2_rx_dma_q_sig;  // ufix16
  wire rx_dma_valid_sig;  // ufix1


  assign enb = dut_enable;

  rx_dma_test_src_LDCR_D u_rx_dma_test_src_LDCR_D (.clk(clk),
                                                   .clk_enable(enb),
                                                   .reset(reset),
                                                   .adc_data_i0(adc_data_i0),  // sfix16
                                                   .adc_valid_i0(adc_valid_i0),  // ufix1
                                                   .adc_data_q0(adc_data_q0),  // sfix16
                                                   .adc_valid_q0(adc_valid_q0),  // ufix1
                                                   .adc_data_i1(adc_data_i1),  // sfix16
                                                   .adc_valid_i1(adc_valid_i1),  // ufix1
                                                   .adc_data_q1(adc_data_q1),  // sfix16
                                                   .adc_valid_q1(adc_valid_q1),  // ufix1
                                                   .Accumulations(Accumulations),  // ufix32
                                                   .frame_rx_trigger(frame_rx_trigger),  // ufix1
                                                   .autoTrigger_i(autoTrigger_i),  // ufix1
                                                   .frameLen_i(frameLen_i),  // ufix16
                                                   .idleTime_i(idleTime_i),  // sfix24
                                                   .ce_out(ce_out_sig),  // ufix1
                                                   .AccumulatorCount(AccumulatorCount_sig),  // ufix32
                                                   .ch1_rx_dma_i(ch1_rx_dma_i_sig),  // ufix16
                                                   .ch1_rx_dma_q(ch1_rx_dma_q_sig),  // ufix16
                                                   .ch2_rx_dma_i(ch2_rx_dma_i_sig),  // ufix16
                                                   .ch2_rx_dma_q(ch2_rx_dma_q_sig),  // ufix16
                                                   .rx_dma_valid(rx_dma_valid_sig)  // ufix1
                                                   );

  assign ce_out = ce_out_sig;

  assign AccumulatorCount = AccumulatorCount_sig;

  assign ch1_rx_dma_i = ch1_rx_dma_i_sig;

  assign ch1_rx_dma_q = ch1_rx_dma_q_sig;

  assign ch2_rx_dma_i = ch2_rx_dma_i_sig;

  assign ch2_rx_dma_q = ch2_rx_dma_q_sig;

  assign rx_dma_valid = rx_dma_valid_sig;

endmodule  // rx_dma_test_dut

