// -------------------------------------------------------------
// 
// File Name: /home/draco/git/adi_dma_testing/iq_dma_example/hdl_ip/hdlsrc/rx_dma_test/rx_dma_test_src_RADIX22FFT_SDF2_6.v
// Created: 2025-08-22 09:27:16
// 
// Generated by MATLAB 24.1, HDL Coder 24.1, and Simulink 24.1
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: rx_dma_test_src_RADIX22FFT_SDF2_6
// Source Path: rx_dma_test/LDCR_D/Channelizer_CH1/FFT/RADIX22FFT_SDF2_6
// Hierarchy Level: 3
// Model version: 9.625
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module rx_dma_test_src_RADIX22FFT_SDF2_6
          (clk,
           reset,
           enb,
           dout_5_1_re,
           dout_5_1_im,
           dout_5_1_vld,
           rd_6_Addr,
           rd_6_Enb,
           proc_6_enb,
           multiply_6_J,
           dout_6_1_re,
           dout_6_1_im,
           dout_6_1_vld,
           dinXTwdl_6_1_vld);


  input   clk;
  input   reset;
  input   enb;
  input   signed [18:0] dout_5_1_re;  // sfix19_En5
  input   signed [18:0] dout_5_1_im;  // sfix19_En5
  input   dout_5_1_vld;
  input   rd_6_Addr;
  input   rd_6_Enb;
  input   proc_6_enb;
  input   multiply_6_J;
  output  signed [19:0] dout_6_1_re;  // sfix20_En5
  output  signed [19:0] dout_6_1_im;  // sfix20_En5
  output  dout_6_1_vld;
  output  dinXTwdl_6_1_vld;


  wire signed [19:0] din_re;  // sfix20_En5
  wire signed [19:0] din_im;  // sfix20_En5
  wire saveEnb;
  wire dinVld;
  reg signed [19:0] din_re_dly1;  // sfix20_En5
  reg signed [19:0] btfin_re;  // sfix20_En5
  reg signed [19:0] din_im_dly1;  // sfix20_En5
  reg signed [19:0] btfin_im;  // sfix20_En5
  wire mulIn_vld;
  reg  procEnb_dly1;
  reg  btfin_vld;
  reg  x_vld;
  reg  x_vld_dly;
  reg signed [19:0] x_im;  // sfix20_En5
  reg signed [19:0] x_im_dly;  // sfix20_En5
  wire signed [19:0] wrData_re;  // sfix20_En5
  wire signed [19:0] wrData_im;  // sfix20_En5
  wire wrAddr;  // ufix1
  wire wrEnb;
  reg signed [19:0] twoLocationReg_0_MEM_re_0;  // sfix20
  reg signed [19:0] twoLocationReg_0_MEM_im_0;  // sfix20
  reg signed [19:0] twoLocationReg_0_MEM_re_1;  // sfix20
  reg signed [19:0] twoLocationReg_0_MEM_im_1;  // sfix20
  reg signed [19:0] twoLocationReg_0_dout_re_reg;  // sfix20
  reg signed [19:0] twoLocationReg_0_dout_im_reg;  // sfix20
  reg signed [19:0] twoLocationReg_0_MEM_re_0_next;  // sfix20_En5
  reg signed [19:0] twoLocationReg_0_MEM_im_0_next;  // sfix20_En5
  reg signed [19:0] twoLocationReg_0_MEM_re_1_next;  // sfix20_En5
  reg signed [19:0] twoLocationReg_0_MEM_im_1_next;  // sfix20_En5
  reg signed [19:0] twoLocationReg_0_dout_re_reg_next;  // sfix20_En5
  reg signed [19:0] twoLocationReg_0_dout_im_reg_next;  // sfix20_En5
  reg signed [19:0] x_re;  // sfix20_En5
  reg signed [19:0] x_re_dly;  // sfix20_En5
  reg  Radix22ButterflyG2_procEnb_dly;
  reg  Radix22ButterflyG2_procEnb_dly1;
  reg  Radix22ButterflyG2_procEnb_dly2;
  reg signed [20:0] Radix22ButterflyG2_btf1_re_reg;  // sfix21
  reg signed [20:0] Radix22ButterflyG2_btf1_im_reg;  // sfix21
  reg signed [20:0] Radix22ButterflyG2_btf2_re_reg;  // sfix21
  reg signed [20:0] Radix22ButterflyG2_btf2_im_reg;  // sfix21
  reg signed [19:0] Radix22ButterflyG2_din_re_dly;  // sfix20
  reg signed [19:0] Radix22ButterflyG2_din_im_dly;  // sfix20
  reg  Radix22ButterflyG2_din_vld_dly;
  reg signed [19:0] Radix22ButterflyG2_x_re_dly;  // sfix20
  reg signed [19:0] Radix22ButterflyG2_x_im_dly;  // sfix20
  reg  Radix22ButterflyG2_x_vld_dly;
  reg signed [19:0] Radix22ButterflyG2_dinXTwdl_re_dly1;  // sfix20
  reg signed [19:0] Radix22ButterflyG2_dinXTwdl_im_dly1;  // sfix20
  reg signed [19:0] Radix22ButterflyG2_dinXTwdl_re_dly2;  // sfix20
  reg signed [19:0] Radix22ButterflyG2_dinXTwdl_im_dly2;  // sfix20
  reg  Radix22ButterflyG2_multiply_J_dly1;
  reg  Radix22ButterflyG2_procEnb_dly_next;
  reg  Radix22ButterflyG2_procEnb_dly1_next;
  reg  Radix22ButterflyG2_procEnb_dly2_next;
  reg signed [20:0] Radix22ButterflyG2_btf1_re_reg_next;  // sfix21_En5
  reg signed [20:0] Radix22ButterflyG2_btf1_im_reg_next;  // sfix21_En5
  reg signed [20:0] Radix22ButterflyG2_btf2_re_reg_next;  // sfix21_En5
  reg signed [20:0] Radix22ButterflyG2_btf2_im_reg_next;  // sfix21_En5
  reg signed [19:0] Radix22ButterflyG2_din_re_dly_next;  // sfix20_En5
  reg signed [19:0] Radix22ButterflyG2_din_im_dly_next;  // sfix20_En5
  reg  Radix22ButterflyG2_din_vld_dly_next;
  reg signed [19:0] Radix22ButterflyG2_x_re_dly_next;  // sfix20_En5
  reg signed [19:0] Radix22ButterflyG2_x_im_dly_next;  // sfix20_En5
  reg  Radix22ButterflyG2_x_vld_dly_next;
  reg signed [19:0] Radix22ButterflyG2_dinXTwdl_re_dly1_next;  // sfix20_En5
  reg signed [19:0] Radix22ButterflyG2_dinXTwdl_im_dly1_next;  // sfix20_En5
  reg signed [19:0] Radix22ButterflyG2_dinXTwdl_re_dly2_next;  // sfix20_En5
  reg signed [19:0] Radix22ButterflyG2_dinXTwdl_im_dly2_next;  // sfix20_En5
  reg  Radix22ButterflyG2_multiply_J_dly1_next;
  reg signed [19:0] xf_re;  // sfix20_En5
  reg signed [19:0] xf_im;  // sfix20_En5
  reg  xf_vld;
  reg signed [19:0] dinf_re;  // sfix20_En5
  reg signed [19:0] dinf_im;  // sfix20_En5
  reg  dinf_vld;
  reg signed [19:0] btf1_re;  // sfix20_En5
  reg signed [19:0] btf1_im;  // sfix20_En5
  reg signed [19:0] btf2_re;  // sfix20_En5
  reg signed [19:0] btf2_im;  // sfix20_En5
  reg  btfout_vld;
  reg signed [20:0] Radix22ButterflyG2_add_cast;  // sfix21_En5
  reg signed [20:0] Radix22ButterflyG2_add_cast_0;  // sfix21_En5
  reg signed [20:0] Radix22ButterflyG2_add_cast_1;  // sfix21_En5
  reg signed [20:0] Radix22ButterflyG2_add_cast_2;  // sfix21_En5
  reg signed [20:0] Radix22ButterflyG2_sub_cast;  // sfix21_En5
  reg signed [20:0] Radix22ButterflyG2_sub_cast_0;  // sfix21_En5
  reg signed [20:0] Radix22ButterflyG2_sub_cast_1;  // sfix21_En5
  reg signed [20:0] Radix22ButterflyG2_sub_cast_2;  // sfix21_En5
  reg signed [20:0] Radix22ButterflyG2_add_cast_3;  // sfix21_En5
  reg signed [20:0] Radix22ButterflyG2_add_cast_4;  // sfix21_En5
  reg signed [20:0] Radix22ButterflyG2_add_cast_5;  // sfix21_En5
  reg signed [20:0] Radix22ButterflyG2_add_cast_6;  // sfix21_En5
  reg signed [20:0] Radix22ButterflyG2_sub_cast_3;  // sfix21_En5
  reg signed [20:0] Radix22ButterflyG2_sub_cast_4;  // sfix21_En5
  reg signed [20:0] Radix22ButterflyG2_sub_cast_5;  // sfix21_En5
  reg signed [20:0] Radix22ButterflyG2_sub_cast_6;  // sfix21_En5


  assign din_re = {dout_5_1_re[18], dout_5_1_re};



  assign din_im = {dout_5_1_im[18], dout_5_1_im};



  assign saveEnb =  ~ proc_6_enb;



  assign dinVld = dout_5_1_vld & saveEnb;



  always @(posedge clk)
    begin : intdelay_process
      if (reset == 1'b1) begin
        din_re_dly1 <= 20'sb00000000000000000000;
      end
      else begin
        if (enb) begin
          din_re_dly1 <= din_re;
        end
      end
    end



  always @(posedge clk)
    begin : intdelay_1_process
      if (reset == 1'b1) begin
        btfin_re <= 20'sb00000000000000000000;
      end
      else begin
        if (enb) begin
          btfin_re <= din_re_dly1;
        end
      end
    end



  always @(posedge clk)
    begin : intdelay_2_process
      if (reset == 1'b1) begin
        din_im_dly1 <= 20'sb00000000000000000000;
      end
      else begin
        if (enb) begin
          din_im_dly1 <= din_im;
        end
      end
    end



  always @(posedge clk)
    begin : intdelay_3_process
      if (reset == 1'b1) begin
        btfin_im <= 20'sb00000000000000000000;
      end
      else begin
        if (enb) begin
          btfin_im <= din_im_dly1;
        end
      end
    end



  assign mulIn_vld = dout_5_1_vld & proc_6_enb;



  always @(posedge clk)
    begin : intdelay_4_process
      if (reset == 1'b1) begin
        procEnb_dly1 <= 1'b0;
      end
      else begin
        if (enb) begin
          procEnb_dly1 <= mulIn_vld;
        end
      end
    end



  always @(posedge clk)
    begin : intdelay_5_process
      if (reset == 1'b1) begin
        btfin_vld <= 1'b0;
      end
      else begin
        if (enb) begin
          btfin_vld <= procEnb_dly1;
        end
      end
    end



  always @(posedge clk)
    begin : intdelay_6_process
      if (reset == 1'b1) begin
        x_vld <= 1'b0;
      end
      else begin
        if (enb) begin
          x_vld <= rd_6_Enb;
        end
      end
    end



  always @(posedge clk)
    begin : intdelay_7_process
      if (reset == 1'b1) begin
        x_vld_dly <= 1'b0;
      end
      else begin
        if (enb) begin
          x_vld_dly <= x_vld;
        end
      end
    end



  always @(posedge clk)
    begin : intdelay_8_process
      if (reset == 1'b1) begin
        x_im_dly <= 20'sb00000000000000000000;
      end
      else begin
        if (enb) begin
          x_im_dly <= x_im;
        end
      end
    end



  // twoLocationReg_0
  always @(posedge clk)
    begin : twoLocationReg_0_process
      if (reset == 1'b1) begin
        twoLocationReg_0_MEM_re_0 <= 20'sb00000000000000000000;
        twoLocationReg_0_MEM_im_0 <= 20'sb00000000000000000000;
        twoLocationReg_0_MEM_re_1 <= 20'sb00000000000000000000;
        twoLocationReg_0_MEM_im_1 <= 20'sb00000000000000000000;
        twoLocationReg_0_dout_re_reg <= 20'sb00000000000000000000;
        twoLocationReg_0_dout_im_reg <= 20'sb00000000000000000000;
      end
      else begin
        if (enb) begin
          twoLocationReg_0_MEM_re_0 <= twoLocationReg_0_MEM_re_0_next;
          twoLocationReg_0_MEM_im_0 <= twoLocationReg_0_MEM_im_0_next;
          twoLocationReg_0_MEM_re_1 <= twoLocationReg_0_MEM_re_1_next;
          twoLocationReg_0_MEM_im_1 <= twoLocationReg_0_MEM_im_1_next;
          twoLocationReg_0_dout_re_reg <= twoLocationReg_0_dout_re_reg_next;
          twoLocationReg_0_dout_im_reg <= twoLocationReg_0_dout_im_reg_next;
        end
      end
    end

  always @(rd_6_Addr, twoLocationReg_0_MEM_im_0, twoLocationReg_0_MEM_im_1,
       twoLocationReg_0_MEM_re_0, twoLocationReg_0_MEM_re_1,
       twoLocationReg_0_dout_im_reg, twoLocationReg_0_dout_re_reg, wrAddr,
       wrData_im, wrData_re, wrEnb) begin
    twoLocationReg_0_MEM_re_0_next = twoLocationReg_0_MEM_re_0;
    twoLocationReg_0_MEM_im_0_next = twoLocationReg_0_MEM_im_0;
    twoLocationReg_0_MEM_re_1_next = twoLocationReg_0_MEM_re_1;
    twoLocationReg_0_MEM_im_1_next = twoLocationReg_0_MEM_im_1;
    if (rd_6_Addr) begin
      twoLocationReg_0_dout_re_reg_next = twoLocationReg_0_MEM_re_1;
      twoLocationReg_0_dout_im_reg_next = twoLocationReg_0_MEM_im_1;
    end
    else begin
      twoLocationReg_0_dout_re_reg_next = twoLocationReg_0_MEM_re_0;
      twoLocationReg_0_dout_im_reg_next = twoLocationReg_0_MEM_im_0;
    end
    if (wrEnb) begin
      if (wrAddr == 1'b1) begin
        twoLocationReg_0_MEM_re_1_next = wrData_re;
        twoLocationReg_0_MEM_im_1_next = wrData_im;
      end
      else begin
        twoLocationReg_0_MEM_re_0_next = wrData_re;
        twoLocationReg_0_MEM_im_0_next = wrData_im;
      end
    end
    x_re = twoLocationReg_0_dout_re_reg;
    x_im = twoLocationReg_0_dout_im_reg;
  end



  always @(posedge clk)
    begin : intdelay_9_process
      if (reset == 1'b1) begin
        x_re_dly <= 20'sb00000000000000000000;
      end
      else begin
        if (enb) begin
          x_re_dly <= x_re;
        end
      end
    end



  // Radix22ButterflyG2
  always @(posedge clk)
    begin : Radix22ButterflyG2_process
      if (reset == 1'b1) begin
        Radix22ButterflyG2_procEnb_dly <= 1'b0;
        Radix22ButterflyG2_procEnb_dly1 <= 1'b0;
        Radix22ButterflyG2_procEnb_dly2 <= 1'b0;
        Radix22ButterflyG2_btf1_re_reg <= 21'sb000000000000000000000;
        Radix22ButterflyG2_btf1_im_reg <= 21'sb000000000000000000000;
        Radix22ButterflyG2_btf2_re_reg <= 21'sb000000000000000000000;
        Radix22ButterflyG2_btf2_im_reg <= 21'sb000000000000000000000;
        Radix22ButterflyG2_din_re_dly <= 20'sb00000000000000000000;
        Radix22ButterflyG2_din_im_dly <= 20'sb00000000000000000000;
        Radix22ButterflyG2_din_vld_dly <= 1'b0;
        Radix22ButterflyG2_x_re_dly <= 20'sb00000000000000000000;
        Radix22ButterflyG2_x_im_dly <= 20'sb00000000000000000000;
        Radix22ButterflyG2_x_vld_dly <= 1'b0;
        Radix22ButterflyG2_dinXTwdl_re_dly1 <= 20'sb00000000000000000000;
        Radix22ButterflyG2_dinXTwdl_im_dly1 <= 20'sb00000000000000000000;
        Radix22ButterflyG2_dinXTwdl_re_dly2 <= 20'sb00000000000000000000;
        Radix22ButterflyG2_dinXTwdl_im_dly2 <= 20'sb00000000000000000000;
        Radix22ButterflyG2_multiply_J_dly1 <= 1'b0;
      end
      else begin
        if (enb) begin
          Radix22ButterflyG2_procEnb_dly <= Radix22ButterflyG2_procEnb_dly_next;
          Radix22ButterflyG2_procEnb_dly1 <= Radix22ButterflyG2_procEnb_dly1_next;
          Radix22ButterflyG2_procEnb_dly2 <= Radix22ButterflyG2_procEnb_dly2_next;
          Radix22ButterflyG2_btf1_re_reg <= Radix22ButterflyG2_btf1_re_reg_next;
          Radix22ButterflyG2_btf1_im_reg <= Radix22ButterflyG2_btf1_im_reg_next;
          Radix22ButterflyG2_btf2_re_reg <= Radix22ButterflyG2_btf2_re_reg_next;
          Radix22ButterflyG2_btf2_im_reg <= Radix22ButterflyG2_btf2_im_reg_next;
          Radix22ButterflyG2_din_re_dly <= Radix22ButterflyG2_din_re_dly_next;
          Radix22ButterflyG2_din_im_dly <= Radix22ButterflyG2_din_im_dly_next;
          Radix22ButterflyG2_din_vld_dly <= Radix22ButterflyG2_din_vld_dly_next;
          Radix22ButterflyG2_x_re_dly <= Radix22ButterflyG2_x_re_dly_next;
          Radix22ButterflyG2_x_im_dly <= Radix22ButterflyG2_x_im_dly_next;
          Radix22ButterflyG2_x_vld_dly <= Radix22ButterflyG2_x_vld_dly_next;
          Radix22ButterflyG2_dinXTwdl_re_dly1 <= Radix22ButterflyG2_dinXTwdl_re_dly1_next;
          Radix22ButterflyG2_dinXTwdl_im_dly1 <= Radix22ButterflyG2_dinXTwdl_im_dly1_next;
          Radix22ButterflyG2_dinXTwdl_re_dly2 <= Radix22ButterflyG2_dinXTwdl_re_dly2_next;
          Radix22ButterflyG2_dinXTwdl_im_dly2 <= Radix22ButterflyG2_dinXTwdl_im_dly2_next;
          Radix22ButterflyG2_multiply_J_dly1 <= Radix22ButterflyG2_multiply_J_dly1_next;
        end
      end
    end

  always @(Radix22ButterflyG2_btf1_im_reg, Radix22ButterflyG2_btf1_re_reg,
       Radix22ButterflyG2_btf2_im_reg, Radix22ButterflyG2_btf2_re_reg,
       Radix22ButterflyG2_dinXTwdl_im_dly1, Radix22ButterflyG2_dinXTwdl_im_dly2,
       Radix22ButterflyG2_dinXTwdl_re_dly1, Radix22ButterflyG2_dinXTwdl_re_dly2,
       Radix22ButterflyG2_din_im_dly, Radix22ButterflyG2_din_re_dly,
       Radix22ButterflyG2_din_vld_dly, Radix22ButterflyG2_multiply_J_dly1,
       Radix22ButterflyG2_procEnb_dly, Radix22ButterflyG2_procEnb_dly1,
       Radix22ButterflyG2_procEnb_dly2, Radix22ButterflyG2_x_im_dly,
       Radix22ButterflyG2_x_re_dly, Radix22ButterflyG2_x_vld_dly, btfin_im,
       btfin_re, btfin_vld, dinVld, din_im, din_re, multiply_6_J, x_im_dly,
       x_re_dly, x_vld_dly) begin
    Radix22ButterflyG2_add_cast_1 = 21'sb000000000000000000000;
    Radix22ButterflyG2_add_cast_2 = 21'sb000000000000000000000;
    Radix22ButterflyG2_sub_cast_1 = 21'sb000000000000000000000;
    Radix22ButterflyG2_sub_cast_2 = 21'sb000000000000000000000;
    Radix22ButterflyG2_add_cast_5 = 21'sb000000000000000000000;
    Radix22ButterflyG2_add_cast_6 = 21'sb000000000000000000000;
    Radix22ButterflyG2_sub_cast_5 = 21'sb000000000000000000000;
    Radix22ButterflyG2_sub_cast_6 = 21'sb000000000000000000000;
    Radix22ButterflyG2_add_cast = 21'sb000000000000000000000;
    Radix22ButterflyG2_add_cast_0 = 21'sb000000000000000000000;
    Radix22ButterflyG2_sub_cast = 21'sb000000000000000000000;
    Radix22ButterflyG2_sub_cast_0 = 21'sb000000000000000000000;
    Radix22ButterflyG2_add_cast_3 = 21'sb000000000000000000000;
    Radix22ButterflyG2_add_cast_4 = 21'sb000000000000000000000;
    Radix22ButterflyG2_sub_cast_3 = 21'sb000000000000000000000;
    Radix22ButterflyG2_sub_cast_4 = 21'sb000000000000000000000;
    Radix22ButterflyG2_x_re_dly_next = x_re_dly;
    Radix22ButterflyG2_x_im_dly_next = x_im_dly;
    Radix22ButterflyG2_x_vld_dly_next = x_vld_dly;
    Radix22ButterflyG2_din_re_dly_next = din_re;
    Radix22ButterflyG2_din_im_dly_next = din_im;
    Radix22ButterflyG2_din_vld_dly_next = dinVld;
    Radix22ButterflyG2_procEnb_dly2_next = Radix22ButterflyG2_procEnb_dly1;
    Radix22ButterflyG2_procEnb_dly1_next = Radix22ButterflyG2_procEnb_dly;
    Radix22ButterflyG2_procEnb_dly_next = btfin_vld;
    if (Radix22ButterflyG2_multiply_J_dly1) begin
      Radix22ButterflyG2_add_cast_1 = {x_re_dly[19], x_re_dly};
      Radix22ButterflyG2_add_cast_2 = {Radix22ButterflyG2_dinXTwdl_im_dly2[19], Radix22ButterflyG2_dinXTwdl_im_dly2};
      Radix22ButterflyG2_btf1_re_reg_next = Radix22ButterflyG2_add_cast_1 + Radix22ButterflyG2_add_cast_2;
      Radix22ButterflyG2_sub_cast_1 = {x_re_dly[19], x_re_dly};
      Radix22ButterflyG2_sub_cast_2 = {Radix22ButterflyG2_dinXTwdl_im_dly2[19], Radix22ButterflyG2_dinXTwdl_im_dly2};
      Radix22ButterflyG2_btf2_re_reg_next = Radix22ButterflyG2_sub_cast_1 - Radix22ButterflyG2_sub_cast_2;
      Radix22ButterflyG2_add_cast_5 = {x_im_dly[19], x_im_dly};
      Radix22ButterflyG2_add_cast_6 = {Radix22ButterflyG2_dinXTwdl_re_dly2[19], Radix22ButterflyG2_dinXTwdl_re_dly2};
      Radix22ButterflyG2_btf2_im_reg_next = Radix22ButterflyG2_add_cast_5 + Radix22ButterflyG2_add_cast_6;
      Radix22ButterflyG2_sub_cast_5 = {x_im_dly[19], x_im_dly};
      Radix22ButterflyG2_sub_cast_6 = {Radix22ButterflyG2_dinXTwdl_re_dly2[19], Radix22ButterflyG2_dinXTwdl_re_dly2};
      Radix22ButterflyG2_btf1_im_reg_next = Radix22ButterflyG2_sub_cast_5 - Radix22ButterflyG2_sub_cast_6;
    end
    else begin
      Radix22ButterflyG2_add_cast = {x_re_dly[19], x_re_dly};
      Radix22ButterflyG2_add_cast_0 = {Radix22ButterflyG2_dinXTwdl_re_dly2[19], Radix22ButterflyG2_dinXTwdl_re_dly2};
      Radix22ButterflyG2_btf1_re_reg_next = Radix22ButterflyG2_add_cast + Radix22ButterflyG2_add_cast_0;
      Radix22ButterflyG2_sub_cast = {x_re_dly[19], x_re_dly};
      Radix22ButterflyG2_sub_cast_0 = {Radix22ButterflyG2_dinXTwdl_re_dly2[19], Radix22ButterflyG2_dinXTwdl_re_dly2};
      Radix22ButterflyG2_btf2_re_reg_next = Radix22ButterflyG2_sub_cast - Radix22ButterflyG2_sub_cast_0;
      Radix22ButterflyG2_add_cast_3 = {x_im_dly[19], x_im_dly};
      Radix22ButterflyG2_add_cast_4 = {Radix22ButterflyG2_dinXTwdl_im_dly2[19], Radix22ButterflyG2_dinXTwdl_im_dly2};
      Radix22ButterflyG2_btf1_im_reg_next = Radix22ButterflyG2_add_cast_3 + Radix22ButterflyG2_add_cast_4;
      Radix22ButterflyG2_sub_cast_3 = {x_im_dly[19], x_im_dly};
      Radix22ButterflyG2_sub_cast_4 = {Radix22ButterflyG2_dinXTwdl_im_dly2[19], Radix22ButterflyG2_dinXTwdl_im_dly2};
      Radix22ButterflyG2_btf2_im_reg_next = Radix22ButterflyG2_sub_cast_3 - Radix22ButterflyG2_sub_cast_4;
    end
    Radix22ButterflyG2_dinXTwdl_re_dly2_next = Radix22ButterflyG2_dinXTwdl_re_dly1;
    Radix22ButterflyG2_dinXTwdl_im_dly2_next = Radix22ButterflyG2_dinXTwdl_im_dly1;
    Radix22ButterflyG2_dinXTwdl_re_dly1_next = btfin_re;
    Radix22ButterflyG2_dinXTwdl_im_dly1_next = btfin_im;
    Radix22ButterflyG2_multiply_J_dly1_next = multiply_6_J;
    xf_re = Radix22ButterflyG2_x_re_dly;
    xf_im = Radix22ButterflyG2_x_im_dly;
    xf_vld = Radix22ButterflyG2_x_vld_dly;
    dinf_re = Radix22ButterflyG2_din_re_dly;
    dinf_im = Radix22ButterflyG2_din_im_dly;
    dinf_vld = Radix22ButterflyG2_din_vld_dly;
    btf1_re = Radix22ButterflyG2_btf1_re_reg[19:0];
    btf1_im = Radix22ButterflyG2_btf1_im_reg[19:0];
    btf2_re = Radix22ButterflyG2_btf2_re_reg[19:0];
    btf2_im = Radix22ButterflyG2_btf2_im_reg[19:0];
    btfout_vld = Radix22ButterflyG2_procEnb_dly2;
  end



  rx_dma_test_src_SDFCommutator6 u_SDFCOMMUTATOR_6 (.clk(clk),
                                                    .reset(reset),
                                                    .enb(enb),
                                                    .dout_5_1_vld(dout_5_1_vld),
                                                    .xf_re(xf_re),  // sfix20_En5
                                                    .xf_im(xf_im),  // sfix20_En5
                                                    .xf_vld(xf_vld),
                                                    .dinf_re(dinf_re),  // sfix20_En5
                                                    .dinf_im(dinf_im),  // sfix20_En5
                                                    .dinf_vld(dinf_vld),
                                                    .btf1_re(btf1_re),  // sfix20_En5
                                                    .btf1_im(btf1_im),  // sfix20_En5
                                                    .btf2_re(btf2_re),  // sfix20_En5
                                                    .btf2_im(btf2_im),  // sfix20_En5
                                                    .btfout_vld(btfout_vld),
                                                    .wrData_re(wrData_re),  // sfix20_En5
                                                    .wrData_im(wrData_im),  // sfix20_En5
                                                    .wrAddr(wrAddr),  // ufix1
                                                    .wrEnb(wrEnb),
                                                    .dout_6_1_re(dout_6_1_re),  // sfix20_En5
                                                    .dout_6_1_im(dout_6_1_im),  // sfix20_En5
                                                    .dout_6_1_vld(dout_6_1_vld)
                                                    );

  assign dinXTwdl_6_1_vld = btfin_vld;

endmodule  // rx_dma_test_src_RADIX22FFT_SDF2_6

