add_files -fileset sim_1 -norecurse /home/draco/git/adi_dma_testing/iq_dma_example/hdl_ip/hdlsrc/rx_dma_test/rx_dma_test_src_Subsystem.v
add_files -fileset sim_1 -norecurse /home/draco/git/adi_dma_testing/iq_dma_example/hdl_ip/hdlsrc/rx_dma_test/rx_dma_test_src_frameCtrl.v
add_files -fileset sim_1 -norecurse /home/draco/git/adi_dma_testing/iq_dma_example/hdl_ip/hdlsrc/rx_dma_test/rx_dma_test_src_counter_subsystem.v
add_files -fileset sim_1 -norecurse /home/draco/git/adi_dma_testing/iq_dma_example/hdl_ip/hdlsrc/rx_dma_test/rx_dma_test_src_FilterCoef.v
add_files -fileset sim_1 -norecurse /home/draco/git/adi_dma_testing/iq_dma_example/hdl_ip/hdlsrc/rx_dma_test/rx_dma_test_src_FilterTapSystolicWvldin.v
add_files -fileset sim_1 -norecurse /home/draco/git/adi_dma_testing/iq_dma_example/hdl_ip/hdlsrc/rx_dma_test/rx_dma_test_src_subFilter.v
add_files -fileset sim_1 -norecurse /home/draco/git/adi_dma_testing/iq_dma_example/hdl_ip/hdlsrc/rx_dma_test/rx_dma_test_src_FilterBank.v
add_files -fileset sim_1 -norecurse /home/draco/git/adi_dma_testing/iq_dma_example/hdl_ip/hdlsrc/rx_dma_test/rx_dma_test_src_SimpleDualPortRAM_generic.v
add_files -fileset sim_1 -norecurse /home/draco/git/adi_dma_testing/iq_dma_example/hdl_ip/hdlsrc/rx_dma_test/rx_dma_test_src_SDFCommutator1.v
add_files -fileset sim_1 -norecurse /home/draco/git/adi_dma_testing/iq_dma_example/hdl_ip/hdlsrc/rx_dma_test/rx_dma_test_src_RADIX22FFT_SDF1_1.v
add_files -fileset sim_1 -norecurse /home/draco/git/adi_dma_testing/iq_dma_example/hdl_ip/hdlsrc/rx_dma_test/rx_dma_test_src_RADIX22FFT_CTRL1_1.v
add_files -fileset sim_1 -norecurse /home/draco/git/adi_dma_testing/iq_dma_example/hdl_ip/hdlsrc/rx_dma_test/rx_dma_test_src_SDFCommutator2.v
add_files -fileset sim_1 -norecurse /home/draco/git/adi_dma_testing/iq_dma_example/hdl_ip/hdlsrc/rx_dma_test/rx_dma_test_src_RADIX22FFT_SDF2_2.v
add_files -fileset sim_1 -norecurse /home/draco/git/adi_dma_testing/iq_dma_example/hdl_ip/hdlsrc/rx_dma_test/rx_dma_test_src_RADIX22FFT_CTRL1_2.v
add_files -fileset sim_1 -norecurse /home/draco/git/adi_dma_testing/iq_dma_example/hdl_ip/hdlsrc/rx_dma_test/rx_dma_test_src_TWDLROM_3_1.v
add_files -fileset sim_1 -norecurse /home/draco/git/adi_dma_testing/iq_dma_example/hdl_ip/hdlsrc/rx_dma_test/rx_dma_test_src_Complex3Multiply.v
add_files -fileset sim_1 -norecurse /home/draco/git/adi_dma_testing/iq_dma_example/hdl_ip/hdlsrc/rx_dma_test/rx_dma_test_src_SDFCommutator3.v
add_files -fileset sim_1 -norecurse /home/draco/git/adi_dma_testing/iq_dma_example/hdl_ip/hdlsrc/rx_dma_test/rx_dma_test_src_RADIX22FFT_SDF1_3.v
add_files -fileset sim_1 -norecurse /home/draco/git/adi_dma_testing/iq_dma_example/hdl_ip/hdlsrc/rx_dma_test/rx_dma_test_src_RADIX22FFT_CTRL1_3.v
add_files -fileset sim_1 -norecurse /home/draco/git/adi_dma_testing/iq_dma_example/hdl_ip/hdlsrc/rx_dma_test/rx_dma_test_src_SDFCommutator4.v
add_files -fileset sim_1 -norecurse /home/draco/git/adi_dma_testing/iq_dma_example/hdl_ip/hdlsrc/rx_dma_test/rx_dma_test_src_RADIX22FFT_SDF2_4.v
add_files -fileset sim_1 -norecurse /home/draco/git/adi_dma_testing/iq_dma_example/hdl_ip/hdlsrc/rx_dma_test/rx_dma_test_src_RADIX22FFT_CTRL1_4.v
add_files -fileset sim_1 -norecurse /home/draco/git/adi_dma_testing/iq_dma_example/hdl_ip/hdlsrc/rx_dma_test/rx_dma_test_src_TWDLROM_5_1.v
add_files -fileset sim_1 -norecurse /home/draco/git/adi_dma_testing/iq_dma_example/hdl_ip/hdlsrc/rx_dma_test/rx_dma_test_src_Complex3Multiply_block.v
add_files -fileset sim_1 -norecurse /home/draco/git/adi_dma_testing/iq_dma_example/hdl_ip/hdlsrc/rx_dma_test/rx_dma_test_src_SDFCommutator5.v
add_files -fileset sim_1 -norecurse /home/draco/git/adi_dma_testing/iq_dma_example/hdl_ip/hdlsrc/rx_dma_test/rx_dma_test_src_RADIX22FFT_SDF1_5.v
add_files -fileset sim_1 -norecurse /home/draco/git/adi_dma_testing/iq_dma_example/hdl_ip/hdlsrc/rx_dma_test/rx_dma_test_src_RADIX22FFT_CTRL1_5.v
add_files -fileset sim_1 -norecurse /home/draco/git/adi_dma_testing/iq_dma_example/hdl_ip/hdlsrc/rx_dma_test/rx_dma_test_src_SDFCommutator6.v
add_files -fileset sim_1 -norecurse /home/draco/git/adi_dma_testing/iq_dma_example/hdl_ip/hdlsrc/rx_dma_test/rx_dma_test_src_RADIX22FFT_SDF2_6.v
add_files -fileset sim_1 -norecurse /home/draco/git/adi_dma_testing/iq_dma_example/hdl_ip/hdlsrc/rx_dma_test/rx_dma_test_src_RADIX22FFT_CTRL1_6.v
add_files -fileset sim_1 -norecurse /home/draco/git/adi_dma_testing/iq_dma_example/hdl_ip/hdlsrc/rx_dma_test/rx_dma_test_src_RADIX2FFT_bitNatural.v
add_files -fileset sim_1 -norecurse /home/draco/git/adi_dma_testing/iq_dma_example/hdl_ip/hdlsrc/rx_dma_test/rx_dma_test_src_FFT.v
add_files -fileset sim_1 -norecurse /home/draco/git/adi_dma_testing/iq_dma_example/hdl_ip/hdlsrc/rx_dma_test/rx_dma_test_src_Channelizer_CH1.v
add_files -fileset sim_1 -norecurse /home/draco/git/adi_dma_testing/iq_dma_example/hdl_ip/hdlsrc/rx_dma_test/rx_dma_test_src_LDCR_D.v
