// -------------------------------------------------------------
// 
// File Name: /home/draco/git/adi_dma_testing/iq_dma_example/hdl_ip/hdlsrc/rx_dma_test/rx_dma_test_src_Subsystem.v
// Created: 2025-08-21 13:52:00
// 
// Generated by MATLAB 24.1, HDL Coder 24.1, and Simulink 24.1
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: rx_dma_test_src_Subsystem
// Source Path: rx_dma_test/LDCR_D/Subsystem
// Hierarchy Level: 1
// Model version: 9.535
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module rx_dma_test_src_Subsystem
          (clk,
           reset,
           enb,
           In1,
           enb_1,
           In3,
           count);


  input   clk;
  input   reset;
  input   enb;
  input   In1;
  input   enb_1;
  input   [31:0] In3;  // uint32
  output  [31:0] count;  // uint32


  reg  Delay15_out1;
  wire [31:0] count_step;  // uint32
  wire [31:0] count_reset;  // uint32
  reg [31:0] HDL_Counter1_out1;  // uint32
  wire [31:0] count_1;  // uint32
  wire [31:0] count_2;  // uint32
  wire Relational_Operator_out1;
  wire AND_out1;
  wire [31:0] count_3;  // uint32


  always @(posedge clk)
    begin : Delay15_process
      if (reset == 1'b1) begin
        Delay15_out1 <= 1'b0;
      end
      else begin
        if (enb) begin
          Delay15_out1 <= In1;
        end
      end
    end


  // Free running, Unsigned Counter
  //  initial value   = 0
  //  step value      = 1
  assign count_step = 32'b00000000000000000000000000000001;


  assign count_reset = 32'b00000000000000000000000000000000;


  assign count_1 = HDL_Counter1_out1 + count_step;


  assign count_2 = (enb_1 == 1'b0 ? HDL_Counter1_out1 :
              count_1);


  assign Relational_Operator_out1 = In3 < HDL_Counter1_out1;


  assign AND_out1 = Relational_Operator_out1 & Delay15_out1;


  assign count_3 = (AND_out1 == 1'b0 ? count_2 :
              count_reset);


  always @(posedge clk)
    begin : HDL_Counter1_process
      if (reset == 1'b1) begin
        HDL_Counter1_out1 <= 32'b00000000000000000000000000000000;
      end
      else begin
        if (enb) begin
          HDL_Counter1_out1 <= count_3;
        end
      end
    end


  assign count = HDL_Counter1_out1;

endmodule  // rx_dma_test_src_Subsystem

