create_project prj_ip {} -part xc7z030ifbg676-2L -force
set_property ip_repo_paths {../../} [current_fileset]

# Add HDL source files to project
add_files -norecurse {../hdl/rx_dma_test_src_Subsystem.v}
add_files -norecurse {../hdl/rx_dma_test_src_counter_subsystem.v}
add_files -norecurse {../hdl/rx_dma_test_src_FilterCoef.v}
add_files -norecurse {../hdl/rx_dma_test_src_FilterTapSystolicWvldin.v}
add_files -norecurse {../hdl/rx_dma_test_src_subFilter.v}
add_files -norecurse {../hdl/rx_dma_test_src_FilterBank.v}
add_files -norecurse {../hdl/rx_dma_test_src_SimpleDualPortRAM_generic.v}
add_files -norecurse {../hdl/rx_dma_test_src_SDFCommutator1.v}
add_files -norecurse {../hdl/rx_dma_test_src_RADIX22FFT_SDF1_1.v}
add_files -norecurse {../hdl/rx_dma_test_src_RADIX22FFT_CTRL1_1.v}
add_files -norecurse {../hdl/rx_dma_test_src_SDFCommutator2.v}
add_files -norecurse {../hdl/rx_dma_test_src_RADIX22FFT_SDF2_2.v}
add_files -norecurse {../hdl/rx_dma_test_src_RADIX22FFT_CTRL1_2.v}
add_files -norecurse {../hdl/rx_dma_test_src_TWDLROM_3_1.v}
add_files -norecurse {../hdl/rx_dma_test_src_Complex3Multiply.v}
add_files -norecurse {../hdl/rx_dma_test_src_SDFCommutator3.v}
add_files -norecurse {../hdl/rx_dma_test_src_RADIX22FFT_SDF1_3.v}
add_files -norecurse {../hdl/rx_dma_test_src_RADIX22FFT_CTRL1_3.v}
add_files -norecurse {../hdl/rx_dma_test_src_SDFCommutator4.v}
add_files -norecurse {../hdl/rx_dma_test_src_RADIX22FFT_SDF2_4.v}
add_files -norecurse {../hdl/rx_dma_test_src_RADIX22FFT_CTRL1_4.v}
add_files -norecurse {../hdl/rx_dma_test_src_TWDLROM_5_1.v}
add_files -norecurse {../hdl/rx_dma_test_src_Complex3Multiply_block.v}
add_files -norecurse {../hdl/rx_dma_test_src_SDFCommutator5.v}
add_files -norecurse {../hdl/rx_dma_test_src_RADIX22FFT_SDF1_5.v}
add_files -norecurse {../hdl/rx_dma_test_src_RADIX22FFT_CTRL1_5.v}
add_files -norecurse {../hdl/rx_dma_test_src_SDFCommutator6.v}
add_files -norecurse {../hdl/rx_dma_test_src_RADIX22FFT_SDF2_6.v}
add_files -norecurse {../hdl/rx_dma_test_src_RADIX22FFT_CTRL1_6.v}
add_files -norecurse {../hdl/rx_dma_test_src_RADIX2FFT_bitNatural.v}
add_files -norecurse {../hdl/rx_dma_test_src_FFT.v}
add_files -norecurse {../hdl/rx_dma_test_src_Channelizer_CH1.v}
add_files -norecurse {../hdl/rx_dma_test_src_LDCR_D.v}
add_files -norecurse {../hdl/rx_dma_test_reset_sync.v}
add_files -norecurse {../hdl/rx_dma_test_dut.v}
add_files -norecurse {../hdl/rx_dma_test_addr_decoder.v}
add_files -norecurse {../hdl/rx_dma_test_SimpleDualPortRAM_generic.v}
add_files -norecurse {../hdl/rx_dma_test_rdfifo_data.v}
add_files -norecurse {../hdl/rx_dma_test_SimpleDualPortRAM_singlebit.v}
add_files -norecurse {../hdl/rx_dma_test_rdfifo_last.v}
add_files -norecurse {../hdl/rx_dma_test_rdfifo_rid.v}
add_files -norecurse {../hdl/rx_dma_test_axi4_module.v}
add_files -norecurse {../hdl/rx_dma_test_axi4.v}
add_files -norecurse {../hdl/rx_dma_test.v}
set_property top rx_dma_test [get_filesets sources_1]
set_property top rx_dma_test [get_filesets sim_1]
update_compile_order -fileset sources_1
update_compile_order -fileset sim_1

# Package IP from project
ipx::package_project -root_dir {../} -force

# Set IP properties
set_property name rx_dma_test [ipx::current_core]
set_property display_name rx_dma_test [ipx::current_core]
set_property version {1.0} [ipx::current_core]
set_property library {ip} [ipx::current_core]
set Families [split [lsort -uniq [get_property C_FAMILY [get_parts]]]]
set IPSupportedFamily {}
foreach family $Families {append IPSupportedFamily "{$family} {Production} "}
set_property supported_families $IPSupportedFamily [ipx::current_core]
set_property taxonomy {{/HDL Coder Generated IP}} [ipx::current_core]
set_property description {HDL Coder generated IP} [ipx::current_core]
set_property core_revision 2114225512 [ipx::current_core]

# Add HDL source files to IP
ipx::add_file {hdl/rx_dma_test_src_Subsystem.v} [ipx::get_file_groups xilinx_anylanguagesynthesis -of_objects [ipx::current_core]]
set_property type {{verilogSource}} [ipx::get_files {hdl/rx_dma_test_src_Subsystem.v} -of_objects [ipx::get_file_groups xilinx_anylanguagesynthesis -of_objects [ipx::current_core]]]
ipx::add_file {hdl/rx_dma_test_src_Subsystem.v} [ipx::get_file_groups xilinx_anylanguagebehavioralsimulation -of_objects [ipx::current_core]]
set_property type {{verilogSource}} [ipx::get_files {hdl/rx_dma_test_src_Subsystem.v} -of_objects [ipx::get_file_groups xilinx_anylanguagebehavioralsimulation -of_objects [ipx::current_core]]]
ipx::add_file {hdl/rx_dma_test_src_counter_subsystem.v} [ipx::get_file_groups xilinx_anylanguagesynthesis -of_objects [ipx::current_core]]
set_property type {{verilogSource}} [ipx::get_files {hdl/rx_dma_test_src_counter_subsystem.v} -of_objects [ipx::get_file_groups xilinx_anylanguagesynthesis -of_objects [ipx::current_core]]]
ipx::add_file {hdl/rx_dma_test_src_counter_subsystem.v} [ipx::get_file_groups xilinx_anylanguagebehavioralsimulation -of_objects [ipx::current_core]]
set_property type {{verilogSource}} [ipx::get_files {hdl/rx_dma_test_src_counter_subsystem.v} -of_objects [ipx::get_file_groups xilinx_anylanguagebehavioralsimulation -of_objects [ipx::current_core]]]
ipx::add_file {hdl/rx_dma_test_src_FilterCoef.v} [ipx::get_file_groups xilinx_anylanguagesynthesis -of_objects [ipx::current_core]]
set_property type {{verilogSource}} [ipx::get_files {hdl/rx_dma_test_src_FilterCoef.v} -of_objects [ipx::get_file_groups xilinx_anylanguagesynthesis -of_objects [ipx::current_core]]]
ipx::add_file {hdl/rx_dma_test_src_FilterCoef.v} [ipx::get_file_groups xilinx_anylanguagebehavioralsimulation -of_objects [ipx::current_core]]
set_property type {{verilogSource}} [ipx::get_files {hdl/rx_dma_test_src_FilterCoef.v} -of_objects [ipx::get_file_groups xilinx_anylanguagebehavioralsimulation -of_objects [ipx::current_core]]]
ipx::add_file {hdl/rx_dma_test_src_FilterTapSystolicWvldin.v} [ipx::get_file_groups xilinx_anylanguagesynthesis -of_objects [ipx::current_core]]
set_property type {{verilogSource}} [ipx::get_files {hdl/rx_dma_test_src_FilterTapSystolicWvldin.v} -of_objects [ipx::get_file_groups xilinx_anylanguagesynthesis -of_objects [ipx::current_core]]]
ipx::add_file {hdl/rx_dma_test_src_FilterTapSystolicWvldin.v} [ipx::get_file_groups xilinx_anylanguagebehavioralsimulation -of_objects [ipx::current_core]]
set_property type {{verilogSource}} [ipx::get_files {hdl/rx_dma_test_src_FilterTapSystolicWvldin.v} -of_objects [ipx::get_file_groups xilinx_anylanguagebehavioralsimulation -of_objects [ipx::current_core]]]
ipx::add_file {hdl/rx_dma_test_src_subFilter.v} [ipx::get_file_groups xilinx_anylanguagesynthesis -of_objects [ipx::current_core]]
set_property type {{verilogSource}} [ipx::get_files {hdl/rx_dma_test_src_subFilter.v} -of_objects [ipx::get_file_groups xilinx_anylanguagesynthesis -of_objects [ipx::current_core]]]
ipx::add_file {hdl/rx_dma_test_src_subFilter.v} [ipx::get_file_groups xilinx_anylanguagebehavioralsimulation -of_objects [ipx::current_core]]
set_property type {{verilogSource}} [ipx::get_files {hdl/rx_dma_test_src_subFilter.v} -of_objects [ipx::get_file_groups xilinx_anylanguagebehavioralsimulation -of_objects [ipx::current_core]]]
ipx::add_file {hdl/rx_dma_test_src_FilterBank.v} [ipx::get_file_groups xilinx_anylanguagesynthesis -of_objects [ipx::current_core]]
set_property type {{verilogSource}} [ipx::get_files {hdl/rx_dma_test_src_FilterBank.v} -of_objects [ipx::get_file_groups xilinx_anylanguagesynthesis -of_objects [ipx::current_core]]]
ipx::add_file {hdl/rx_dma_test_src_FilterBank.v} [ipx::get_file_groups xilinx_anylanguagebehavioralsimulation -of_objects [ipx::current_core]]
set_property type {{verilogSource}} [ipx::get_files {hdl/rx_dma_test_src_FilterBank.v} -of_objects [ipx::get_file_groups xilinx_anylanguagebehavioralsimulation -of_objects [ipx::current_core]]]
ipx::add_file {hdl/rx_dma_test_src_SimpleDualPortRAM_generic.v} [ipx::get_file_groups xilinx_anylanguagesynthesis -of_objects [ipx::current_core]]
set_property type {{verilogSource}} [ipx::get_files {hdl/rx_dma_test_src_SimpleDualPortRAM_generic.v} -of_objects [ipx::get_file_groups xilinx_anylanguagesynthesis -of_objects [ipx::current_core]]]
ipx::add_file {hdl/rx_dma_test_src_SimpleDualPortRAM_generic.v} [ipx::get_file_groups xilinx_anylanguagebehavioralsimulation -of_objects [ipx::current_core]]
set_property type {{verilogSource}} [ipx::get_files {hdl/rx_dma_test_src_SimpleDualPortRAM_generic.v} -of_objects [ipx::get_file_groups xilinx_anylanguagebehavioralsimulation -of_objects [ipx::current_core]]]
ipx::add_file {hdl/rx_dma_test_src_SDFCommutator1.v} [ipx::get_file_groups xilinx_anylanguagesynthesis -of_objects [ipx::current_core]]
set_property type {{verilogSource}} [ipx::get_files {hdl/rx_dma_test_src_SDFCommutator1.v} -of_objects [ipx::get_file_groups xilinx_anylanguagesynthesis -of_objects [ipx::current_core]]]
ipx::add_file {hdl/rx_dma_test_src_SDFCommutator1.v} [ipx::get_file_groups xilinx_anylanguagebehavioralsimulation -of_objects [ipx::current_core]]
set_property type {{verilogSource}} [ipx::get_files {hdl/rx_dma_test_src_SDFCommutator1.v} -of_objects [ipx::get_file_groups xilinx_anylanguagebehavioralsimulation -of_objects [ipx::current_core]]]
ipx::add_file {hdl/rx_dma_test_src_RADIX22FFT_SDF1_1.v} [ipx::get_file_groups xilinx_anylanguagesynthesis -of_objects [ipx::current_core]]
set_property type {{verilogSource}} [ipx::get_files {hdl/rx_dma_test_src_RADIX22FFT_SDF1_1.v} -of_objects [ipx::get_file_groups xilinx_anylanguagesynthesis -of_objects [ipx::current_core]]]
ipx::add_file {hdl/rx_dma_test_src_RADIX22FFT_SDF1_1.v} [ipx::get_file_groups xilinx_anylanguagebehavioralsimulation -of_objects [ipx::current_core]]
set_property type {{verilogSource}} [ipx::get_files {hdl/rx_dma_test_src_RADIX22FFT_SDF1_1.v} -of_objects [ipx::get_file_groups xilinx_anylanguagebehavioralsimulation -of_objects [ipx::current_core]]]
ipx::add_file {hdl/rx_dma_test_src_RADIX22FFT_CTRL1_1.v} [ipx::get_file_groups xilinx_anylanguagesynthesis -of_objects [ipx::current_core]]
set_property type {{verilogSource}} [ipx::get_files {hdl/rx_dma_test_src_RADIX22FFT_CTRL1_1.v} -of_objects [ipx::get_file_groups xilinx_anylanguagesynthesis -of_objects [ipx::current_core]]]
ipx::add_file {hdl/rx_dma_test_src_RADIX22FFT_CTRL1_1.v} [ipx::get_file_groups xilinx_anylanguagebehavioralsimulation -of_objects [ipx::current_core]]
set_property type {{verilogSource}} [ipx::get_files {hdl/rx_dma_test_src_RADIX22FFT_CTRL1_1.v} -of_objects [ipx::get_file_groups xilinx_anylanguagebehavioralsimulation -of_objects [ipx::current_core]]]
ipx::add_file {hdl/rx_dma_test_src_SDFCommutator2.v} [ipx::get_file_groups xilinx_anylanguagesynthesis -of_objects [ipx::current_core]]
set_property type {{verilogSource}} [ipx::get_files {hdl/rx_dma_test_src_SDFCommutator2.v} -of_objects [ipx::get_file_groups xilinx_anylanguagesynthesis -of_objects [ipx::current_core]]]
ipx::add_file {hdl/rx_dma_test_src_SDFCommutator2.v} [ipx::get_file_groups xilinx_anylanguagebehavioralsimulation -of_objects [ipx::current_core]]
set_property type {{verilogSource}} [ipx::get_files {hdl/rx_dma_test_src_SDFCommutator2.v} -of_objects [ipx::get_file_groups xilinx_anylanguagebehavioralsimulation -of_objects [ipx::current_core]]]
ipx::add_file {hdl/rx_dma_test_src_RADIX22FFT_SDF2_2.v} [ipx::get_file_groups xilinx_anylanguagesynthesis -of_objects [ipx::current_core]]
set_property type {{verilogSource}} [ipx::get_files {hdl/rx_dma_test_src_RADIX22FFT_SDF2_2.v} -of_objects [ipx::get_file_groups xilinx_anylanguagesynthesis -of_objects [ipx::current_core]]]
ipx::add_file {hdl/rx_dma_test_src_RADIX22FFT_SDF2_2.v} [ipx::get_file_groups xilinx_anylanguagebehavioralsimulation -of_objects [ipx::current_core]]
set_property type {{verilogSource}} [ipx::get_files {hdl/rx_dma_test_src_RADIX22FFT_SDF2_2.v} -of_objects [ipx::get_file_groups xilinx_anylanguagebehavioralsimulation -of_objects [ipx::current_core]]]
ipx::add_file {hdl/rx_dma_test_src_RADIX22FFT_CTRL1_2.v} [ipx::get_file_groups xilinx_anylanguagesynthesis -of_objects [ipx::current_core]]
set_property type {{verilogSource}} [ipx::get_files {hdl/rx_dma_test_src_RADIX22FFT_CTRL1_2.v} -of_objects [ipx::get_file_groups xilinx_anylanguagesynthesis -of_objects [ipx::current_core]]]
ipx::add_file {hdl/rx_dma_test_src_RADIX22FFT_CTRL1_2.v} [ipx::get_file_groups xilinx_anylanguagebehavioralsimulation -of_objects [ipx::current_core]]
set_property type {{verilogSource}} [ipx::get_files {hdl/rx_dma_test_src_RADIX22FFT_CTRL1_2.v} -of_objects [ipx::get_file_groups xilinx_anylanguagebehavioralsimulation -of_objects [ipx::current_core]]]
ipx::add_file {hdl/rx_dma_test_src_TWDLROM_3_1.v} [ipx::get_file_groups xilinx_anylanguagesynthesis -of_objects [ipx::current_core]]
set_property type {{verilogSource}} [ipx::get_files {hdl/rx_dma_test_src_TWDLROM_3_1.v} -of_objects [ipx::get_file_groups xilinx_anylanguagesynthesis -of_objects [ipx::current_core]]]
ipx::add_file {hdl/rx_dma_test_src_TWDLROM_3_1.v} [ipx::get_file_groups xilinx_anylanguagebehavioralsimulation -of_objects [ipx::current_core]]
set_property type {{verilogSource}} [ipx::get_files {hdl/rx_dma_test_src_TWDLROM_3_1.v} -of_objects [ipx::get_file_groups xilinx_anylanguagebehavioralsimulation -of_objects [ipx::current_core]]]
ipx::add_file {hdl/rx_dma_test_src_Complex3Multiply.v} [ipx::get_file_groups xilinx_anylanguagesynthesis -of_objects [ipx::current_core]]
set_property type {{verilogSource}} [ipx::get_files {hdl/rx_dma_test_src_Complex3Multiply.v} -of_objects [ipx::get_file_groups xilinx_anylanguagesynthesis -of_objects [ipx::current_core]]]
ipx::add_file {hdl/rx_dma_test_src_Complex3Multiply.v} [ipx::get_file_groups xilinx_anylanguagebehavioralsimulation -of_objects [ipx::current_core]]
set_property type {{verilogSource}} [ipx::get_files {hdl/rx_dma_test_src_Complex3Multiply.v} -of_objects [ipx::get_file_groups xilinx_anylanguagebehavioralsimulation -of_objects [ipx::current_core]]]
ipx::add_file {hdl/rx_dma_test_src_SDFCommutator3.v} [ipx::get_file_groups xilinx_anylanguagesynthesis -of_objects [ipx::current_core]]
set_property type {{verilogSource}} [ipx::get_files {hdl/rx_dma_test_src_SDFCommutator3.v} -of_objects [ipx::get_file_groups xilinx_anylanguagesynthesis -of_objects [ipx::current_core]]]
ipx::add_file {hdl/rx_dma_test_src_SDFCommutator3.v} [ipx::get_file_groups xilinx_anylanguagebehavioralsimulation -of_objects [ipx::current_core]]
set_property type {{verilogSource}} [ipx::get_files {hdl/rx_dma_test_src_SDFCommutator3.v} -of_objects [ipx::get_file_groups xilinx_anylanguagebehavioralsimulation -of_objects [ipx::current_core]]]
ipx::add_file {hdl/rx_dma_test_src_RADIX22FFT_SDF1_3.v} [ipx::get_file_groups xilinx_anylanguagesynthesis -of_objects [ipx::current_core]]
set_property type {{verilogSource}} [ipx::get_files {hdl/rx_dma_test_src_RADIX22FFT_SDF1_3.v} -of_objects [ipx::get_file_groups xilinx_anylanguagesynthesis -of_objects [ipx::current_core]]]
ipx::add_file {hdl/rx_dma_test_src_RADIX22FFT_SDF1_3.v} [ipx::get_file_groups xilinx_anylanguagebehavioralsimulation -of_objects [ipx::current_core]]
set_property type {{verilogSource}} [ipx::get_files {hdl/rx_dma_test_src_RADIX22FFT_SDF1_3.v} -of_objects [ipx::get_file_groups xilinx_anylanguagebehavioralsimulation -of_objects [ipx::current_core]]]
ipx::add_file {hdl/rx_dma_test_src_RADIX22FFT_CTRL1_3.v} [ipx::get_file_groups xilinx_anylanguagesynthesis -of_objects [ipx::current_core]]
set_property type {{verilogSource}} [ipx::get_files {hdl/rx_dma_test_src_RADIX22FFT_CTRL1_3.v} -of_objects [ipx::get_file_groups xilinx_anylanguagesynthesis -of_objects [ipx::current_core]]]
ipx::add_file {hdl/rx_dma_test_src_RADIX22FFT_CTRL1_3.v} [ipx::get_file_groups xilinx_anylanguagebehavioralsimulation -of_objects [ipx::current_core]]
set_property type {{verilogSource}} [ipx::get_files {hdl/rx_dma_test_src_RADIX22FFT_CTRL1_3.v} -of_objects [ipx::get_file_groups xilinx_anylanguagebehavioralsimulation -of_objects [ipx::current_core]]]
ipx::add_file {hdl/rx_dma_test_src_SDFCommutator4.v} [ipx::get_file_groups xilinx_anylanguagesynthesis -of_objects [ipx::current_core]]
set_property type {{verilogSource}} [ipx::get_files {hdl/rx_dma_test_src_SDFCommutator4.v} -of_objects [ipx::get_file_groups xilinx_anylanguagesynthesis -of_objects [ipx::current_core]]]
ipx::add_file {hdl/rx_dma_test_src_SDFCommutator4.v} [ipx::get_file_groups xilinx_anylanguagebehavioralsimulation -of_objects [ipx::current_core]]
set_property type {{verilogSource}} [ipx::get_files {hdl/rx_dma_test_src_SDFCommutator4.v} -of_objects [ipx::get_file_groups xilinx_anylanguagebehavioralsimulation -of_objects [ipx::current_core]]]
ipx::add_file {hdl/rx_dma_test_src_RADIX22FFT_SDF2_4.v} [ipx::get_file_groups xilinx_anylanguagesynthesis -of_objects [ipx::current_core]]
set_property type {{verilogSource}} [ipx::get_files {hdl/rx_dma_test_src_RADIX22FFT_SDF2_4.v} -of_objects [ipx::get_file_groups xilinx_anylanguagesynthesis -of_objects [ipx::current_core]]]
ipx::add_file {hdl/rx_dma_test_src_RADIX22FFT_SDF2_4.v} [ipx::get_file_groups xilinx_anylanguagebehavioralsimulation -of_objects [ipx::current_core]]
set_property type {{verilogSource}} [ipx::get_files {hdl/rx_dma_test_src_RADIX22FFT_SDF2_4.v} -of_objects [ipx::get_file_groups xilinx_anylanguagebehavioralsimulation -of_objects [ipx::current_core]]]
ipx::add_file {hdl/rx_dma_test_src_RADIX22FFT_CTRL1_4.v} [ipx::get_file_groups xilinx_anylanguagesynthesis -of_objects [ipx::current_core]]
set_property type {{verilogSource}} [ipx::get_files {hdl/rx_dma_test_src_RADIX22FFT_CTRL1_4.v} -of_objects [ipx::get_file_groups xilinx_anylanguagesynthesis -of_objects [ipx::current_core]]]
ipx::add_file {hdl/rx_dma_test_src_RADIX22FFT_CTRL1_4.v} [ipx::get_file_groups xilinx_anylanguagebehavioralsimulation -of_objects [ipx::current_core]]
set_property type {{verilogSource}} [ipx::get_files {hdl/rx_dma_test_src_RADIX22FFT_CTRL1_4.v} -of_objects [ipx::get_file_groups xilinx_anylanguagebehavioralsimulation -of_objects [ipx::current_core]]]
ipx::add_file {hdl/rx_dma_test_src_TWDLROM_5_1.v} [ipx::get_file_groups xilinx_anylanguagesynthesis -of_objects [ipx::current_core]]
set_property type {{verilogSource}} [ipx::get_files {hdl/rx_dma_test_src_TWDLROM_5_1.v} -of_objects [ipx::get_file_groups xilinx_anylanguagesynthesis -of_objects [ipx::current_core]]]
ipx::add_file {hdl/rx_dma_test_src_TWDLROM_5_1.v} [ipx::get_file_groups xilinx_anylanguagebehavioralsimulation -of_objects [ipx::current_core]]
set_property type {{verilogSource}} [ipx::get_files {hdl/rx_dma_test_src_TWDLROM_5_1.v} -of_objects [ipx::get_file_groups xilinx_anylanguagebehavioralsimulation -of_objects [ipx::current_core]]]
ipx::add_file {hdl/rx_dma_test_src_Complex3Multiply_block.v} [ipx::get_file_groups xilinx_anylanguagesynthesis -of_objects [ipx::current_core]]
set_property type {{verilogSource}} [ipx::get_files {hdl/rx_dma_test_src_Complex3Multiply_block.v} -of_objects [ipx::get_file_groups xilinx_anylanguagesynthesis -of_objects [ipx::current_core]]]
ipx::add_file {hdl/rx_dma_test_src_Complex3Multiply_block.v} [ipx::get_file_groups xilinx_anylanguagebehavioralsimulation -of_objects [ipx::current_core]]
set_property type {{verilogSource}} [ipx::get_files {hdl/rx_dma_test_src_Complex3Multiply_block.v} -of_objects [ipx::get_file_groups xilinx_anylanguagebehavioralsimulation -of_objects [ipx::current_core]]]
ipx::add_file {hdl/rx_dma_test_src_SDFCommutator5.v} [ipx::get_file_groups xilinx_anylanguagesynthesis -of_objects [ipx::current_core]]
set_property type {{verilogSource}} [ipx::get_files {hdl/rx_dma_test_src_SDFCommutator5.v} -of_objects [ipx::get_file_groups xilinx_anylanguagesynthesis -of_objects [ipx::current_core]]]
ipx::add_file {hdl/rx_dma_test_src_SDFCommutator5.v} [ipx::get_file_groups xilinx_anylanguagebehavioralsimulation -of_objects [ipx::current_core]]
set_property type {{verilogSource}} [ipx::get_files {hdl/rx_dma_test_src_SDFCommutator5.v} -of_objects [ipx::get_file_groups xilinx_anylanguagebehavioralsimulation -of_objects [ipx::current_core]]]
ipx::add_file {hdl/rx_dma_test_src_RADIX22FFT_SDF1_5.v} [ipx::get_file_groups xilinx_anylanguagesynthesis -of_objects [ipx::current_core]]
set_property type {{verilogSource}} [ipx::get_files {hdl/rx_dma_test_src_RADIX22FFT_SDF1_5.v} -of_objects [ipx::get_file_groups xilinx_anylanguagesynthesis -of_objects [ipx::current_core]]]
ipx::add_file {hdl/rx_dma_test_src_RADIX22FFT_SDF1_5.v} [ipx::get_file_groups xilinx_anylanguagebehavioralsimulation -of_objects [ipx::current_core]]
set_property type {{verilogSource}} [ipx::get_files {hdl/rx_dma_test_src_RADIX22FFT_SDF1_5.v} -of_objects [ipx::get_file_groups xilinx_anylanguagebehavioralsimulation -of_objects [ipx::current_core]]]
ipx::add_file {hdl/rx_dma_test_src_RADIX22FFT_CTRL1_5.v} [ipx::get_file_groups xilinx_anylanguagesynthesis -of_objects [ipx::current_core]]
set_property type {{verilogSource}} [ipx::get_files {hdl/rx_dma_test_src_RADIX22FFT_CTRL1_5.v} -of_objects [ipx::get_file_groups xilinx_anylanguagesynthesis -of_objects [ipx::current_core]]]
ipx::add_file {hdl/rx_dma_test_src_RADIX22FFT_CTRL1_5.v} [ipx::get_file_groups xilinx_anylanguagebehavioralsimulation -of_objects [ipx::current_core]]
set_property type {{verilogSource}} [ipx::get_files {hdl/rx_dma_test_src_RADIX22FFT_CTRL1_5.v} -of_objects [ipx::get_file_groups xilinx_anylanguagebehavioralsimulation -of_objects [ipx::current_core]]]
ipx::add_file {hdl/rx_dma_test_src_SDFCommutator6.v} [ipx::get_file_groups xilinx_anylanguagesynthesis -of_objects [ipx::current_core]]
set_property type {{verilogSource}} [ipx::get_files {hdl/rx_dma_test_src_SDFCommutator6.v} -of_objects [ipx::get_file_groups xilinx_anylanguagesynthesis -of_objects [ipx::current_core]]]
ipx::add_file {hdl/rx_dma_test_src_SDFCommutator6.v} [ipx::get_file_groups xilinx_anylanguagebehavioralsimulation -of_objects [ipx::current_core]]
set_property type {{verilogSource}} [ipx::get_files {hdl/rx_dma_test_src_SDFCommutator6.v} -of_objects [ipx::get_file_groups xilinx_anylanguagebehavioralsimulation -of_objects [ipx::current_core]]]
ipx::add_file {hdl/rx_dma_test_src_RADIX22FFT_SDF2_6.v} [ipx::get_file_groups xilinx_anylanguagesynthesis -of_objects [ipx::current_core]]
set_property type {{verilogSource}} [ipx::get_files {hdl/rx_dma_test_src_RADIX22FFT_SDF2_6.v} -of_objects [ipx::get_file_groups xilinx_anylanguagesynthesis -of_objects [ipx::current_core]]]
ipx::add_file {hdl/rx_dma_test_src_RADIX22FFT_SDF2_6.v} [ipx::get_file_groups xilinx_anylanguagebehavioralsimulation -of_objects [ipx::current_core]]
set_property type {{verilogSource}} [ipx::get_files {hdl/rx_dma_test_src_RADIX22FFT_SDF2_6.v} -of_objects [ipx::get_file_groups xilinx_anylanguagebehavioralsimulation -of_objects [ipx::current_core]]]
ipx::add_file {hdl/rx_dma_test_src_RADIX22FFT_CTRL1_6.v} [ipx::get_file_groups xilinx_anylanguagesynthesis -of_objects [ipx::current_core]]
set_property type {{verilogSource}} [ipx::get_files {hdl/rx_dma_test_src_RADIX22FFT_CTRL1_6.v} -of_objects [ipx::get_file_groups xilinx_anylanguagesynthesis -of_objects [ipx::current_core]]]
ipx::add_file {hdl/rx_dma_test_src_RADIX22FFT_CTRL1_6.v} [ipx::get_file_groups xilinx_anylanguagebehavioralsimulation -of_objects [ipx::current_core]]
set_property type {{verilogSource}} [ipx::get_files {hdl/rx_dma_test_src_RADIX22FFT_CTRL1_6.v} -of_objects [ipx::get_file_groups xilinx_anylanguagebehavioralsimulation -of_objects [ipx::current_core]]]
ipx::add_file {hdl/rx_dma_test_src_RADIX2FFT_bitNatural.v} [ipx::get_file_groups xilinx_anylanguagesynthesis -of_objects [ipx::current_core]]
set_property type {{verilogSource}} [ipx::get_files {hdl/rx_dma_test_src_RADIX2FFT_bitNatural.v} -of_objects [ipx::get_file_groups xilinx_anylanguagesynthesis -of_objects [ipx::current_core]]]
ipx::add_file {hdl/rx_dma_test_src_RADIX2FFT_bitNatural.v} [ipx::get_file_groups xilinx_anylanguagebehavioralsimulation -of_objects [ipx::current_core]]
set_property type {{verilogSource}} [ipx::get_files {hdl/rx_dma_test_src_RADIX2FFT_bitNatural.v} -of_objects [ipx::get_file_groups xilinx_anylanguagebehavioralsimulation -of_objects [ipx::current_core]]]
ipx::add_file {hdl/rx_dma_test_src_FFT.v} [ipx::get_file_groups xilinx_anylanguagesynthesis -of_objects [ipx::current_core]]
set_property type {{verilogSource}} [ipx::get_files {hdl/rx_dma_test_src_FFT.v} -of_objects [ipx::get_file_groups xilinx_anylanguagesynthesis -of_objects [ipx::current_core]]]
ipx::add_file {hdl/rx_dma_test_src_FFT.v} [ipx::get_file_groups xilinx_anylanguagebehavioralsimulation -of_objects [ipx::current_core]]
set_property type {{verilogSource}} [ipx::get_files {hdl/rx_dma_test_src_FFT.v} -of_objects [ipx::get_file_groups xilinx_anylanguagebehavioralsimulation -of_objects [ipx::current_core]]]
ipx::add_file {hdl/rx_dma_test_src_Channelizer_CH1.v} [ipx::get_file_groups xilinx_anylanguagesynthesis -of_objects [ipx::current_core]]
set_property type {{verilogSource}} [ipx::get_files {hdl/rx_dma_test_src_Channelizer_CH1.v} -of_objects [ipx::get_file_groups xilinx_anylanguagesynthesis -of_objects [ipx::current_core]]]
ipx::add_file {hdl/rx_dma_test_src_Channelizer_CH1.v} [ipx::get_file_groups xilinx_anylanguagebehavioralsimulation -of_objects [ipx::current_core]]
set_property type {{verilogSource}} [ipx::get_files {hdl/rx_dma_test_src_Channelizer_CH1.v} -of_objects [ipx::get_file_groups xilinx_anylanguagebehavioralsimulation -of_objects [ipx::current_core]]]
ipx::add_file {hdl/rx_dma_test_src_LDCR_D.v} [ipx::get_file_groups xilinx_anylanguagesynthesis -of_objects [ipx::current_core]]
set_property type {{verilogSource}} [ipx::get_files {hdl/rx_dma_test_src_LDCR_D.v} -of_objects [ipx::get_file_groups xilinx_anylanguagesynthesis -of_objects [ipx::current_core]]]
ipx::add_file {hdl/rx_dma_test_src_LDCR_D.v} [ipx::get_file_groups xilinx_anylanguagebehavioralsimulation -of_objects [ipx::current_core]]
set_property type {{verilogSource}} [ipx::get_files {hdl/rx_dma_test_src_LDCR_D.v} -of_objects [ipx::get_file_groups xilinx_anylanguagebehavioralsimulation -of_objects [ipx::current_core]]]
ipx::add_file {hdl/rx_dma_test_reset_sync.v} [ipx::get_file_groups xilinx_anylanguagesynthesis -of_objects [ipx::current_core]]
set_property type {{verilogSource}} [ipx::get_files {hdl/rx_dma_test_reset_sync.v} -of_objects [ipx::get_file_groups xilinx_anylanguagesynthesis -of_objects [ipx::current_core]]]
ipx::add_file {hdl/rx_dma_test_reset_sync.v} [ipx::get_file_groups xilinx_anylanguagebehavioralsimulation -of_objects [ipx::current_core]]
set_property type {{verilogSource}} [ipx::get_files {hdl/rx_dma_test_reset_sync.v} -of_objects [ipx::get_file_groups xilinx_anylanguagebehavioralsimulation -of_objects [ipx::current_core]]]
ipx::add_file {hdl/rx_dma_test_dut.v} [ipx::get_file_groups xilinx_anylanguagesynthesis -of_objects [ipx::current_core]]
set_property type {{verilogSource}} [ipx::get_files {hdl/rx_dma_test_dut.v} -of_objects [ipx::get_file_groups xilinx_anylanguagesynthesis -of_objects [ipx::current_core]]]
ipx::add_file {hdl/rx_dma_test_dut.v} [ipx::get_file_groups xilinx_anylanguagebehavioralsimulation -of_objects [ipx::current_core]]
set_property type {{verilogSource}} [ipx::get_files {hdl/rx_dma_test_dut.v} -of_objects [ipx::get_file_groups xilinx_anylanguagebehavioralsimulation -of_objects [ipx::current_core]]]
ipx::add_file {hdl/rx_dma_test_addr_decoder.v} [ipx::get_file_groups xilinx_anylanguagesynthesis -of_objects [ipx::current_core]]
set_property type {{verilogSource}} [ipx::get_files {hdl/rx_dma_test_addr_decoder.v} -of_objects [ipx::get_file_groups xilinx_anylanguagesynthesis -of_objects [ipx::current_core]]]
ipx::add_file {hdl/rx_dma_test_addr_decoder.v} [ipx::get_file_groups xilinx_anylanguagebehavioralsimulation -of_objects [ipx::current_core]]
set_property type {{verilogSource}} [ipx::get_files {hdl/rx_dma_test_addr_decoder.v} -of_objects [ipx::get_file_groups xilinx_anylanguagebehavioralsimulation -of_objects [ipx::current_core]]]
ipx::add_file {hdl/rx_dma_test_SimpleDualPortRAM_generic.v} [ipx::get_file_groups xilinx_anylanguagesynthesis -of_objects [ipx::current_core]]
set_property type {{verilogSource}} [ipx::get_files {hdl/rx_dma_test_SimpleDualPortRAM_generic.v} -of_objects [ipx::get_file_groups xilinx_anylanguagesynthesis -of_objects [ipx::current_core]]]
ipx::add_file {hdl/rx_dma_test_SimpleDualPortRAM_generic.v} [ipx::get_file_groups xilinx_anylanguagebehavioralsimulation -of_objects [ipx::current_core]]
set_property type {{verilogSource}} [ipx::get_files {hdl/rx_dma_test_SimpleDualPortRAM_generic.v} -of_objects [ipx::get_file_groups xilinx_anylanguagebehavioralsimulation -of_objects [ipx::current_core]]]
ipx::add_file {hdl/rx_dma_test_rdfifo_data.v} [ipx::get_file_groups xilinx_anylanguagesynthesis -of_objects [ipx::current_core]]
set_property type {{verilogSource}} [ipx::get_files {hdl/rx_dma_test_rdfifo_data.v} -of_objects [ipx::get_file_groups xilinx_anylanguagesynthesis -of_objects [ipx::current_core]]]
ipx::add_file {hdl/rx_dma_test_rdfifo_data.v} [ipx::get_file_groups xilinx_anylanguagebehavioralsimulation -of_objects [ipx::current_core]]
set_property type {{verilogSource}} [ipx::get_files {hdl/rx_dma_test_rdfifo_data.v} -of_objects [ipx::get_file_groups xilinx_anylanguagebehavioralsimulation -of_objects [ipx::current_core]]]
ipx::add_file {hdl/rx_dma_test_SimpleDualPortRAM_singlebit.v} [ipx::get_file_groups xilinx_anylanguagesynthesis -of_objects [ipx::current_core]]
set_property type {{verilogSource}} [ipx::get_files {hdl/rx_dma_test_SimpleDualPortRAM_singlebit.v} -of_objects [ipx::get_file_groups xilinx_anylanguagesynthesis -of_objects [ipx::current_core]]]
ipx::add_file {hdl/rx_dma_test_SimpleDualPortRAM_singlebit.v} [ipx::get_file_groups xilinx_anylanguagebehavioralsimulation -of_objects [ipx::current_core]]
set_property type {{verilogSource}} [ipx::get_files {hdl/rx_dma_test_SimpleDualPortRAM_singlebit.v} -of_objects [ipx::get_file_groups xilinx_anylanguagebehavioralsimulation -of_objects [ipx::current_core]]]
ipx::add_file {hdl/rx_dma_test_rdfifo_last.v} [ipx::get_file_groups xilinx_anylanguagesynthesis -of_objects [ipx::current_core]]
set_property type {{verilogSource}} [ipx::get_files {hdl/rx_dma_test_rdfifo_last.v} -of_objects [ipx::get_file_groups xilinx_anylanguagesynthesis -of_objects [ipx::current_core]]]
ipx::add_file {hdl/rx_dma_test_rdfifo_last.v} [ipx::get_file_groups xilinx_anylanguagebehavioralsimulation -of_objects [ipx::current_core]]
set_property type {{verilogSource}} [ipx::get_files {hdl/rx_dma_test_rdfifo_last.v} -of_objects [ipx::get_file_groups xilinx_anylanguagebehavioralsimulation -of_objects [ipx::current_core]]]
ipx::add_file {hdl/rx_dma_test_rdfifo_rid.v} [ipx::get_file_groups xilinx_anylanguagesynthesis -of_objects [ipx::current_core]]
set_property type {{verilogSource}} [ipx::get_files {hdl/rx_dma_test_rdfifo_rid.v} -of_objects [ipx::get_file_groups xilinx_anylanguagesynthesis -of_objects [ipx::current_core]]]
ipx::add_file {hdl/rx_dma_test_rdfifo_rid.v} [ipx::get_file_groups xilinx_anylanguagebehavioralsimulation -of_objects [ipx::current_core]]
set_property type {{verilogSource}} [ipx::get_files {hdl/rx_dma_test_rdfifo_rid.v} -of_objects [ipx::get_file_groups xilinx_anylanguagebehavioralsimulation -of_objects [ipx::current_core]]]
ipx::add_file {hdl/rx_dma_test_axi4_module.v} [ipx::get_file_groups xilinx_anylanguagesynthesis -of_objects [ipx::current_core]]
set_property type {{verilogSource}} [ipx::get_files {hdl/rx_dma_test_axi4_module.v} -of_objects [ipx::get_file_groups xilinx_anylanguagesynthesis -of_objects [ipx::current_core]]]
ipx::add_file {hdl/rx_dma_test_axi4_module.v} [ipx::get_file_groups xilinx_anylanguagebehavioralsimulation -of_objects [ipx::current_core]]
set_property type {{verilogSource}} [ipx::get_files {hdl/rx_dma_test_axi4_module.v} -of_objects [ipx::get_file_groups xilinx_anylanguagebehavioralsimulation -of_objects [ipx::current_core]]]
ipx::add_file {hdl/rx_dma_test_axi4.v} [ipx::get_file_groups xilinx_anylanguagesynthesis -of_objects [ipx::current_core]]
set_property type {{verilogSource}} [ipx::get_files {hdl/rx_dma_test_axi4.v} -of_objects [ipx::get_file_groups xilinx_anylanguagesynthesis -of_objects [ipx::current_core]]]
ipx::add_file {hdl/rx_dma_test_axi4.v} [ipx::get_file_groups xilinx_anylanguagebehavioralsimulation -of_objects [ipx::current_core]]
set_property type {{verilogSource}} [ipx::get_files {hdl/rx_dma_test_axi4.v} -of_objects [ipx::get_file_groups xilinx_anylanguagebehavioralsimulation -of_objects [ipx::current_core]]]
ipx::add_file {hdl/rx_dma_test.v} [ipx::get_file_groups xilinx_anylanguagesynthesis -of_objects [ipx::current_core]]
set_property type {{verilogSource}} [ipx::get_files {hdl/rx_dma_test.v} -of_objects [ipx::get_file_groups xilinx_anylanguagesynthesis -of_objects [ipx::current_core]]]
ipx::add_file {hdl/rx_dma_test.v} [ipx::get_file_groups xilinx_anylanguagebehavioralsimulation -of_objects [ipx::current_core]]
set_property type {{verilogSource}} [ipx::get_files {hdl/rx_dma_test.v} -of_objects [ipx::get_file_groups xilinx_anylanguagebehavioralsimulation -of_objects [ipx::current_core]]]

# Add bus interfaces
ipx::remove_all_bus_interface [ipx::current_core]
ipx::remove_all_memory_map [ipx::current_core]
ipx::remove_all_address_space [ipx::current_core]
# AXI4 Slave
ipx::add_bus_interface {AXI4} [ipx::current_core]
set_property abstraction_type_vlnv {xilinx.com:interface:aximm_rtl:1.0} [ipx::get_bus_interfaces AXI4 -of_objects [ipx::current_core]]
set_property bus_type_vlnv {xilinx.com:interface:aximm:1.0} [ipx::get_bus_interfaces AXI4 -of_objects [ipx::current_core]]
ipx::add_port_map {AWID} [ipx::get_bus_interfaces AXI4 -of_objects [ipx::current_core]]
set_property physical_name {AXI4_AWID} [ipx::get_port_maps AWID -of_objects [ipx::get_bus_interfaces AXI4 -of_objects [ipx::current_core]]]
ipx::add_port_map {AWADDR} [ipx::get_bus_interfaces AXI4 -of_objects [ipx::current_core]]
set_property physical_name {AXI4_AWADDR} [ipx::get_port_maps AWADDR -of_objects [ipx::get_bus_interfaces AXI4 -of_objects [ipx::current_core]]]
ipx::add_port_map {AWLEN} [ipx::get_bus_interfaces AXI4 -of_objects [ipx::current_core]]
set_property physical_name {AXI4_AWLEN} [ipx::get_port_maps AWLEN -of_objects [ipx::get_bus_interfaces AXI4 -of_objects [ipx::current_core]]]
ipx::add_port_map {AWSIZE} [ipx::get_bus_interfaces AXI4 -of_objects [ipx::current_core]]
set_property physical_name {AXI4_AWSIZE} [ipx::get_port_maps AWSIZE -of_objects [ipx::get_bus_interfaces AXI4 -of_objects [ipx::current_core]]]
ipx::add_port_map {AWBURST} [ipx::get_bus_interfaces AXI4 -of_objects [ipx::current_core]]
set_property physical_name {AXI4_AWBURST} [ipx::get_port_maps AWBURST -of_objects [ipx::get_bus_interfaces AXI4 -of_objects [ipx::current_core]]]
ipx::add_port_map {AWLOCK} [ipx::get_bus_interfaces AXI4 -of_objects [ipx::current_core]]
set_property physical_name {AXI4_AWLOCK} [ipx::get_port_maps AWLOCK -of_objects [ipx::get_bus_interfaces AXI4 -of_objects [ipx::current_core]]]
ipx::add_port_map {AWCACHE} [ipx::get_bus_interfaces AXI4 -of_objects [ipx::current_core]]
set_property physical_name {AXI4_AWCACHE} [ipx::get_port_maps AWCACHE -of_objects [ipx::get_bus_interfaces AXI4 -of_objects [ipx::current_core]]]
ipx::add_port_map {AWPROT} [ipx::get_bus_interfaces AXI4 -of_objects [ipx::current_core]]
set_property physical_name {AXI4_AWPROT} [ipx::get_port_maps AWPROT -of_objects [ipx::get_bus_interfaces AXI4 -of_objects [ipx::current_core]]]
ipx::add_port_map {AWVALID} [ipx::get_bus_interfaces AXI4 -of_objects [ipx::current_core]]
set_property physical_name {AXI4_AWVALID} [ipx::get_port_maps AWVALID -of_objects [ipx::get_bus_interfaces AXI4 -of_objects [ipx::current_core]]]
ipx::add_port_map {WDATA} [ipx::get_bus_interfaces AXI4 -of_objects [ipx::current_core]]
set_property physical_name {AXI4_WDATA} [ipx::get_port_maps WDATA -of_objects [ipx::get_bus_interfaces AXI4 -of_objects [ipx::current_core]]]
ipx::add_port_map {WSTRB} [ipx::get_bus_interfaces AXI4 -of_objects [ipx::current_core]]
set_property physical_name {AXI4_WSTRB} [ipx::get_port_maps WSTRB -of_objects [ipx::get_bus_interfaces AXI4 -of_objects [ipx::current_core]]]
ipx::add_port_map {WLAST} [ipx::get_bus_interfaces AXI4 -of_objects [ipx::current_core]]
set_property physical_name {AXI4_WLAST} [ipx::get_port_maps WLAST -of_objects [ipx::get_bus_interfaces AXI4 -of_objects [ipx::current_core]]]
ipx::add_port_map {WVALID} [ipx::get_bus_interfaces AXI4 -of_objects [ipx::current_core]]
set_property physical_name {AXI4_WVALID} [ipx::get_port_maps WVALID -of_objects [ipx::get_bus_interfaces AXI4 -of_objects [ipx::current_core]]]
ipx::add_port_map {BREADY} [ipx::get_bus_interfaces AXI4 -of_objects [ipx::current_core]]
set_property physical_name {AXI4_BREADY} [ipx::get_port_maps BREADY -of_objects [ipx::get_bus_interfaces AXI4 -of_objects [ipx::current_core]]]
ipx::add_port_map {ARID} [ipx::get_bus_interfaces AXI4 -of_objects [ipx::current_core]]
set_property physical_name {AXI4_ARID} [ipx::get_port_maps ARID -of_objects [ipx::get_bus_interfaces AXI4 -of_objects [ipx::current_core]]]
ipx::add_port_map {ARADDR} [ipx::get_bus_interfaces AXI4 -of_objects [ipx::current_core]]
set_property physical_name {AXI4_ARADDR} [ipx::get_port_maps ARADDR -of_objects [ipx::get_bus_interfaces AXI4 -of_objects [ipx::current_core]]]
ipx::add_port_map {ARLEN} [ipx::get_bus_interfaces AXI4 -of_objects [ipx::current_core]]
set_property physical_name {AXI4_ARLEN} [ipx::get_port_maps ARLEN -of_objects [ipx::get_bus_interfaces AXI4 -of_objects [ipx::current_core]]]
ipx::add_port_map {ARSIZE} [ipx::get_bus_interfaces AXI4 -of_objects [ipx::current_core]]
set_property physical_name {AXI4_ARSIZE} [ipx::get_port_maps ARSIZE -of_objects [ipx::get_bus_interfaces AXI4 -of_objects [ipx::current_core]]]
ipx::add_port_map {ARBURST} [ipx::get_bus_interfaces AXI4 -of_objects [ipx::current_core]]
set_property physical_name {AXI4_ARBURST} [ipx::get_port_maps ARBURST -of_objects [ipx::get_bus_interfaces AXI4 -of_objects [ipx::current_core]]]
ipx::add_port_map {ARLOCK} [ipx::get_bus_interfaces AXI4 -of_objects [ipx::current_core]]
set_property physical_name {AXI4_ARLOCK} [ipx::get_port_maps ARLOCK -of_objects [ipx::get_bus_interfaces AXI4 -of_objects [ipx::current_core]]]
ipx::add_port_map {ARCACHE} [ipx::get_bus_interfaces AXI4 -of_objects [ipx::current_core]]
set_property physical_name {AXI4_ARCACHE} [ipx::get_port_maps ARCACHE -of_objects [ipx::get_bus_interfaces AXI4 -of_objects [ipx::current_core]]]
ipx::add_port_map {ARPROT} [ipx::get_bus_interfaces AXI4 -of_objects [ipx::current_core]]
set_property physical_name {AXI4_ARPROT} [ipx::get_port_maps ARPROT -of_objects [ipx::get_bus_interfaces AXI4 -of_objects [ipx::current_core]]]
ipx::add_port_map {ARVALID} [ipx::get_bus_interfaces AXI4 -of_objects [ipx::current_core]]
set_property physical_name {AXI4_ARVALID} [ipx::get_port_maps ARVALID -of_objects [ipx::get_bus_interfaces AXI4 -of_objects [ipx::current_core]]]
ipx::add_port_map {RREADY} [ipx::get_bus_interfaces AXI4 -of_objects [ipx::current_core]]
set_property physical_name {AXI4_RREADY} [ipx::get_port_maps RREADY -of_objects [ipx::get_bus_interfaces AXI4 -of_objects [ipx::current_core]]]
ipx::add_port_map {AWREADY} [ipx::get_bus_interfaces AXI4 -of_objects [ipx::current_core]]
set_property physical_name {AXI4_AWREADY} [ipx::get_port_maps AWREADY -of_objects [ipx::get_bus_interfaces AXI4 -of_objects [ipx::current_core]]]
ipx::add_port_map {WREADY} [ipx::get_bus_interfaces AXI4 -of_objects [ipx::current_core]]
set_property physical_name {AXI4_WREADY} [ipx::get_port_maps WREADY -of_objects [ipx::get_bus_interfaces AXI4 -of_objects [ipx::current_core]]]
ipx::add_port_map {BID} [ipx::get_bus_interfaces AXI4 -of_objects [ipx::current_core]]
set_property physical_name {AXI4_BID} [ipx::get_port_maps BID -of_objects [ipx::get_bus_interfaces AXI4 -of_objects [ipx::current_core]]]
ipx::add_port_map {BRESP} [ipx::get_bus_interfaces AXI4 -of_objects [ipx::current_core]]
set_property physical_name {AXI4_BRESP} [ipx::get_port_maps BRESP -of_objects [ipx::get_bus_interfaces AXI4 -of_objects [ipx::current_core]]]
ipx::add_port_map {BVALID} [ipx::get_bus_interfaces AXI4 -of_objects [ipx::current_core]]
set_property physical_name {AXI4_BVALID} [ipx::get_port_maps BVALID -of_objects [ipx::get_bus_interfaces AXI4 -of_objects [ipx::current_core]]]
ipx::add_port_map {ARREADY} [ipx::get_bus_interfaces AXI4 -of_objects [ipx::current_core]]
set_property physical_name {AXI4_ARREADY} [ipx::get_port_maps ARREADY -of_objects [ipx::get_bus_interfaces AXI4 -of_objects [ipx::current_core]]]
ipx::add_port_map {RID} [ipx::get_bus_interfaces AXI4 -of_objects [ipx::current_core]]
set_property physical_name {AXI4_RID} [ipx::get_port_maps RID -of_objects [ipx::get_bus_interfaces AXI4 -of_objects [ipx::current_core]]]
ipx::add_port_map {RDATA} [ipx::get_bus_interfaces AXI4 -of_objects [ipx::current_core]]
set_property physical_name {AXI4_RDATA} [ipx::get_port_maps RDATA -of_objects [ipx::get_bus_interfaces AXI4 -of_objects [ipx::current_core]]]
ipx::add_port_map {RRESP} [ipx::get_bus_interfaces AXI4 -of_objects [ipx::current_core]]
set_property physical_name {AXI4_RRESP} [ipx::get_port_maps RRESP -of_objects [ipx::get_bus_interfaces AXI4 -of_objects [ipx::current_core]]]
ipx::add_port_map {RLAST} [ipx::get_bus_interfaces AXI4 -of_objects [ipx::current_core]]
set_property physical_name {AXI4_RLAST} [ipx::get_port_maps RLAST -of_objects [ipx::get_bus_interfaces AXI4 -of_objects [ipx::current_core]]]
ipx::add_port_map {RVALID} [ipx::get_bus_interfaces AXI4 -of_objects [ipx::current_core]]
set_property physical_name {AXI4_RVALID} [ipx::get_port_maps RVALID -of_objects [ipx::get_bus_interfaces AXI4 -of_objects [ipx::current_core]]]
ipx::add_bus_interface {AXI4_signal_clock} [ipx::current_core]
set_property abstraction_type_vlnv {xilinx.com:signal:clock_rtl:1.0} [ipx::get_bus_interfaces AXI4_signal_clock -of_objects [ipx::current_core]]
set_property bus_type_vlnv {xilinx.com:signal:clock:1.0} [ipx::get_bus_interfaces AXI4_signal_clock -of_objects [ipx::current_core]]
ipx::add_port_map {CLK} [ipx::get_bus_interfaces AXI4_signal_clock -of_objects [ipx::current_core]]
set_property physical_name {AXI4_ACLK} [ipx::get_port_maps CLK -of_objects [ipx::get_bus_interfaces AXI4_signal_clock -of_objects [ipx::current_core]]]
ipx::add_bus_interface {AXI4_signal_reset} [ipx::current_core]
set_property abstraction_type_vlnv {xilinx.com:signal:reset_rtl:1.0} [ipx::get_bus_interfaces AXI4_signal_reset -of_objects [ipx::current_core]]
set_property bus_type_vlnv {xilinx.com:signal:reset:1.0} [ipx::get_bus_interfaces AXI4_signal_reset -of_objects [ipx::current_core]]
ipx::add_port_map {RST} [ipx::get_bus_interfaces AXI4_signal_reset -of_objects [ipx::current_core]]
set_property physical_name {AXI4_ARESETN} [ipx::get_port_maps RST -of_objects [ipx::get_bus_interfaces AXI4_signal_reset -of_objects [ipx::current_core]]]
ipx::add_bus_parameter {ASSOCIATED_BUSIF} [ipx::get_bus_interfaces AXI4_signal_clock -of_objects [ipx::current_core]]
set_property value {AXI4} [ipx::get_bus_parameters ASSOCIATED_BUSIF -of_objects [ipx::get_bus_interfaces AXI4_signal_clock -of_objects [ipx::current_core]]]
ipx::add_bus_parameter {ASSOCIATED_RESET} [ipx::get_bus_interfaces AXI4_signal_clock -of_objects [ipx::current_core]]
set_property value {AXI4_ARESETN} [ipx::get_bus_parameters ASSOCIATED_RESET -of_objects [ipx::get_bus_interfaces AXI4_signal_clock -of_objects [ipx::current_core]]]
ipx::add_bus_parameter {POLARITY} [ipx::get_bus_interfaces AXI4_signal_reset -of_objects [ipx::current_core]]
set_property value {ACTIVE_LOW} [ipx::get_bus_parameters POLARITY -of_objects [ipx::get_bus_interfaces AXI4_signal_reset -of_objects [ipx::current_core]]]
ipx::add_memory_map {AXI4} [ipx::current_core]
set_property slave_memory_map_ref {AXI4} [ipx::get_bus_interfaces AXI4 -of_objects [ipx::current_core]]
ipx::add_address_block {reg0} [ipx::get_memory_maps AXI4 -of_objects [ipx::current_core]]
set_property range {65536} [ipx::get_address_blocks reg0 -of_objects [ipx::get_memory_maps AXI4 -of_objects [ipx::current_core]]]


# Add IP clock and reset definition
ipx::add_bus_interface {IPCORE_CLK} [ipx::current_core]
set_property abstraction_type_vlnv {xilinx.com:signal:clock_rtl:1.0} [ipx::get_bus_interfaces IPCORE_CLK -of_objects [ipx::current_core]]
set_property bus_type_vlnv {xilinx.com:signal:clock:1.0} [ipx::get_bus_interfaces IPCORE_CLK -of_objects [ipx::current_core]]
ipx::add_port_map {CLK} [ipx::get_bus_interfaces IPCORE_CLK -of_objects [ipx::current_core]]
set_property physical_name {IPCORE_CLK} [ipx::get_port_maps CLK -of_objects [ipx::get_bus_interfaces IPCORE_CLK -of_objects [ipx::current_core]]]
ipx::add_bus_interface {IPCORE_RESETN} [ipx::current_core]
set_property abstraction_type_vlnv {xilinx.com:signal:reset_rtl:1.0} [ipx::get_bus_interfaces IPCORE_RESETN -of_objects [ipx::current_core]]
set_property bus_type_vlnv {xilinx.com:signal:reset:1.0} [ipx::get_bus_interfaces IPCORE_RESETN -of_objects [ipx::current_core]]
ipx::add_port_map {RST} [ipx::get_bus_interfaces IPCORE_RESETN -of_objects [ipx::current_core]]
set_property physical_name {IPCORE_RESETN} [ipx::get_port_maps RST -of_objects [ipx::get_bus_interfaces IPCORE_RESETN -of_objects [ipx::current_core]]]
ipx::add_bus_parameter {ASSOCIATED_RESET} [ipx::get_bus_interfaces IPCORE_CLK -of_objects [ipx::current_core]]
set_property value {IPCORE_RESETN} [ipx::get_bus_parameters ASSOCIATED_RESET -of_objects [ipx::get_bus_interfaces IPCORE_CLK -of_objects [ipx::current_core]]]
ipx::add_bus_parameter {POLARITY} [ipx::get_bus_interfaces IPCORE_RESETN -of_objects [ipx::current_core]]
set_property value {ACTIVE_LOW} [ipx::get_bus_parameters POLARITY -of_objects [ipx::get_bus_interfaces IPCORE_RESETN -of_objects [ipx::current_core]]]


# Add report files
ipx::add_file_group -type {product_guide} {} [ipx::current_core]
ipx::add_file {doc/doc_arch_axi4.jpg} [ipx::get_file_groups xilinx_productguide -of_objects [ipx::current_core]]
set_property type {{image}} [ipx::get_files {doc/doc_arch_axi4.jpg} -of_objects [ipx::get_file_groups xilinx_productguide -of_objects [ipx::current_core]]]
ipx::add_file {doc/free_running.jpg} [ipx::get_file_groups xilinx_productguide -of_objects [ipx::current_core]]
set_property type {{image}} [ipx::get_files {doc/free_running.jpg} -of_objects [ipx::get_file_groups xilinx_productguide -of_objects [ipx::current_core]]]
ipx::add_file {doc/rx_dma_test_ip_core_report.html} [ipx::get_file_groups xilinx_productguide -of_objects [ipx::current_core]]
set_property type {{html}} [ipx::get_files {doc/rx_dma_test_ip_core_report.html} -of_objects [ipx::get_file_groups xilinx_productguide -of_objects [ipx::current_core]]]

# Add C files
ipx::add_file_group -type {misc} {} [ipx::current_core]
ipx::add_file {include/rx_dma_test_addr.h} [ipx::get_file_groups xilinx_miscfiles -of_objects [ipx::current_core]]
set_property type {{cSource}} [ipx::get_files {include/rx_dma_test_addr.h} -of_objects [ipx::get_file_groups xilinx_miscfiles -of_objects [ipx::current_core]]]

# Package IP
ipx::create_xgui_files [ipx::current_core]
ipx::check_integrity -quiet [ipx::current_core]
ipx::save_core [ipx::current_core]
ipx::archive_core {../rx_dma_test_v1_0.zip} [ipx::current_core]
close_project
exit
